/* Genreactrix AI AMA Engine v2 — persistent resumable AMA runs + immutable completed reports. */
(()=>{'use strict';
const DB='genreactrix-ai-ama',VERSION=2,REPORTS='reports',FOLLOWUPS='followups',OUTCOMES='outcomes',RUNS='runs';
const clone=v=>v==null?v:structuredClone(v),now=()=>new Date().toISOString(),uid=p=>`${p}_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`;
const openDb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(REPORTS)){const s=db.createObjectStore(REPORTS,{keyPath:'id'});s.createIndex('imageId','imageId');s.createIndex('createdAt','createdAt')}if(!db.objectStoreNames.contains(FOLLOWUPS)){const s=db.createObjectStore(FOLLOWUPS,{keyPath:'id'});s.createIndex('reportId','reportId');s.createIndex('createdAt','createdAt')}if(!db.objectStoreNames.contains(OUTCOMES)){const s=db.createObjectStore(OUTCOMES,{keyPath:'id'});s.createIndex('imageId','imageId');s.createIndex('reportId','reportId');s.createIndex('createdAt','createdAt')}if(!db.objectStoreNames.contains(RUNS)){const s=db.createObjectStore(RUNS,{keyPath:'id'});s.createIndex('imageId','imageId');s.createIndex('status','status');s.createIndex('updatedAt','updatedAt')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
const tx=(store,mode,fn)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,mode),s=t.objectStore(store);let out;try{out=fn(s,t)}catch(error){db.close();reject(error);return}t.oncomplete=()=>{db.close();resolve(out)};t.onerror=()=>{db.close();reject(t.error||new Error('AMA database transaction failed'))};t.onabort=()=>{db.close();reject(t.error||new Error('AMA database transaction aborted'))}}));
const put=(store,value)=>tx(store,'readwrite',s=>s.put(clone(value)));
const get=(store,id)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readonly'),r=t.objectStore(store).get(String(id));r.onsuccess=()=>resolve(r.result?clone(r.result):null);r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
const all=store=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readonly'),r=t.objectStore(store).getAll();r.onsuccess=()=>resolve((r.result||[]).map(clone));r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
const byIndex=(store,index,value)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readonly'),r=t.objectStore(store).index(index).getAll(value);r.onsuccess=()=>resolve((r.result||[]).map(clone));r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
function labels(rows=[]){return(rows||[]).map(row=>String(row?.label||row?.name||row?.code||'').trim()).filter(Boolean)}
function reportTitle(sequence,createdAt,aiThemes,directorThemes){const stamp=new Date(createdAt||Date.now()).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});const ai=labels(aiThemes).join(' / ')||'—',director=labels(directorThemes).join(' / ')||'—';return`${sequence}. ${stamp} — AI: ${ai} ↔ Director: ${director}`}
async function reportsForImage(imageId){return(await byIndex(REPORTS,'imageId',String(imageId))).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
async function createReport(input={}){if(!input.imageId)throw new Error('AMA report requires imageId');const existing=await reportsForImage(input.imageId),sequence=existing.length+1,createdAt=input.createdAt||now(),report={id:String(input.id||uid('ama_report')),schemaVersion:2,projectId:String(input.projectId||window.genreactrixProjectRuntimeEngine?.projectId?.()||''),runtimeId:input.runtimeId??window.genreactrixProjectRuntimeEngine?.runtimeId?.()??null,imageId:String(input.imageId),sequence,createdAt,title:reportTitle(sequence,createdAt,input.snapshot?.aiThemes,input.snapshot?.directorThemes),snapshot:clone(input.snapshot||{}),interview:clone(input.interview||{}),worker:clone(input.worker||{}),siteVersion:String(input.siteVersion||window.GENREACTRIX_BUILD||''),matrixVersion:String(input.matrixVersion||input.interview?.matrixVersion||'0.0.0.0'),immutable:true};await put(REPORTS,report);return clone(report)}
function questionNumber(id){const m=String(id||'').match(/^Q(\d+)$/i);return m?Number(m[1]):Number.MAX_SAFE_INTEGER}
function mergeQuestions(existing=[],incoming=[]){const rows=new Map();for(const q of [...existing,...incoming]){const id=String(q?.id||'').toUpperCase();if(!/^Q\d+$/.test(id)||!String(q?.answer||'').trim())continue;rows.set(id,{...clone(q),id})}return[...rows.values()].sort((a,b)=>questionNumber(a.id)-questionNumber(b.id))}
function runProgress(run){const questions=mergeQuestions([],run?.questions||[]),expected=Math.max(0,Number(run?.questionCount)||68),blocks=[...new Set((run?.completedBlockIndexes||[]).map(Number).filter(Number.isInteger))].sort((a,b)=>a-b);return{answered:questions.length,expected,completedBlockIndexes:blocks,blockCount:Math.max(0,Number(run?.blockCount)||0)}}
async function runsForImage(imageId){return(await byIndex(RUNS,'imageId',String(imageId))).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
async function incompleteRunsForImage(imageId){return(await runsForImage(imageId)).filter(run=>run.status!=='complete')}
async function latestIncompleteRun(imageId){return(await incompleteRunsForImage(imageId)).at(-1)||null}
async function createRun(input={}){if(!input.imageId)throw new Error('AMA run requires imageId');const createdAt=input.createdAt||now(),run={id:String(input.id||uid('ama_run')),schemaVersion:2,amaVersion:'AMA-2-resumable',projectId:String(input.projectId||window.genreactrixProjectRuntimeEngine?.projectId?.()||''),runtimeId:input.runtimeId??window.genreactrixProjectRuntimeEngine?.runtimeId?.()??null,imageId:String(input.imageId),createdAt,updatedAt:createdAt,status:'incomplete',stage:'created',snapshot:clone(input.snapshot||{}),siteVersion:String(input.siteVersion||window.GENREACTRIX_BUILD||''),workerVersion:'',matrixVersion:'0.0.0.0',model:'',visualRead:'',candidateThemeCodes:[],themeDefinitions:[],questionCount:68,blockSize:9,blockCount:0,questionBlocks:[],questions:[],completedBlockIndexes:[],errors:[],reportId:null};await put(RUNS,run);return clone(run)}
async function getRun(runId){return get(RUNS,String(runId))}
async function saveRun(run){if(!run?.id)throw new Error('AMA run requires id');const next={...clone(run),updatedAt:now()};await put(RUNS,next);return clone(next)}
async function checkpointRun(runId,patch={}){const run=await getRun(runId);if(!run)throw new Error('AMA run not found');const next={...run,...clone(patch),id:run.id,imageId:run.imageId,snapshot:run.snapshot,updatedAt:now()};if(patch.questions)next.questions=mergeQuestions(run.questions||[],patch.questions);if(patch.completedBlockIndexes)next.completedBlockIndexes=[...new Set(patch.completedBlockIndexes.map(Number).filter(Number.isInteger))].sort((a,b)=>a-b);await put(RUNS,next);return clone(next)}
async function saveQuestionBlock(runId,{questions=[],blockIndex=null,complete=false,meta={}}={}){const run=await getRun(runId);if(!run)throw new Error('AMA run not found');const completed=[...(run.completedBlockIndexes||[])];if(complete&&Number.isInteger(Number(blockIndex))&&!completed.includes(Number(blockIndex)))completed.push(Number(blockIndex));const next={...run,...clone(meta),stage:'questions',questions:mergeQuestions(run.questions||[],questions),completedBlockIndexes:[...new Set(completed)].sort((a,b)=>a-b),updatedAt:now(),status:'incomplete'};await put(RUNS,next);return clone(next)}
async function recordRunError(runId,error,meta={}){const run=await getRun(runId);if(!run)return null;const questionIds=Array.isArray(meta.questionIds)?[...new Set(meta.questionIds.map(id=>String(id||'').toUpperCase()).filter(id=>/^Q\d+$/.test(id)))]:[];const row={at:now(),stage:String(meta.stage||run.stage||'unknown'),blockIndex:Number.isInteger(Number(meta.blockIndex))?Number(meta.blockIndex):null,questionIds,recoveryLevel:String(meta.recoveryLevel||''),message:String(error?.message||error||'Unknown AMA error').slice(0,2000)};const next={...run,status:'incomplete',lastError:row,errors:[...(run.errors||[]),row].slice(-30),updatedAt:now()};await put(RUNS,next);return clone(next)}
async function finalizeRun(runId){let run=await getRun(runId);if(!run)throw new Error('AMA run not found');if(run.reportId){const prior=await get(REPORTS,run.reportId);if(prior)return prior}const progress=runProgress(run),expected=progress.expected||68;if(progress.answered!==expected)throw new Error(`AI AMA is incomplete: ${progress.answered}/${expected} core questions saved.`);if(run.blockCount&&progress.completedBlockIndexes.length!==Number(run.blockCount))throw new Error(`AI AMA is incomplete: ${progress.completedBlockIndexes.length}/${run.blockCount} question blocks complete.`);const reportId=String(run.reportId||`ama_report_${run.id}`),existing=await get(REPORTS,reportId);let report=existing;if(!report){const completedAt=now(),interview={schemaVersion:2,amaVersion:run.amaVersion||'AMA-2-resumable',createdAt:run.createdAt,completedAt,workerVersion:run.workerVersion||'',matrixVersion:run.matrixVersion||'0.0.0.0',model:run.model||'',visualRead:run.visualRead||'',candidateThemeCodes:clone(run.candidateThemeCodes||[]),themeDefinitions:clone(run.themeDefinitions||[]),questionCount:expected,questions:mergeQuestions([],run.questions||[]),resumable:{runId:run.id,blockSize:Number(run.blockSize)||9,blockCount:Number(run.blockCount)||0}};report=await createReport({id:reportId,imageId:run.imageId,createdAt:run.createdAt,snapshot:run.snapshot,interview,worker:{version:run.workerVersion||''},siteVersion:run.siteVersion,matrixVersion:run.matrixVersion||'0.0.0.0'})}run={...run,status:'complete',stage:'complete',reportId:report.id,completedAt:now(),lastError:null,updatedAt:now()};await put(RUNS,run);return clone(report)}
async function addFollowup(reportId,question,answer,meta={}){const report=await get(REPORTS,reportId);if(!report)throw new Error('AMA report not found');const row={id:uid('ama_followup'),schemaVersion:1,reportId:String(reportId),imageId:String(report.imageId),createdAt:now(),question:String(question||'').trim(),answer:String(answer||'').trim(),meta:clone(meta)};if(!row.question||!row.answer)throw new Error('AMA follow-up requires question and answer');await put(FOLLOWUPS,row);return clone(row)}
async function followupsForReport(reportId){return(await byIndex(FOLLOWUPS,'reportId',String(reportId))).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
async function outcomesForReport(reportId){return(await byIndex(OUTCOMES,'reportId',String(reportId))).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
function themeSet(rows=[]){return new Set(labels(rows).map(x=>x.toLowerCase()))}
function sameSet(a=[],b=[]){const A=themeSet(a),B=themeSet(b);return A.size===B.size&&[...A].every(x=>B.has(x))}
async function recordBatchOutcome({imageId,batchId,submissionVersion=0,submittedAt=null,finalDirectorThemes=[]}={}){const reports=await reportsForImage(imageId);if(!reports.length)return 0;let count=0;for(const report of reports){const id=`ama_outcome:${report.id}:${batchId||'batch'}:${submissionVersion||0}`;if(await get(OUTCOMES,id))continue;const exact=sameSet(report.snapshot?.aiThemes||[],finalDirectorThemes||[]),overlap=[...themeSet(report.snapshot?.aiThemes||[])].filter(x=>themeSet(finalDirectorThemes||[]).has(x)).length,row={id,schemaVersion:1,reportId:report.id,imageId:String(imageId),createdAt:submittedAt||now(),batchId:batchId||null,submissionVersion:Number(submissionVersion)||0,finalDirectorThemes:clone(finalDirectorThemes||[]),aiThemesAtAma:clone(report.snapshot?.aiThemes||[]),verdict:exact?'agreement':'director-final',overlapCount:overlap};await put(OUTCOMES,row);count++}return count}
async function getReport(reportId){return get(REPORTS,String(reportId))}
async function getReportBundle(reportId){const report=await get(REPORTS,reportId);if(!report)return null;const [followups,outcomes]=await Promise.all([followupsForReport(reportId),outcomesForReport(reportId)]);return{report,followups,outcomes}}
async function exportImageBundle(imageId){const reports=await reportsForImage(imageId),bundles=[];for(const report of reports)bundles.push(await getReportBundle(report.id));return{schemaVersion:2,imageId:String(imageId),exportedAt:now(),reports:bundles}}
async function verify(){const [reports,followups,outcomes,runs]=await Promise.all([all(REPORTS),all(FOLLOWUPS),all(OUTCOMES),all(RUNS)]),ids=new Set(reports.map(r=>r.id)),issues=[];for(const f of followups)if(!ids.has(f.reportId))issues.push({type:'ama-followup-missing-report',followupId:f.id,reportId:f.reportId});for(const o of outcomes)if(!ids.has(o.reportId))issues.push({type:'ama-outcome-missing-report',outcomeId:o.id,reportId:o.reportId});for(const run of runs)if(run.status==='complete'&&run.reportId&&!ids.has(run.reportId))issues.push({type:'ama-run-missing-report',runId:run.id,reportId:run.reportId});return{checkedAt:now(),reportCount:reports.length,followupCount:followups.length,outcomeCount:outcomes.length,runCount:runs.length,incompleteRunCount:runs.filter(r=>r.status!=='complete').length,issueCount:issues.length,issues}}
const engine={createReport,reportsForImage,getReport,getReportBundle,addFollowup,followupsForReport,outcomesForReport,recordBatchOutcome,exportImageBundle,createRun,getRun,saveRun,checkpointRun,saveQuestionBlock,recordRunError,runsForImage,incompleteRunsForImage,latestIncompleteRun,runProgress,finalizeRun,verify,dbName:DB};
window.genreactrixAmaEngine=engine;window.genreactrixAMAEngine=engine;
window.addEventListener('DOMContentLoaded',()=>window.genreactrixMaintenanceEngine?.registerChecker?.('ama-history',verify,{quick:false,label:'AI AMA History'}));
})();
