/* Genreactrix AI AMA Engine v1 — immutable per-image AMA reports + linked outcomes/follow-ups. */
(()=>{'use strict';
const DB='genreactrix-ai-ama',VERSION=1,REPORTS='reports',FOLLOWUPS='followups',OUTCOMES='outcomes';
const clone=v=>v==null?v:structuredClone(v),now=()=>new Date().toISOString(),uid=p=>`${p}_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`;
const openDb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(REPORTS)){const s=db.createObjectStore(REPORTS,{keyPath:'id'});s.createIndex('imageId','imageId');s.createIndex('createdAt','createdAt')}if(!db.objectStoreNames.contains(FOLLOWUPS)){const s=db.createObjectStore(FOLLOWUPS,{keyPath:'id'});s.createIndex('reportId','reportId');s.createIndex('createdAt','createdAt')}if(!db.objectStoreNames.contains(OUTCOMES)){const s=db.createObjectStore(OUTCOMES,{keyPath:'id'});s.createIndex('imageId','imageId');s.createIndex('reportId','reportId');s.createIndex('createdAt','createdAt')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
const tx=(store,mode,fn)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,mode),s=t.objectStore(store);let out;try{out=fn(s,t)}catch(error){db.close();reject(error);return}t.oncomplete=()=>{db.close();resolve(out)};t.onerror=()=>{db.close();reject(t.error||new Error('AMA database transaction failed'))};t.onabort=()=>{db.close();reject(t.error||new Error('AMA database transaction aborted'))}}));
const put=(store,value)=>tx(store,'readwrite',s=>s.put(clone(value)));
const get=(store,id)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readonly'),r=t.objectStore(store).get(String(id));r.onsuccess=()=>resolve(r.result?clone(r.result):null);r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
const all=store=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readonly'),r=t.objectStore(store).getAll();r.onsuccess=()=>resolve((r.result||[]).map(clone));r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
const byIndex=(store,index,value)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readonly'),r=t.objectStore(store).index(index).getAll(value);r.onsuccess=()=>resolve((r.result||[]).map(clone));r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
function labels(rows=[]){return(rows||[]).map(row=>String(row?.label||row?.name||row?.code||'').trim()).filter(Boolean)}
function reportTitle(sequence,createdAt,aiThemes,directorThemes){const stamp=new Date(createdAt||Date.now()).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});const ai=labels(aiThemes).join(' / ')||'—',director=labels(directorThemes).join(' / ')||'—';return`${sequence}. ${stamp} — AI: ${ai} ↔ Director: ${director}`}
async function reportsForImage(imageId){return(await byIndex(REPORTS,'imageId',String(imageId))).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
async function createReport(input={}){if(!input.imageId)throw new Error('AMA report requires imageId');const existing=await reportsForImage(input.imageId),sequence=existing.length+1,createdAt=input.createdAt||now(),report={id:String(input.id||uid('ama_report')),schemaVersion:1,projectId:String(input.projectId||window.genreactrixProjectRuntimeEngine?.projectId?.()||''),runtimeId:input.runtimeId??window.genreactrixProjectRuntimeEngine?.runtimeId?.()??null,imageId:String(input.imageId),sequence,createdAt,title:reportTitle(sequence,createdAt,input.snapshot?.aiThemes,input.snapshot?.directorThemes),snapshot:clone(input.snapshot||{}),interview:clone(input.interview||{}),worker:clone(input.worker||{}),siteVersion:String(input.siteVersion||window.GENREACTRIX_BUILD||''),matrixVersion:String(input.matrixVersion||input.interview?.matrixVersion||'0.0.0.0'),immutable:true};await put(REPORTS,report);return clone(report)}
async function addFollowup(reportId,question,answer,meta={}){const report=await get(REPORTS,reportId);if(!report)throw new Error('AMA report not found');const row={id:uid('ama_followup'),schemaVersion:1,reportId:String(reportId),imageId:String(report.imageId),createdAt:now(),question:String(question||'').trim(),answer:String(answer||'').trim(),meta:clone(meta)};if(!row.question||!row.answer)throw new Error('AMA follow-up requires question and answer');await put(FOLLOWUPS,row);return clone(row)}
async function followupsForReport(reportId){return(await byIndex(FOLLOWUPS,'reportId',String(reportId))).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
async function outcomesForReport(reportId){return(await byIndex(OUTCOMES,'reportId',String(reportId))).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
function themeSet(rows=[]){return new Set(labels(rows).map(x=>x.toLowerCase()))}
function sameSet(a=[],b=[]){const A=themeSet(a),B=themeSet(b);return A.size===B.size&&[...A].every(x=>B.has(x))}
async function recordBatchOutcome({imageId,batchId,submissionVersion=0,submittedAt=null,finalDirectorThemes=[]}={}){const reports=await reportsForImage(imageId);if(!reports.length)return 0;let count=0;for(const report of reports){const id=`ama_outcome:${report.id}:${batchId||'batch'}:${submissionVersion||0}`;if(await get(OUTCOMES,id))continue;const exact=sameSet(report.snapshot?.aiThemes||[],finalDirectorThemes||[]),overlap=[...themeSet(report.snapshot?.aiThemes||[])].filter(x=>themeSet(finalDirectorThemes||[]).has(x)).length,row={id,schemaVersion:1,reportId:report.id,imageId:String(imageId),createdAt:submittedAt||now(),batchId:batchId||null,submissionVersion:Number(submissionVersion)||0,finalDirectorThemes:clone(finalDirectorThemes||[]),aiThemesAtAma:clone(report.snapshot?.aiThemes||[]),verdict:exact?'agreement':'director-final',overlapCount:overlap};await put(OUTCOMES,row);count++}return count}
async function getReportBundle(reportId){const report=await get(REPORTS,reportId);if(!report)return null;const [followups,outcomes]=await Promise.all([followupsForReport(reportId),outcomesForReport(reportId)]);return{report,followups,outcomes}}
async function exportImageBundle(imageId){const reports=await reportsForImage(imageId),bundles=[];for(const report of reports)bundles.push(await getReportBundle(report.id));return{schemaVersion:1,imageId:String(imageId),exportedAt:now(),reports:bundles}}
async function verify(){const [reports,followups,outcomes]=await Promise.all([all(REPORTS),all(FOLLOWUPS),all(OUTCOMES)]),ids=new Set(reports.map(r=>r.id)),issues=[];for(const f of followups)if(!ids.has(f.reportId))issues.push({type:'ama-followup-missing-report',followupId:f.id,reportId:f.reportId});for(const o of outcomes)if(!ids.has(o.reportId))issues.push({type:'ama-outcome-missing-report',outcomeId:o.id,reportId:o.reportId});return{checkedAt:now(),reportCount:reports.length,followupCount:followups.length,outcomeCount:outcomes.length,issueCount:issues.length,issues}}
const engine={createReport,reportsForImage,getReport,getReportBundle,addFollowup,followupsForReport,outcomesForReport,recordBatchOutcome,exportImageBundle,verify,dbName:DB};
window.genreactrixAmaEngine=engine;window.genreactrixAMAEngine=engine;
window.addEventListener('DOMContentLoaded',()=>window.genreactrixMaintenanceEngine?.registerChecker?.('ama-history',verify,{quick:false,label:'AI AMA History'}));
})();
