(()=>{
'use strict';
const DB='genreactrix-batch-engine-v1', STORE='batches', META='meta', REPORTS='reports', VERSION=1;
const now=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('status','status');s.createIndex('createdAt','createdAt')}if(!db.objectStoreNames.contains(META))db.createObjectStore(META,{keyPath:'key'});if(!db.objectStoreNames.contains(REPORTS)){const s=db.createObjectStore(REPORTS,{keyPath:'id'});s.createIndex('batchId','batchId');s.createIndex('createdAt','createdAt')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function store(name,mode='readonly'){const db=await openDb();return db.transaction(name,mode).objectStore(name)}
async function getAll(name){const s=await store(name);return new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function get(name,key){const s=await store(name);return new Promise((res,rej)=>{const r=s.get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function put(name,value){const s=await store(name,'readwrite');return new Promise((res,rej)=>{const r=s.put(value);r.onsuccess=()=>res(value);r.onerror=()=>rej(r.error)})}
async function activeId(){return (await get(META,'active'))?.value||null}
async function setActive(id){await put(META,{key:'active',value:id});emit();return id}
function recordEngine(){return window.genreactrixImageRecordEngine}
function history(){return window.genreactrixHistoryEngine}
function eligible(record){return record&&!record.attributes?.inRecycleBin&&!record.attributes?.failed&&Boolean(record.source?.originalLocation||record.source?.originalUrl||record.storage?.temporaryKey||record.storage?.referenceKey||record.storage?.hyperlink)}
function classified(record){const d=record.analysis?.director;const reactions=Array.isArray(d?.selectedReactions)&&d.selectedReactions.length>0;const themes=Array.isArray(d?.themes)&&d.themes.some(Boolean);const primNeeded=(d?.selectedReactions?.length||0)>=2;const primOk=!primNeeded||record.components?.primFusion==='current';return reactions&&themes&&primOk}
function counts(batch){const records=(batch?.imageIds||[]).map(id=>recordEngine()?.get(id,{touch:false})).filter(Boolean);return{total:records.length,ready:records.filter(classified).length,incomplete:records.filter(r=>!classified(r)&&!r.attributes?.flagged).length,flagged:records.filter(r=>r.attributes?.flagged).length,saved:records.filter(r=>r.attributes?.saved).length,inaccessible:records.filter(r=>!eligible(r)).length,remaining:records.filter(r=>!classified(r)).length}}
async function create({name='Imported Work',imageIds=[],activate=true}={}){const batch={id:uid('batch'),schemaVersion:1,name,status:'draft',imageIds:[...new Set(imageIds)],createdAt:now(),startedAt:null,completedAt:null,submittedAt:null,reopenedAt:null,archivedAt:null,submissionVersion:0,reportIds:[],notes:''};await put(STORE,batch);for(const id of batch.imageIds){const r=recordEngine()?.get(id,{touch:false});if(r)recordEngine().update(id,{batchIds:[...new Set([...(r.batchIds||[]),batch.id])],source:{firstBatchId:r.source?.firstBatchId==='current-import'?batch.id:r.source?.firstBatchId}},'batch-added')}await history()?.append?.({imageId:null,eventType:'batch-created',actor:'system',sourceEngine:'batch',batchId:batch.id,summary:`Batch created: ${batch.name}`,payload:{batch}}).catch(()=>{});if(activate)await setActive(batch.id);emit();return batch}
async function all(){return getAll(STORE)}
async function active(){const id=await activeId();return id?get(STORE,id):null}
async function update(id,patch,eventType='batch-updated'){const b=await get(STORE,id);if(!b)throw new Error('Batch not found');const next={...b,...patch,imageIds:patch.imageIds?[...new Set(patch.imageIds)]:b.imageIds,updatedAt:now()};await put(STORE,next);await history()?.append?.({imageId:null,eventType,actor:'director',sourceEngine:'batch',batchId:id,summary:eventType.replaceAll('-',' '),payload:{before:b,current:next}}).catch(()=>{});emit();return next}
async function addImages(id,imageIds){const b=await get(STORE,id);if(!b)throw new Error('Batch not found');const added=[...new Set(imageIds)].filter(x=>!b.imageIds.includes(x));for(const imageId of added){const r=recordEngine()?.get(imageId,{touch:false});if(r)recordEngine().update(imageId,{batchIds:[...new Set([...(r.batchIds||[]),id])]},'batch-added')}return update(id,{imageIds:[...b.imageIds,...added],status:b.status==='draft'?'active':b.status,startedAt:b.startedAt||now()},'batch-images-added')}
async function removeImages(id,imageIds){const b=await get(STORE,id);const remove=new Set(imageIds);return update(id,{imageIds:b.imageIds.filter(x=>!remove.has(x))},'batch-images-removed')}
async function migrate(){let batches=await all();if(batches.length)return batches;const records=recordEngine()?.all?.()||[];const ids=records.filter(r=>(r.batchIds||[]).includes('current-import')||r.source?.firstBatchId==='current-import').map(r=>r.id);if(ids.length)return[await create({name:'Imported Work',imageIds:ids,activate:true})];return[await create({name:'New Batch',imageIds:[],activate:true})]}
function standardReport(batch){const records=batch.imageIds.map(id=>recordEngine()?.get(id,{touch:false})).filter(Boolean);const reactionTotals={},themeTotals={},primFusionTotals={};let aiCovered=0;for(const r of records){const d=r.analysis?.director||{};(d.selectedReactions||[]).forEach(x=>reactionTotals[x]=(reactionTotals[x]||0)+1);(d.themes||[]).filter(Boolean).forEach(x=>{const key=typeof x==='string'?x:(x.label||x.id||'Unknown');themeTotals[key]=(themeTotals[key]||0)+1});if((d.selectedReactions||[]).length>=2){const key=(d.selectedReactions||[]).join(' × ');primFusionTotals[key]=(primFusionTotals[key]||0)+1}if(r.analysis?.ai&&Object.keys(r.analysis.ai).length)aiCovered++}return{id:uid('report'),schemaVersion:1,batchId:batch.id,batchName:batch.name,submissionVersion:batch.submissionVersion+1,createdAt:now(),counts:counts(batch),reactionTotals,themeTotals,primFusionTotals,aiCoverage:aiCovered,sourceSummary:records.reduce((a,r)=>{const k=r.source?.type||'unknown';a[k]=(a[k]||0)+1;return a},{}),imageIds:[...batch.imageIds]}}
async function validate(id){const b=await get(STORE,id);if(!b)throw new Error('Batch not found');const c=counts(b);return{batch:b,counts:c,canSubmit:c.total>0&&c.incomplete===0&&c.inaccessible===0}}
async function submit(id,{allowFlagged=true}={}){const check=await validate(id);if(!check.counts.total)throw new Error('Batch is empty');if(check.counts.inaccessible)throw new Error(`${check.counts.inaccessible} image(s) are inaccessible`);if(check.counts.incomplete)throw new Error(`${check.counts.incomplete} non-flagged image(s) are incomplete`);const b=check.batch;const report=standardReport(b);await put(REPORTS,report);for(const imageId of b.imageIds){const r=recordEngine()?.get(imageId,{touch:false});if(!r)continue;recordEngine().update(imageId,{workflow:{stage:'batched'},timestamps:{batchedAt:now()}},'batch-submitted')}const submitted=await update(id,{status:'submitted',submittedAt:now(),completedAt:now(),submissionVersion:(b.submissionVersion||0)+1,reportIds:[...(b.reportIds||[]),report.id]},'batch-submitted');let recycled=0;for(const imageId of b.imageIds){const r=recordEngine()?.get(imageId,{touch:false});if(r?.storage?.mode==='temporary'&&!r.attributes?.saved&&!r.attributes?.flagged){if(await window.genreactrixImagesEngine?.moveToRecycle?.(imageId))recycled++}}await history()?.append?.({imageId:null,eventType:'batch-report-generated',actor:'system',sourceEngine:'batch',batchId:id,summary:'Standard batch report generated',payload:{reportId:report.id,counts:report.counts,recycled}}).catch(()=>{});await create({name:'New Batch',imageIds:[],activate:true});emit();return{submitted,report,recycled}}
async function reopen(id){const b=await get(STORE,id);if(!b||b.status!=='submitted')throw new Error('Only submitted batches can be reopened');const next=await update(id,{status:'reopened',reopenedAt:now()},'batch-reopened');await setActive(id);return next}
async function archive(id){return update(id,{status:'archived',archivedAt:now()},'batch-archived')}
async function report(id){return get(REPORTS,id)}
async function reportsForBatch(batchId){return (await getAll(REPORTS)).filter(r=>r.batchId===batchId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
async function snapshot(){const b=await active();return{activeBatch:b,activeBatchId:b?.id||null,counts:b?counts(b):{total:0,ready:0,incomplete:0,flagged:0,saved:0,inaccessible:0,remaining:0},batches:await all(),reports:b?await reportsForBatch(b.id):[]}}
function emit(){window.dispatchEvent(new CustomEvent('genreactrix:batch'));window.renderPortraitControlStation?.();renderConsole().catch(()=>{})}
async function renderConsole(){const snap=await snapshot();const b=snap.activeBatch;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=String(v)};set('portraitBatchName',b?.name||'No active batch');set('portraitReadyBatchCount',snap.counts.ready);set('portraitBatchTotal',snap.counts.total);set('portraitBatchRemaining',snap.counts.remaining);set('portraitSavedCurrent',snap.counts.saved);set('portraitFlaggedCurrent',snap.counts.flagged);const select=document.getElementById('batchSelect');if(select){select.innerHTML=snap.batches.map(x=>`<option value="${x.id}" ${x.id===b?.id?'selected':''}>${x.name} · ${x.status}</option>`).join('')}set('batchTotal',snap.counts.total);set('batchReady',snap.counts.ready);set('batchIncomplete',snap.counts.incomplete);set('batchFlagged',snap.counts.flagged);set('batchSaved',snap.counts.saved);set('batchInaccessible',snap.counts.inaccessible);const list=document.getElementById('batchContents');if(list)list.innerHTML=(b?.imageIds||[]).map(id=>{const r=recordEngine()?.get(id,{touch:false});return `<label class="batch-image-row"><input type="checkbox" value="${id}"><span>${r?.name||id}<small>${classified(r)?'Ready':r?.attributes?.flagged?'Flagged':'Incomplete'}</small></span></label>`}).join('')||'<p class="batch-empty">No images in this batch.</p>';const reports=document.getElementById('batchReportHistory');if(reports)reports.innerHTML=snap.reports.map(r=>`<div class="batch-report-row"><span>${new Date(r.createdAt).toLocaleString()}</span><strong>${r.counts.total} images</strong></div>`).join('')||'<p class="batch-empty">No submissions yet.</p>'}
function openConsole(){document.getElementById('batchDialog')?.showModal();renderConsole()}
async function quickSubmit(){const b=await active();if(!b)throw new Error('No active batch');const check=await validate(b.id);const summary=`${b.name}\n\nTotal: ${check.counts.total}\nReady: ${check.counts.ready}\nIncomplete: ${check.counts.incomplete}\nFlagged: ${check.counts.flagged}\nSaved: ${check.counts.saved}\nInaccessible: ${check.counts.inaccessible}\n\nSubmitting automatically generates the standard report and moves eligible temporary copies to the 30-day recycle bin.`;if(!confirm(summary))return null;return submit(b.id)}
function initUi(){document.getElementById('batchDialogClose')?.addEventListener('click',()=>document.getElementById('batchDialog')?.close());document.getElementById('batchSelect')?.addEventListener('change',e=>setActive(e.target.value));document.getElementById('batchCreate')?.addEventListener('click',async()=>{const name=prompt('Batch name','New Batch');if(name)await create({name,imageIds:[],activate:true})});document.getElementById('batchRename')?.addEventListener('click',async()=>{const b=await active();if(!b)return;const name=prompt('Batch name',b.name);if(name)await update(b.id,{name},'batch-renamed')});document.getElementById('batchAddAvailable')?.addEventListener('click',async()=>{const b=await active();const n=Math.max(1,Number(document.getElementById('batchAddCount').value)||100);const ids=(recordEngine()?.query?.({stage:'available'})||[]).filter(eligible).map(r=>r.id).filter(id=>!b.imageIds.includes(id)).slice(0,n);await addImages(b.id,ids)});document.getElementById('batchAddAll')?.addEventListener('click',async()=>{const b=await active();const ids=(recordEngine()?.query?.({stage:'available'})||[]).filter(eligible).map(r=>r.id).filter(id=>!b.imageIds.includes(id));await addImages(b.id,ids)});document.getElementById('batchRemoveSelected')?.addEventListener('click',async()=>{const b=await active();const ids=[...document.querySelectorAll('#batchContents input:checked')].map(x=>x.value);if(ids.length)await removeImages(b.id,ids)});document.getElementById('batchShuffle')?.addEventListener('click',async()=>{const b=await active();const ids=[...b.imageIds];for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}await update(b.id,{imageIds:ids},'batch-shuffled')});document.getElementById('batchValidate')?.addEventListener('click',async()=>{const b=await active();const v=await validate(b.id);document.getElementById('batchStatus').textContent=v.canSubmit?'Ready to submit':`${v.counts.incomplete} incomplete · ${v.counts.inaccessible} inaccessible`});document.getElementById('batchSubmit')?.addEventListener('click',async()=>{try{const r=await quickSubmit();if(r)document.getElementById('batchStatus').textContent=`Submitted · report ${r.report.id} · ${r.recycled} recycled`}catch(e){document.getElementById('batchStatus').textContent=e.message}});document.getElementById('batchReopen')?.addEventListener('click',async()=>{const id=document.getElementById('batchSelect').value;try{await reopen(id)}catch(e){document.getElementById('batchStatus').textContent=e.message}});document.getElementById('batchArchive')?.addEventListener('click',async()=>{const b=await active();if(b)await archive(b.id)})}
const engine={create,all,active,setActive,addImages,removeImages,update,validate,submit,reopen,archive,snapshot,openConsole,quickSubmit,reportsForBatch,activeId};window.genreactrixBatchEngine=engine;window.addEventListener('DOMContentLoaded',async()=>{await migrate();initUi();renderConsole();emit()});window.addEventListener('genreactrix:image-record',()=>renderConsole());
})();
