(()=>{
'use strict';
const DB='genreactrix-batch-engine-v1',STORE='batches',META='meta',REPORTS='reports',VERSION=3;
let activeFilter='all';
let snapshotCache={activeBatch:null,activeBatchId:null,counts:{total:0,working:0,review:0,depot:0,red:0,hotMagenta:0,keep:0,eligible:0},batches:[],reports:[],inbox:{}};
const now=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('status','status');s.createIndex('createdAt','createdAt')}if(!db.objectStoreNames.contains(META))db.createObjectStore(META,{keyPath:'key'});if(!db.objectStoreNames.contains(REPORTS)){const s=db.createObjectStore(REPORTS,{keyPath:'id'});s.createIndex('batchId','batchId');s.createIndex('createdAt','createdAt')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function withStore(name,mode,fn){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(name,mode),s=tx.objectStore(name);let result;try{result=fn(s)}catch(error){db.close();reject(error);return}tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error||new Error('Batch transaction aborted'))}})}
async function getAll(name){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),r=tx.objectStore(name).getAll();r.onsuccess=()=>{const value=r.result||[];db.close();res(value)};r.onerror=()=>{db.close();rej(r.error)}})}
async function get(name,key){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(name,'readonly'),r=tx.objectStore(name).get(key);r.onsuccess=()=>{const value=r.result||null;db.close();res(value)};r.onerror=()=>{db.close();rej(r.error)}})}
async function put(name,value){return withStore(name,'readwrite',s=>{s.put(value);return value})}
async function activeId(){return (await get(META,'active'))?.value||null}
async function setActive(id){await put(META,{key:'active',value:id||null});engine.activeIdCached=id||null;await refreshSnapshot();return id||null}
function recordEngine(){return window.genreactrixImageRecordEngine}
function imagesEngine(){return window.genreactrixImagesEngine}
function history(){return window.genreactrixHistoryEngine}
function inboxRecord(record){const lifecycle=window.genreactrixInboxLifecycle;if(lifecycle?.contains)return lifecycle.contains(record?.id);const ext=record?.metadata?.extended||{};return (Array.isArray(ext.inboxBundleIds)&&ext.inboxBundleIds.length>0)||(Array.isArray(ext.inboxPackIds)&&ext.inboxPackIds.length>0)}
function alreadyBatched(record){return ['batched','red-excluded','hot-magenta-excluded'].includes(record?.workflow?.stage)||Boolean(record?.timestamps?.batchedAt)}
function sourceAccessible(record){return Boolean(record&&!record.attributes?.failed&&(record.storage?.temporaryKey||record.storage?.referenceKey||record.storage?.hyperlink||record.source?.originalLocation||record.source?.originalUrl))}
function terminal(record){if(record?.attributes?.rejected)return'hot';if(record?.attributes?.rejectionFlagged)return'red';if(record?.attributes?.depot)return'depot';if(record?.attributes?.flagged)return'review';return'working'}
function isBatchEligible(record){return sourceAccessible(record)&&['depot','red','hot'].includes(terminal(record))}
function activeInboxRecords(){return (recordEngine()?.all?.()||[]).filter(record=>inboxRecord(record)&&!record.attributes?.inRecycleBin&&!record.attributes?.archived&&!alreadyBatched(record))}
function summaryFor(records){const count=key=>records.filter(r=>terminal(r)===key).length;return{total:records.length,working:count('working'),review:count('review'),depot:count('depot'),red:count('red'),hotMagenta:count('hot'),keep:records.filter(r=>r.attributes?.saved).length,eligible:records.filter(isBatchEligible).length,inaccessible:records.filter(r=>['depot','red','hot'].includes(terminal(r))&&!sourceAccessible(r)).length}}
function inboxWorkSnapshot(){const records=activeInboxRecords();return{...summaryFor(records),imageIds:records.map(r=>r.id),eligibleImageIds:records.filter(isBatchEligible).map(r=>r.id)}}
function pendingInboxRecords(){return activeInboxRecords().filter(isBatchEligible)}
function pendingInboxSnapshot(){const records=pendingInboxRecords();return{...summaryFor(records),imageIds:records.map(r=>r.id),keep:records.filter(r=>r.attributes?.saved).length}}
function outcomeCountsForRecords(records){const s=summaryFor(records);return{total:s.total,depot:s.depot,red:s.red,hotMagenta:s.hotMagenta,keep:s.keep,eligible:s.eligible}}
function outcomeCounts(batch){return outcomeCountsForRecords((batch?.imageIds||[]).map(id=>recordEngine()?.get(id,{touch:false})).filter(Boolean))}
async function all(){return getAll(STORE)}
async function active(){const id=await activeId();return id?get(STORE,id):null}
async function create({name=null,imageIds=[],activate=true}={}){const ids=[...new Set(imageIds)].filter(Boolean),batch={id:uid('batch'),schemaVersion:2,name:name||`Inbox Batch · ${new Date().toLocaleString()}`,status:'draft',imageIds:ids,createdAt:now(),startedAt:null,completedAt:null,submittedAt:null,submissionVersion:0,reportIds:[],evaluationVersion:localStorage.getItem('genreactrix-evaluation-vocabulary-version-v1')||'0.0.0',reevaluationRequired:false};await put(STORE,batch);for(const id of ids){const r=recordEngine()?.get(id,{touch:false});if(r)recordEngine().update(id,{batchIds:[...new Set([...(r.batchIds||[]),batch.id])],source:{firstBatchId:r.source?.firstBatchId||batch.id}},'batch-added')}if(activate)await setActive(batch.id);await history()?.append?.({imageId:null,eventType:'batch-created',actor:'system',sourceEngine:'batch',batchId:batch.id,summary:'Inbox Batch created',payload:{imageIds:ids}}).catch(()=>{});await refreshSnapshot();return batch}
async function update(id,patch,eventType='batch-updated'){const b=await get(STORE,id);if(!b)throw new Error('Batch not found');const next={...b,...patch,imageIds:patch.imageIds?[...new Set(patch.imageIds)]:b.imageIds,updatedAt:now()};await put(STORE,next);await history()?.append?.({imageId:null,eventType,actor:'director',sourceEngine:'batch',batchId:id,summary:eventType.replaceAll('-',' '),payload:{before:b,current:next}}).catch(()=>{});await refreshSnapshot();return next}
async function addImages(id,imageIds){const b=await get(STORE,id);if(!b)throw new Error('Batch not found');const ids=[...new Set([...(b.imageIds||[]),...(imageIds||[])])];for(const imageId of ids){const r=recordEngine()?.get(imageId,{touch:false});if(r&&!r.batchIds?.includes(id))recordEngine().update(imageId,{batchIds:[...new Set([...(r.batchIds||[]),id])],source:{firstBatchId:r.source?.firstBatchId||id}},'batch-added')}return update(id,{imageIds:ids},'batch-images-loaded')}
async function removeImages(id,imageIds){const b=await get(STORE,id);if(!b)return null;const remove=new Set(imageIds||[]);return update(id,{imageIds:(b.imageIds||[]).filter(x=>!remove.has(x))},'batch-images-removed')}
async function moveImages(fromId,toId,imageIds){await addImages(toId,imageIds);return removeImages(fromId,imageIds)}
async function reorderSelected(id,imageIds,direction){const b=await get(STORE,id);if(!b)return null;const selected=new Set(imageIds||[]),list=[...(b.imageIds||[])];if(direction<0){for(let i=1;i<list.length;i++)if(selected.has(list[i])&&!selected.has(list[i-1]))[list[i-1],list[i]]=[list[i],list[i-1]]}else{for(let i=list.length-2;i>=0;i--)if(selected.has(list[i])&&!selected.has(list[i+1]))[list[i],list[i+1]]=[list[i+1],list[i]]}return update(id,{imageIds:list},'batch-reordered')}
async function stageEligibleInbox(){const records=pendingInboxRecords(),ids=records.map(r=>r.id);if(!ids.length)throw new Error('No Depot, Delete, or Reject images are waiting for Batch.');const current=await active();if(current&&current.status==='draft')await update(current.id,{imageIds:ids,startedAt:current.startedAt||now()},'batch-inbox-reloaded');else await create({imageIds:ids,activate:true});const batch=await active();for(const id of ids){const r=recordEngine()?.get(id,{touch:false});if(r&&!r.batchIds?.includes(batch.id))recordEngine().update(id,{batchIds:[...new Set([...(r.batchIds||[]),batch.id])],source:{firstBatchId:r.source?.firstBatchId||batch.id}},'batch-added')}await refreshSnapshot();return{batch,outcomes:outcomeCountsForRecords(records)}}
async function validate(id,imageIds=null){const b=await get(STORE,id);if(!b)throw new Error('Batch not found');const ids=Array.isArray(imageIds)?imageIds:b.imageIds||[],records=ids.map(imageId=>recordEngine()?.get(imageId,{touch:false})).filter(Boolean),issues=[];for(const r of records){const t=terminal(r);if(!['depot','red','hot'].includes(t))issues.push({imageId:r.id,type:'not-batch-eligible',terminal:t});else if(!sourceAccessible(r))issues.push({imageId:r.id,type:'source-unavailable',terminal:t})}return{canSubmit:records.length>0&&issues.length===0,counts:summaryFor(records),issues,imageIds:records.map(r=>r.id)}}
async function reportsForBatch(batchId){return (await getAll(REPORTS)).filter(r=>r.batchId===batchId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
async function submit(id,imageIds=null){let b=await get(STORE,id);if(!b)throw new Error('Batch not found');const ids=Array.isArray(imageIds)&&imageIds.length?[...new Set(imageIds)]:[...(b.imageIds||[])];const check=await validate(id,ids);if(!check.canSubmit)throw new Error(check.issues.length?'Batch contains an image that is no longer eligible.':'No eligible images selected.');b=await update(id,{status:'submitting',imageIds:ids,startedAt:b.startedAt||now()},'batch-submitting');const processed=[];for(const imageId of ids){let record=recordEngine()?.get(imageId,{touch:false});if(!record)continue;const t=terminal(record),submittedAt=now();if(record.attributes?.saved)record=await imagesEngine()?.commitKeptAsset?.(imageId)||record;if(t==='red')await imagesEngine()?.writeExclusionRecord?.(imageId,'red');if(t==='hot')await imagesEngine()?.writeExclusionRecord?.(imageId,'hot-magenta');const stage=t==='red'?'red-excluded':t==='hot'?'hot-magenta-excluded':'batched';record=recordEngine().update(imageId,{workflow:{stage},timestamps:{batchedAt:submittedAt},metadata:{extended:{lastBatchSubmissionId:b.id,lastBatchTerminal:t}}},'batch-committed');let recycled=false;if(!record.attributes?.saved&&record.storage?.mode==='temporary'){await imagesEngine()?.moveToRecycle?.(imageId);recycled=true}processed.push({imageId,terminal:t,keep:Boolean(record.attributes?.saved),recycled})}
  const submittedAt=now();await window.genreactrixInboxLifecycle?.finalizeBatchImages?.(ids,{batchId:b.id,submittedAt});const counts=outcomeCountsForRecords(ids.map(imageId=>recordEngine()?.get(imageId,{touch:false})).filter(Boolean));const report={id:uid('batch-record'),batchId:b.id,createdAt:submittedAt,submissionVersion:(b.submissionVersion||0)+1,imageIds:ids,counts,items:processed};await put(REPORTS,report);b=await update(b.id,{status:'submitted',submittedAt,completedAt:submittedAt,submissionVersion:report.submissionVersion,reportIds:[...(b.reportIds||[]),report.id]},'batch-submitted');await setActive(null);await refreshSnapshot();return{batch:b,report,recycled:processed.filter(x=>x.recycled).length}}
async function reopen(){throw new Error('A submitted Batch is historical. Pull an image from Origin for re-evaluation instead.')}
async function archive(id){return update(id,{status:'archived',archivedAt:now()},'batch-archived')}
async function migrate(){const batches=await all(),current=await activeId();if(current&&!batches.some(b=>b.id===current&&b.status==='draft'))await setActive(null);else engine.activeIdCached=current||null;return batches}
async function snapshot(){const [b,batches,reports]=await Promise.all([active(),all(),getAll(REPORTS)]),inbox=inboxWorkSnapshot(),batchRecords=(b?.imageIds||[]).map(id=>recordEngine()?.get(id,{touch:false})).filter(Boolean);snapshotCache={activeBatch:b,activeBatchId:b?.id||null,counts:summaryFor(batchRecords),batches,reports:reports.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),inbox,pending:pendingInboxSnapshot()};engine.snapshotCached=snapshotCache;engine.activeIdCached=b?.id||null;return structuredClone(snapshotCache)}
async function refreshSnapshot(){try{await snapshot();renderConsole();window.dispatchEvent(new CustomEvent('genreactrix:batch-snapshot',{detail:{snapshot:structuredClone(snapshotCache)}}))}catch(error){console.warn(error)}}
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=String(value)}
function filterRecord(record){const t=terminal(record);return activeFilter==='all'||activeFilter===t||(activeFilter==='keep'&&record.attributes?.saved)}
async function renderConsole(){const snap=await snapshot().catch(()=>snapshotCache),inbox=snap.inbox||inboxWorkSnapshot();setText('batchTotal',inbox.total||0);setText('batchWorking',inbox.working||0);setText('batchYellow',inbox.review||0);setText('batchDepot',inbox.depot||0);setText('batchRed',inbox.red||0);setText('batchHotMagenta',inbox.hotMagenta||0);setText('batchKeep',inbox.keep||0);setText('batchEligibleDepot',inbox.depot||0);setText('batchEligibleRed',inbox.red||0);setText('batchEligibleHotMagenta',inbox.hotMagenta||0);setText('batchEligibleKeep',pendingInboxRecords().filter(r=>r.attributes?.saved).length);const b=snap.activeBatch,rows=(b?.imageIds||[]).map(id=>recordEngine()?.get(id,{touch:false})).filter(Boolean).filter(filterRecord);setText('batchVisibleCount',`${rows.length} visible`);document.querySelectorAll('[data-batch-filter]').forEach(btn=>btn.classList.toggle('active',btn.dataset.batchFilter===activeFilter));const list=document.getElementById('batchContents');if(list)list.innerHTML=rows.map((r,index)=>{const t=terminal(r),labels={working:'Working',review:'Review',depot:'Depot',red:'Delete',hot:'Reject'};return `<label class="batch-image-row" data-state="${t}"><input type="checkbox" value="${r.id}" checked><span class="batch-order">${index+1}</span><span><strong>${r.name||r.source?.originalFilename||r.id}</strong><small class="batch-tags"><span class="batch-tag">${labels[t]}</span>${r.attributes?.saved?'<span class="batch-tag">Keep</span>':''}</small></span></label>`}).join('')||'<p class="batch-empty">Load eligible Inbox images to prepare this Batch.</p>';const historyBox=document.getElementById('batchReportHistory');if(historyBox)historyBox.innerHTML=(snap.reports||[]).map(r=>`<button class="batch-report-row" type="button"><span>${new Date(r.createdAt).toLocaleString()}</span><strong>${r.imageIds?.length||0} images</strong></button>`).join('')||'<p class="batch-empty">No Batch history yet.</p>'}
function selectedIds(){return[...document.querySelectorAll('#batchContents input:checked')].map(x=>x.value)}
function openConsole(){document.getElementById('batchDialog')?.showModal();renderConsole()}
function showFilter(filter){activeFilter=filter;renderConsole()}
async function showSubmissionVerification(){let b=await active();if(!b){await stageEligibleInbox();b=await active()}const selected=selectedIds();const ids=selected.length?selected:b.imageIds||[];const check=await validate(b.id,ids),rows=ids.map(id=>recordEngine()?.get(id,{touch:false})).filter(Boolean),out=outcomeCountsForRecords(rows),box=document.getElementById('batchVerifySummary');if(box)box.innerHTML=`<div class="batch-verify-summary"><span>Selected</span><strong>${out.total}</strong><span>Depot</span><strong>${out.depot}</strong><span>Delete</span><strong>${out.red}</strong><span>Reject</span><strong>${out.hotMagenta}</strong><span>Keep full-resolution</span><strong>${out.keep}</strong></div>${check.canSubmit?'':'<p class="batch-verify-warning">One or more selected images are no longer eligible for Batch.</p>'}`;const confirm=document.getElementById('batchVerifyConfirm');if(confirm){confirm.disabled=!check.canSubmit;confirm.dataset.imageIds=ids.join(',')}document.getElementById('batchVerifyDialog')?.showModal();return{...check,outcomes:out}}
async function quickSubmit(){const staged=await stageEligibleInbox();openConsole();return staged}
function initUi(){const byId=id=>document.getElementById(id);byId('batchDialogClose')?.addEventListener('click',()=>byId('batchDialog')?.close());byId('batchStageInbox')?.addEventListener('click',async()=>{try{const staged=await stageEligibleInbox();byId('batchStatus').textContent=`Loaded ${staged.outcomes.total} eligible Inbox image${staged.outcomes.total===1?'':'s'}.`;await renderConsole()}catch(error){byId('batchStatus').textContent=error.message}});byId('batchValidate')?.addEventListener('click',async()=>{try{let b=await active();if(!b){await stageEligibleInbox();b=await active()}const ids=selectedIds();const v=await validate(b.id,ids.length?ids:null);byId('batchStatus').textContent=v.canSubmit?`${v.counts.total} selected image${v.counts.total===1?'':'s'} can Batch.`:`${v.issues.length} issue${v.issues.length===1?'':'s'} must be resolved.`}catch(error){byId('batchStatus').textContent=error.message}});byId('batchSubmit')?.addEventListener('click',async()=>{try{await showSubmissionVerification()}catch(error){byId('batchStatus').textContent=error.message}});byId('batchVerifyCancel')?.addEventListener('click',()=>byId('batchVerifyDialog')?.close());byId('batchVerifyReview')?.addEventListener('click',()=>{byId('batchVerifyDialog')?.close();byId('batchDialog')?.showModal()});byId('batchVerifyConfirm')?.addEventListener('click',async event=>{const b=await active();if(!b)return;const ids=String(event.currentTarget.dataset.imageIds||'').split(',').filter(Boolean);try{const result=await submit(b.id,ids);byId('batchVerifyDialog')?.close();byId('batchStatus').textContent=`Batched ${result.report.imageIds.length} image${result.report.imageIds.length===1?'':'s'}.`;await renderConsole()}catch(error){byId('batchVerifyDialog')?.close();byId('batchStatus').textContent=error.message}});byId('batchSelectAll')?.addEventListener('change',e=>document.querySelectorAll('#batchContents input[type=checkbox]').forEach(x=>x.checked=e.target.checked));document.querySelectorAll('[data-batch-filter]').forEach(btn=>btn.addEventListener('click',()=>showFilter(btn.dataset.batchFilter)))}
async function verify(){const issues=[],batches=await all(),recordIds=new Set(recordEngine()?.all?.().map(r=>r.id)||[]);for(const b of batches){for(const id of b.imageIds||[])if(!recordIds.has(id))issues.push({type:'batch-missing-image',batchId:b.id,imageId:id,severity:'attention'});if(b.status==='submitted'&&!(b.reportIds||[]).length)issues.push({type:'submitted-batch-missing-record',batchId:b.id,severity:'critical'})}return{batchCount:batches.length,issueCount:issues.length,issues}}
const engine={create,all,active,setActive,addImages,removeImages,moveImages,reorderSelected,update,validate,submit,reopen,archive,snapshot,openConsole,quickSubmit,stageEligibleInbox,stageResolvedInbox:stageEligibleInbox,pendingInboxSnapshot,inboxWorkSnapshot,outcomeCounts,reportsForBatch,verify,activeId,activeIdCached:null,snapshotCached:snapshotCache};window.genreactrixBatchEngine=engine;
window.addEventListener('DOMContentLoaded',async()=>{await migrate();initUi();await refreshSnapshot()});
window.addEventListener('genreactrix:image-record',()=>refreshSnapshot());
})();
