(function(){
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
  let selected=new Set(),activeSection="add",selectedSingleFile=null,loadedUrlSourceName="";
  function engine(){return window.genreactrixImagesEngine}
  function all(){try{return engine()?.allRecords?.()||[]}catch{return[]}}
  function status(text){if($("imagesConsoleStatus"))$("imagesConsoleStatus").textContent=text||""}
  function terminalLabel(r){if(r.attributes?.rejected)return"Reject";if(r.attributes?.rejectionFlagged)return"Delete";if(r.attributes?.depot)return"Depot";if(r.attributes?.flagged)return"Review";return"Working"}
  function listFor(section){const records=all();if(section==="saved")return records.filter(r=>r.attributes?.saved);if(section==="flagged")return records.filter(r=>r.attributes?.flagged||r.attributes?.rejectionFlagged||r.attributes?.rejected);if(section==="recycle")return records.filter(r=>r.attributes?.inRecycleBin);if(section==="failures")return records.filter(r=>r.error||r.attributes?.failed);if(section==="history")return records.slice().sort((a,b)=>String(b.createdAt||"").localeCompare(String(a.createdAt||"")));return[]}
  function renderList(section){const id={saved:"imagesSavedList",flagged:"imagesFlaggedList",recycle:"imagesRecycleList",failures:"imagesFailuresList",history:"imagesHistoryList"}[section];if(!id||!$(id))return;const records=listFor(section);$(id).innerHTML=records.length?records.map(r=>{const source=r.source?.originalFilename||r.source?.originalUrl||r.name||r.id,state=[r.workflow?.stage,terminalLabel(r),r.attributes?.saved?"Keep":"",r.attributes?.inRecycleBin?"Recycle":"",r.error?"Failed":""].filter(Boolean).join(" · ");return `<article class="images-record-row"><label class="images-record-select"><input type="checkbox" data-image-select="${esc(r.id)}" ${selected.has(r.id)?"checked":""}><span><strong>${esc(source)}</strong><small>${esc(r.id)} · ${esc(state)}</small></span></label><div class="images-console-actions"><button data-image-inspect="${esc(r.id)}" type="button">Inspect</button></div></article>`}).join(""):`<p class="images-empty">No ${esc(section)} images.</p>`;$(id).querySelectorAll("[data-image-select]").forEach(box=>box.addEventListener("change",()=>{box.checked?selected.add(box.dataset.imageSelect):selected.delete(box.dataset.imageSelect)}));$(id).querySelectorAll("[data-image-inspect]").forEach(button=>button.addEventListener("click",()=>window.genreactrixInvestigationUI?.openImage?.(button.dataset.imageInspect,{title:`${section[0].toUpperCase()+section.slice(1)} Image`}).catch(error=>status(`Inspect failed: ${error.message||error}`))))}
  function originCaseLabel(c){return c.type==='dupe'?'Dupe':c.type==='repeat'?'Repeat':c.type==='import-failure'?'Import Failure':c.type==='source-retry'?'Retry Import Source':'Origin case'}
  function originCaseActions(c){const inspect=`<button data-origin-inspect="${esc(c.id)}" type="button">${c.type==='dupe'||c.type==='repeat'?'Compare':'Inspect'}</button>`;if(c.type==='dupe'&&c.status==='pending-review')return `${inspect}<button data-origin-action="sustain" data-origin-id="${esc(c.id)}" type="button">Sustain</button><button data-origin-action="overrule" data-origin-id="${esc(c.id)}" type="button">Overrule</button>`;if(c.type==='repeat'&&c.status==='blocked-repeat')return `${inspect}<button data-origin-action="reevaluate" data-origin-id="${esc(c.id)}" type="button">Re-evaluate</button>`;if(c.type==='import-failure'&&c.status==='blocked')return `${inspect}<button data-origin-action="retry" data-origin-id="${esc(c.id)}" type="button">Retry</button>`;if(c.type==='source-retry'&&c.status==='retry-pending')return `${inspect}<button data-origin-action="retry" data-origin-id="${esc(c.id)}" type="button">Retry</button>`;return inspect}
  async function renderGates(){const target=$("imagesReviewList"),gateEngine=window.genreactrixOriginGateEngine;if(!target)return;if(!gateEngine){target.innerHTML='<p class="images-empty">Origin Gate Engine unavailable.</p>';return}const cases=await gateEngine.all(),records=new Map(all().map(r=>[String(r.id),r]));target.innerHTML=cases.length?cases.map(c=>{const original=records.get(String(c.matchedImageId||'')),source=c.source?.originalFilename||c.source?.originalUrl||c.candidate?.name||c.id,matched=original?(original.source?.originalFilename||original.source?.originalUrl||original.name||original.id):'',evidence=c.evidence?.kind?` · ${c.evidence.kind}`:'',err=c.error?` · ${c.error}`:'';return `<article class="images-record-row" data-origin-case="${esc(c.id)}"><span><strong>${esc(originCaseLabel(c))} · ${esc(source)}</strong><small>${esc(c.status)}${matched?` · Original: ${esc(matched)}`:''}${esc(evidence)}${esc(err)}</small></span><div class="images-console-actions">${originCaseActions(c)}</div></article>`}).join(''):'<p class="images-empty">No Origin gate cases.</p>';target.querySelectorAll('[data-origin-inspect]').forEach(button=>button.addEventListener('click',()=>window.genreactrixInvestigationUI?.openOriginCase?.(button.dataset.originInspect).catch(error=>status(`Inspect failed: ${error.message||error}`))))}
  async function actOnGate(action,id){const gates=window.genreactrixOriginGateEngine;if(!gates)return;status(`${action==='sustain'?'Sustaining Dupe':action==='overrule'?'Overruling Dupe':action==='reevaluate'?'Starting Re-evaluation':'Retrying Origin case'}…`);try{if(action==='sustain')await gates.sustainDupe(id);else if(action==='overrule')await gates.overruleDupe(id);else if(action==='reevaluate')await gates.reevaluateRepeat(id);else if(action==='retry')await gates.retry(id);status(action==='sustain'?'Dupe sustained.':action==='overrule'?'Dupe overruled and admitted to Queue.':action==='reevaluate'?'Repeat authorized for Re-evaluation and returned to Queue.':'Origin retry completed.');await renderGates();window.dispatchEvent(new CustomEvent('genreactrix:image-record'))}catch(error){status(`Origin action failed: ${error.message||error}`)}}
  async function renderDashboard(){const d=await window.genreactrixImportEngine?.dashboard?.();if(!d)return;$("importActiveCount").textContent=d.active.length;$("importFailedCount").textContent=d.origin?.importFailures??d.failed.length;$("importPendingAiCount").textContent=d.pendingAi;$("importAiOutputCount").textContent=d.aiOutput;$("importRecentJobs").innerHTML=d.recent.map(j=>`<article class="images-record-row"><span><strong>${esc(j.sourceLabel||j.sourceType)}</strong><small>${esc(j.status)} · ${j.imported||0} imported · ${j.metadata?.originGateCount||0} Origin gates · ${j.failed||0} failed · ${new Date(j.createdAt).toLocaleString()}</small></span></article>`).join("")||"<p class=\"images-empty\">No import jobs.</p>"}
  function switchSection(section){activeSection=section;document.querySelectorAll("[data-images-panel]").forEach(p=>p.hidden=p.dataset.imagesPanel!==section);document.querySelectorAll("[data-images-section]").forEach(b=>b.classList.toggle("active",b.dataset.imagesSection===section));if(section==="dashboard"){renderDashboard();return}if(section==="review"){renderGates();return}if(section!=="add")renderList(section)}
  async function preview(){const qty=Math.max(1,Number($("imagesConsoleQuantity")?.value)||100),rows=await engine()?.prefetchUrls?.($("imagesConsoleUrls")?.value||"",{limit:qty})||[];$("imagesConsoleSummary").textContent=rows.length?`${rows.length} eligible source${rows.length===1?"":"s"} found.`:"No eligible URLs found."}
  function decodeEntities(text){const t=document.createElement('textarea');t.innerHTML=String(text||'');return t.value}
  function normalizeEmbeddedUrlText(text){return decodeEntities(String(text||'')).replace(/\\\//g,'/').replace(/\\u002[fF]/g,'/').replace(/&amp;/gi,'&')}
  function trimExtractedUrl(raw){let url=String(raw||'').replace(/[\u0000-\u001f]+/g,'').trim();url=url.replace(/[.,;:!?]+$/g,'');for(const [open,close] of [['(',')'],['[',']'],['{','}']]){while(url.endsWith(close)&&((url.match(new RegExp('\\'+close,'g'))||[]).length>(url.match(new RegExp('\\'+open,'g'))||[]).length))url=url.slice(0,-1)}return url}
  function urlsFromText(text){const matches=normalizeEmbeddedUrlText(text).match(/https?:\/\/[^\s<>"'`]+/gi)||[];return matches.map(trimExtractedUrl).filter(url=>{try{const parsed=new URL(url);return ['http:','https:'].includes(parsed.protocol)}catch{return false}})}
  function delimitedCells(text,delimiter=','){const cells=[];let cell='',quoted=false;const input=String(text||'');for(let i=0;i<input.length;i++){const ch=input[i];if(ch==='"'){if(quoted&&input[i+1]==='"'){cell+='"';i++}else quoted=!quoted;continue}if(!quoted&&(ch===delimiter||ch==='\n'||ch==='\r')){cells.push(cell);cell='';if(ch==='\r'&&input[i+1]==='\n')i++;continue}cell+=ch}cells.push(cell);return cells}
  function urlsFromDelimitedText(text,delimiter){return delimitedCells(text,delimiter).flatMap(urlsFromText)}
  function uniqueUrls(urls){const out=[],seen=new Set();for(const raw of urls||[]){let href='';try{href=new URL(String(raw)).href}catch{}if(!href||seen.has(href))continue;seen.add(href);out.push(href)}return out}
  async function unzipTextEntriesFromBytes(bytes){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(view.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)return[];const total=view.getUint16(eocd+10,true),central=view.getUint32(eocd+16,true),decoder=new TextDecoder(),texts=[];let pos=central;for(let n=0;n<total&&pos+46<=bytes.length;n++){if(view.getUint32(pos,true)!==0x02014b50)break;const method=view.getUint16(pos+10,true),compressedSize=view.getUint32(pos+20,true),nameLen=view.getUint16(pos+28,true),extraLen=view.getUint16(pos+30,true),commentLen=view.getUint16(pos+32,true),localOffset=view.getUint32(pos+42,true),name=decoder.decode(bytes.slice(pos+46,pos+46+nameLen));pos+=46+nameLen+extraLen+commentLen;if(!/\.(?:xml|rels|txt|csv|tsv|json|html?|md|rtf|url)$/i.test(name))continue;if(localOffset+30>bytes.length||view.getUint32(localOffset,true)!==0x04034b50)continue;const localNameLen=view.getUint16(localOffset+26,true),localExtraLen=view.getUint16(localOffset+28,true),dataStart=localOffset+30+localNameLen+localExtraLen,compressed=bytes.slice(dataStart,dataStart+compressedSize);let raw;if(method===0)raw=compressed;else if(method===8&&typeof DecompressionStream==='function'){try{const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('deflate-raw'));raw=new Uint8Array(await new Response(stream).arrayBuffer())}catch{continue}}else continue;texts.push(decoder.decode(raw))}return texts}
  function rawTextViews(bytes){const views=[];for(const encoding of ['utf-8','windows-1252','utf-16le','utf-16be']){try{views.push(new TextDecoder(encoding,{fatal:false}).decode(bytes))}catch{}}return views}
  async function urlsFromFile(file){const bytes=new Uint8Array(await file.arrayBuffer()),rawViews=rawTextViews(bytes),zipTexts=await unzipTextEntriesFromBytes(bytes).catch(()=>[]),name=String(file?.name||'').toLowerCase();let found=[];if(name.endsWith('.csv'))found.push(...urlsFromDelimitedText(rawViews[0]||'',','));else if(name.endsWith('.tsv'))found.push(...urlsFromDelimitedText(rawViews[0]||'','\t'));else found.push(...rawViews.flatMap(urlsFromText));found.push(...zipTexts.flatMap(urlsFromText));const urls=uniqueUrls(found);return{urls,zipEntries:zipTexts.length}}
  async function loadUrlFile(file){if(!file)return;loadedUrlSourceName='';status(`Scanning ${file.name} for URLs…`);try{const result=await urlsFromFile(file),urls=result.urls;if(!urls.length)throw new Error('No HTTP/HTTPS URLs were found in that file.');loadedUrlSourceName=file.name;$('imagesConsoleUrls').value=urls.join('\n');if($('imagesConsoleQuantity'))$('imagesConsoleQuantity').value=String(urls.length);$('imagesConsoleSummary').textContent=`Loaded ${urls.length} unique URL${urls.length===1?'':'s'} from ${file.name}.`;status('URL source loaded. Press Import to retrieve the images through the normal Origin path.')}catch(error){status(`Could not scan URL source: ${error.message||error}`)}}
  async function doImport(){const button=$("imagesConsoleImport");const qty=Math.max(1,Number($("imagesConsoleQuantity")?.value)||100),mode=$("imagesConsoleMode")?.value||"link";if(mode==="prefetch"){await preview();return}const text=$("imagesConsoleUrls")?.value||"";button.disabled=true;try{const result=await window.genreactrixImportEngine?.runUrls?.(text,{limit:qty,mode:mode==="download"?"temporary":"link",prefetch:Boolean($("imagesConsolePrefetch")?.checked),target:"queue",sourceLabel:loadedUrlSourceName||"URL list"}),records=result?.records||[],gates=result?.gates||[];status(`${records.length} image${records.length===1?"":"s"} imported${gates.length?` · ${gates.length} Origin gate${gates.length===1?'':'s'}`:''}.`);$("imagesConsoleSummary").textContent=`Imported ${records.length}${gates.length?` · Origin gates ${gates.length}`:''}.`;if(gates.length)switchSection("review");window.dispatchEvent(new CustomEvent("genreactrix:image-record"))}catch(error){status(`Import failed: ${error.message||error}`)}finally{button.disabled=false}}
  const IMAGE_FILE_RE=/\.(?:jpe?g|png|gif|webp|bmp|avif|heic|heif)$/i;
  function isImageFile(file){return String(file?.type||"").toLowerCase().startsWith("image/")||IMAGE_FILE_RE.test(String(file?.name||""))}
  async function importSingleFile(file){if(!file)return;if(!isImageFile(file)){status("Choose an image file.");return}status(`Importing ${file.name}…`);try{const result=await window.genreactrixImportEngine?.runFiles?.([file],{limit:1,sourceLabel:file.name,target:"queue"}),records=result?.records||[],gates=result?.gates||[];$("imagesConsoleSummary").textContent=records.length?`Imported ${file.name}.`:`${file.name} stopped at Origin.`;status(records.length?`${file.name} imported.`:`${originCaseLabel(gates[0]||{})}: ${file.name} did not enter Queue.`);if(gates.length)switchSection("review");window.dispatchEvent(new CustomEvent("genreactrix:image-record"));return result}catch(error){status(`Import failed: ${error.message||error}`);throw error}}
  async function restoreSelected(){const ids=[...selected];if(!ids.length){status("Select recycle items first.");return}let restored=0;for(const id of ids){try{await engine()?.restoreFromRecycle?.(id);restored++}catch{}}selected.clear();status(`${restored} restored.`);renderList("recycle");window.dispatchEvent(new CustomEvent("genreactrix:image-record"))}
  async function emptyRecycle(){const records=listFor("recycle");if(!records.length){status("Recycle bin is empty.");return}if(!confirm(`Permanently purge ${records.length} eligible recycle item${records.length===1?"":"s"}? Image Records and 64×64 thumbnails remain.`))return;const result=await engine()?.purgeRecycle?.({all:true});status(`${result?.purged||0} recycle item${result?.purged===1?"":"s"} purged.`);renderList("recycle");window.dispatchEvent(new CustomEvent("genreactrix:image-record"))}
  function open(section='add'){const amount=window.genreactrixSettingsEngine?.getCached?.("defaults.images")||window.genreactrixSettingsEngine?.getCached?.("defaults.urls")||100;if($("imagesConsoleQuantity"))$("imagesConsoleQuantity").value=String(amount);switchSection(section);$("imagesConsoleDialog")?.showModal()}
  function init(){$("imagesConsoleClose")?.addEventListener("click",()=>$("imagesConsoleDialog")?.close());document.querySelectorAll("[data-images-section]").forEach(b=>b.addEventListener("click",()=>switchSection(b.dataset.imagesSection)));$("imagesConsolePreview")?.addEventListener("click",()=>preview().catch(e=>status(String(e.message||e))));$("imagesConsoleImport")?.addEventListener("click",()=>doImport());$("imagesConsoleFolder")?.addEventListener("click",()=>{const limit=Math.max(1,Number($("imagesConsoleQuantity")?.value)||100);$("imagesConsoleDialog")?.close();if(window.genreactrixChooseImageFiles)window.genreactrixChooseImageFiles({limit});else $("folderInput")?.click()});$("imagesConsoleUrlFileBtn")?.addEventListener("click",()=>$("imagesConsoleUrlFile")?.click());$("imagesConsoleUrlFile")?.addEventListener("change",e=>{const file=e.target.files?.[0];loadUrlFile(file).finally(()=>{e.target.value=''})});$("imagesRestoreSelected")?.addEventListener("click",restoreSelected);$("imagesEmptyRecycle")?.addEventListener("click",emptyRecycle);$("imagesReviewList")?.addEventListener("click",e=>{const b=e.target.closest('[data-origin-action]');if(b)actOnGate(b.dataset.originAction,b.dataset.originId)});window.genreactrixNotificationsEngine?.registerAction?.('origin-gates',()=>open('review'))}
  window.genreactrixImagesConsole={open,openGates:()=>open('review'),render:()=>switchSection(activeSection)};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
