(function(){
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
  let selected=new Set(),activeSection="add";
  function engine(){return window.genreactrixImagesEngine}
  function all(){try{return engine()?.allRecords?.()||[]}catch{return[]}}
  function status(text){if($("imagesConsoleStatus"))$("imagesConsoleStatus").textContent=text||""}
  function terminalLabel(r){if(r.attributes?.rejected)return"Reject";if(r.attributes?.rejectionFlagged)return"Delete";if(r.attributes?.depot)return"Depot";if(r.attributes?.flagged)return"Review";return"Working"}
  function listFor(section){const records=all();if(section==="review")return records.filter(r=>!["archived","batched","red-excluded","hot-magenta-excluded"].includes(r.workflow?.stage)&&!r.attributes?.inRecycleBin);if(section==="saved")return records.filter(r=>r.attributes?.saved);if(section==="flagged")return records.filter(r=>r.attributes?.flagged||r.attributes?.rejectionFlagged||r.attributes?.rejected);if(section==="recycle")return records.filter(r=>r.attributes?.inRecycleBin);if(section==="failures")return records.filter(r=>r.error||r.attributes?.failed);if(section==="history")return records.slice().sort((a,b)=>String(b.createdAt||"").localeCompare(String(a.createdAt||"")));return[]}
  function renderList(section){const id={review:"imagesReviewList",saved:"imagesSavedList",flagged:"imagesFlaggedList",recycle:"imagesRecycleList",failures:"imagesFailuresList",history:"imagesHistoryList"}[section];if(!id||!$(id))return;const records=listFor(section);$(id).innerHTML=records.length?records.map(r=>{const source=r.source?.originalFilename||r.source?.originalUrl||r.name||r.id,state=[r.workflow?.stage,terminalLabel(r),r.attributes?.saved?"Keep":"",r.attributes?.inRecycleBin?"Recycle":"",r.error?"Failed":""].filter(Boolean).join(" · ");return `<label class="images-record-row"><input type="checkbox" data-image-select="${esc(r.id)}" ${selected.has(r.id)?"checked":""}><span><strong>${esc(source)}</strong><small>${esc(r.id)} · ${esc(state)}</small></span></label>`}).join(""):`<p class="images-empty">No ${esc(section)} images.</p>`;$(id).querySelectorAll("[data-image-select]").forEach(box=>box.addEventListener("change",()=>{box.checked?selected.add(box.dataset.imageSelect):selected.delete(box.dataset.imageSelect)}))}
  async function renderDashboard(){const d=await window.genreactrixImportEngine?.dashboard?.();if(!d)return;$("importActiveCount").textContent=d.active.length;$("importFailedCount").textContent=d.failed.length;$("importPendingAiCount").textContent=d.pendingAi;$("importAiOutputCount").textContent=d.aiOutput;$("importRecentJobs").innerHTML=d.recent.map(j=>`<article class="images-record-row"><span><strong>${esc(j.sourceLabel||j.sourceType)}</strong><small>${esc(j.status)} · ${j.imported||0} imported · ${j.failed||0} failed · ${new Date(j.createdAt).toLocaleString()}</small></span></article>`).join("")||"<p class=\"images-empty\">No import jobs.</p>"}
  function switchSection(section){activeSection=section;document.querySelectorAll("[data-images-panel]").forEach(p=>p.hidden=p.dataset.imagesPanel!==section);document.querySelectorAll("[data-images-section]").forEach(b=>b.classList.toggle("active",b.dataset.imagesSection===section));if(section==="dashboard"){renderDashboard();return}if(section!=="add")renderList(section)}
  async function preview(){const qty=Math.max(1,Number($("imagesConsoleQuantity")?.value)||100),rows=await engine()?.prefetchUrls?.($("imagesConsoleUrls")?.value||"",{limit:qty})||[];$("imagesConsoleSummary").textContent=rows.length?`${rows.length} eligible source${rows.length===1?"":"s"} found.`:"No eligible URLs found."}
  function decodeEntities(text){const t=document.createElement('textarea');t.innerHTML=text;return t.value}
  function urlsFromText(text){const matches=decodeEntities(String(text||'')).match(/https?:\/\/[^\s"'<>\]\[(){}]+/gi)||[];return [...new Set(matches.map(url=>url.replace(/[.,;:!?]+$/,'')).filter(url=>{try{new URL(url);return true}catch{return false}}))]}
  async function unzipTextEntries(file){const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(view.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error('Document/spreadsheet ZIP directory was not found');const total=view.getUint16(eocd+10,true),central=view.getUint32(eocd+16,true),decoder=new TextDecoder(),texts=[];let pos=central;for(let n=0;n<total&&pos+46<=bytes.length;n++){if(view.getUint32(pos,true)!==0x02014b50)break;const method=view.getUint16(pos+10,true),compressedSize=view.getUint32(pos+20,true),nameLen=view.getUint16(pos+28,true),extraLen=view.getUint16(pos+30,true),commentLen=view.getUint16(pos+32,true),localOffset=view.getUint32(pos+42,true),name=decoder.decode(bytes.slice(pos+46,pos+46+nameLen));pos+=46+nameLen+extraLen+commentLen;if(!/\.(xml|rels|txt|csv|tsv|json|html?|md)$/i.test(name))continue;if(localOffset+30>bytes.length||view.getUint32(localOffset,true)!==0x04034b50)continue;const localNameLen=view.getUint16(localOffset+26,true),localExtraLen=view.getUint16(localOffset+28,true),dataStart=localOffset+30+localNameLen+localExtraLen,compressed=bytes.slice(dataStart,dataStart+compressedSize);let raw;if(method===0)raw=compressed;else if(method===8&&typeof DecompressionStream==='function'){const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('deflate-raw'));raw=new Uint8Array(await new Response(stream).arrayBuffer())}else continue;texts.push(decoder.decode(raw))}return texts}
  async function urlsFromFile(file){const ext=(file.name.split('.').pop()||'').toLowerCase();let texts=[];if(['docx','xlsx','ods'].includes(ext))texts=await unzipTextEntries(file);else texts=[await file.text()];return [...new Set(texts.flatMap(urlsFromText))]}
  async function loadUrlFile(file){if(!file)return;status(`Reading ${file.name}…`);try{const urls=await urlsFromFile(file);if(!urls.length)throw new Error('No URLs were found in that file.');$("imagesConsoleUrls").value=urls.join('\n');$("imagesConsoleSummary").textContent=`Loaded ${urls.length} unique URL${urls.length===1?'':'s'} from ${file.name}.`;status('URL list loaded. Review it, then choose Prefetch only or Import.')}catch(error){status(`Could not read URL file: ${error.message||error}`)}}
  async function doImport(){const qty=Math.max(1,Number($("imagesConsoleQuantity")?.value)||100),mode=$("imagesConsoleMode")?.value||"link";if(mode==="prefetch"){await preview();return}const text=$("imagesConsoleUrls")?.value||"",button=$("imagesConsoleImport");button.disabled=true;try{const result=await window.genreactrixImportEngine?.runUrls?.(text,{limit:qty,mode:mode==="download"?"temporary":"link",prefetch:Boolean($("imagesConsolePrefetch")?.checked),target:"queue"}),records=result?.records||[];if(!records.length)throw new Error("No eligible images to import.");const failed=records.filter(r=>r.attributes?.failed).length;status(`${records.length-failed} image${records.length-failed===1?"":"s"} imported${failed?` · ${failed} failed`:''}.`);$("imagesConsoleSummary").textContent=`Imported ${records.length-failed}${failed?` · Failed ${failed}`:''}.`;switchSection("review");window.dispatchEvent(new CustomEvent("genreactrix:image-record"))}catch(error){status(`Import failed: ${error.message||error}`)}finally{button.disabled=false}}

  async function importSingleFile(file){
    if(!file)return;
    if(!String(file.type||"").startsWith("image/")){status("Choose an image file.");return}
    const button=$("imagesConsoleFileBtn");
    if(button)button.disabled=true;
    status(`Importing ${file.name}…`);
    try{
      const result=await window.genreactrixImportEngine?.runFiles?.([file],{limit:1,sourceLabel:file.name,target:"queue"}),records=result?.records||[];
      if(!records.length)throw new Error("The selected image was not imported.");
      const failed=records.filter(r=>r.attributes?.failed).length;
      if(failed)throw new Error(records[0]?.error||"The selected image failed to import.");
      $("imagesConsoleSummary").textContent=`Imported ${file.name}.`;
      status(`${file.name} imported.`);
      switchSection("review");
      window.dispatchEvent(new CustomEvent("genreactrix:image-record"));
    }catch(error){status(`Import failed: ${error.message||error}`)}
    finally{if(button)button.disabled=false}
  }
  async function restoreSelected(){const ids=[...selected];if(!ids.length){status("Select recycle items first.");return}let restored=0;for(const id of ids){try{await engine()?.restoreFromRecycle?.(id);restored++}catch{}}selected.clear();status(`${restored} restored.`);renderList("recycle");window.dispatchEvent(new CustomEvent("genreactrix:image-record"))}
  async function emptyRecycle(){const records=listFor("recycle");if(!records.length){status("Recycle bin is empty.");return}if(!confirm(`Permanently purge ${records.length} eligible recycle item${records.length===1?"":"s"}? Image Records and 64×64 thumbnails remain.`))return;const result=await engine()?.purgeRecycle?.({all:true});status(`${result?.purged||0} recycle item${result?.purged===1?"":"s"} purged.`);renderList("recycle");window.dispatchEvent(new CustomEvent("genreactrix:image-record"))}
  function open(){const amount=window.genreactrixSettingsEngine?.getCached?.("defaults.images")||window.genreactrixSettingsEngine?.getCached?.("defaults.urls")||100;if($("imagesConsoleQuantity"))$("imagesConsoleQuantity").value=String(amount);switchSection("add");$("imagesConsoleDialog")?.showModal()}
  function init(){$("imagesConsoleClose")?.addEventListener("click",()=>$("imagesConsoleDialog")?.close());document.querySelectorAll("[data-images-section]").forEach(b=>b.addEventListener("click",()=>switchSection(b.dataset.imagesSection)));$("imagesConsolePreview")?.addEventListener("click",()=>preview().catch(e=>status(String(e.message||e))));$("imagesConsoleImport")?.addEventListener("click",()=>doImport());$("imagesConsoleFolder")?.addEventListener("click",()=>{window.pendingPortraitImportLimit=Math.max(1,Number($("imagesConsoleQuantity")?.value)||100);window.pendingImportEngineMode=true;$("imagesConsoleDialog")?.close();$("folderInput")?.click()});$("imagesConsoleFileBtn")?.addEventListener("click",()=>$("imagesConsoleSingleFile")?.click());$("imagesConsoleSingleFile")?.addEventListener("change",e=>{const file=e.target.files?.[0];importSingleFile(file).finally(()=>{e.target.value=''})});$("imagesConsoleUrlFileBtn")?.addEventListener("click",()=>$("imagesConsoleUrlFile")?.click());$("imagesConsoleUrlFile")?.addEventListener("change",e=>{const file=e.target.files?.[0];loadUrlFile(file).finally(()=>{e.target.value=''})});$("imagesRestoreSelected")?.addEventListener("click",restoreSelected);$("imagesEmptyRecycle")?.addEventListener("click",emptyRecycle)}
  window.genreactrixImagesConsole={open,render:()=>switchSection(activeSection)};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
