(function(){
  'use strict';
  const PROFILE_KEY='genreactrix-import-profiles-v1';
  const now=()=>new Date().toISOString();
  const profiles=()=>{try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'[]')}catch{return[]}};
  const saveProfiles=p=>localStorage.setItem(PROFILE_KEY,JSON.stringify(p));
  function profileDefaults(){return{id:'default',name:'Default intake',sourceType:'urls',mode:window.genreactrixSettingsEngine?.get?.('acquisition.defaultMode','link')||'link',quantity:Number(window.genreactrixSettingsEngine?.get?.('defaults.urls',100))||100,prefetch:true,duplicateAction:'skip',target:'active-batch'}}
  function allProfiles(){const p=profiles();return p.length?p:[profileDefaults()]}
  function saveProfile(profile){const p=allProfiles().filter(x=>x.id!==profile.id);p.push({...profile,id:profile.id||`profile_${Date.now()}`,updatedAt:now()});saveProfiles(p);return p[p.length-1]}
  function normalizeUrls(text){return [...new Set(String(text||'').split(/\r?\n|,\s*(?=https?:)/).map(v=>v.trim()).filter(v=>/^https?:\/\//i.test(v)))]}
  function existingByUrl(){return new Map((window.genreactrixImagesEngine?.allRecords?.()||[]).filter(r=>r.source?.originalUrl).map(r=>[r.source.originalUrl,r]))}
  async function previewUrls(text,options={}){const urls=normalizeUrls(text).slice(0,Math.max(1,Number(options.limit)||100));const existing=existingByUrl();const rows=urls.map(url=>({url,duplicate:existing.has(url),existingImageId:existing.get(url)?.id||null,eligible:!existing.has(url)||options.duplicateAction==='keep'}));return{sourceType:'urls',requested:Math.max(1,Number(options.limit)||100),found:rows.length,eligible:rows.filter(r=>r.eligible).length,duplicates:rows.filter(r=>r.duplicate).length,invalid:0,rows,estimatedBytes:null}}
  async function resolveBatch(target){if(target==='none')return null;if(target==='new'){const b=await window.genreactrixBatchEngine?.createBatch?.({name:`Import ${new Date().toLocaleString()}`});return b?.id||null}return await window.genreactrixBatchEngine?.activeId?.()||'current-import'}
  async function runUrls(text,options={}){const preview=await previewUrls(text,options);if(!preview.eligible)throw new Error('No eligible images to import.');const batchId=await resolveBatch(options.target||'active-batch');const job=await window.genreactrixImportJobEngine.create({sourceType:'urls',sourceLabel:options.sourceLabel||'URL list',profileId:options.profileId||null,targetBatchId:batchId,mode:options.mode||'link',requested:preview.requested,metadata:{prefetch:Boolean(options.prefetch),duplicateAction:options.duplicateAction||'skip'}});await window.genreactrixImportJobEngine.patch(job.id,{status:'running',startedAt:now(),found:preview.found,duplicateCount:preview.duplicates,skipped:preview.duplicates});try{const eligibleText=preview.rows.filter(r=>r.eligible).map(r=>r.url).join('\n');const records=await window.genreactrixImagesEngine.importUrls(eligibleText,{limit:preview.eligible,mode:options.mode==='temporary'?'download':'link',prefetch:Boolean(options.prefetch),batchId:batchId||'current-import'});if(batchId&&window.genreactrixBatchEngine?.addImages)await window.genreactrixBatchEngine.addImages(batchId,records.map(r=>r.id));const failed=records.filter(r=>r.attributes?.failed).length;await window.genreactrixImportJobEngine.patch(job.id,{status:failed?'completed-with-failures':'completed',completedAt:now(),imported:records.length-failed,failed,imageIds:records.map(r=>r.id)});window.genreactrixNotificationsEngine?.createOrUpdate?.({severity:failed?'attention':'info',title:'Import complete',message:`${records.length-failed} imported${failed?` · ${failed} failed`:''}`,ownerEngine:'images',relatedJobId:job.id,dedupeKey:`import:${job.id}:complete`,resolved:!failed});window.dispatchEvent(new CustomEvent('genreactrix:import-complete',{detail:{jobId:job.id,imageIds:records.map(r=>r.id)}}));return{job:await window.genreactrixImportJobEngine.get(job.id),records,preview}}catch(error){await window.genreactrixImportJobEngine.patch(job.id,{status:'failed',completedAt:now(),failed:preview.eligible,errors:[String(error?.message||error)]});throw error}}
  async function runFiles(fileList,options={}){const files=[...fileList].filter(f=>f.type.startsWith('image/')).slice(0,Math.max(1,Number(options.limit)||100));if(!files.length)throw new Error('No eligible images to import.');const batchId=await resolveBatch(options.target||'active-batch');const job=await window.genreactrixImportJobEngine.create({sourceType:'folder',sourceLabel:options.sourceLabel||'Folder import',profileId:options.profileId||null,targetBatchId:batchId,mode:'temporary',requested:files.length});await window.genreactrixImportJobEngine.patch(job.id,{status:'running',startedAt:now(),found:files.length});try{const records=await window.genreactrixImagesEngine.importFiles(files,{limit:files.length,batchId:batchId||'current-import'});if(batchId&&window.genreactrixBatchEngine?.addImages)await window.genreactrixBatchEngine.addImages(batchId,records.map(r=>r.id));const failed=records.filter(r=>r.attributes?.failed).length;await window.genreactrixImportJobEngine.patch(job.id,{status:failed?'completed-with-failures':'completed',completedAt:now(),imported:records.length-failed,failed,imageIds:records.map(r=>r.id)});window.dispatchEvent(new CustomEvent('genreactrix:import-complete',{detail:{jobId:job.id,imageIds:records.map(r=>r.id)}}));return{job:await window.genreactrixImportJobEngine.get(job.id),records}}catch(error){await window.genreactrixImportJobEngine.patch(job.id,{status:'failed',completedAt:now(),failed:files.length,errors:[String(error?.message||error)]});throw error}}
  async function dashboard(){const jobs=await window.genreactrixImportJobEngine.all();const records=window.genreactrixImagesEngine?.allRecords?.()||[];return{active:jobs.filter(j=>['running','paused'].includes(j.status)),recent:jobs.slice(0,20),failed:jobs.filter(j=>j.status==='failed'||j.status==='completed-with-failures'),pendingAi:records.filter(r=>r.components?.ai?.description?.status==='missing'||r.workflow?.stage==='available').length,readyForDirector:records.filter(r=>r.workflow?.stage==='ready-for-director').length}}
  window.genreactrixImportEngine={allProfiles,saveProfile,previewUrls,runUrls,runFiles,dashboard,verify:()=>window.genreactrixImportJobEngine.verify()};
})();
