/* Genreactrix Maintenance and Recovery Engine v1 */
(()=>{'use strict';
const DB='genreactrix-maintenance',VERSION=1,ISSUES='issues',REPORTS='reports',MIGRATIONS='migrations';
const now=()=>new Date().toISOString(),uid=p=>`${p}_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`,clone=v=>v==null?v:structuredClone(v);
const checkers=new Map(),repairs=new Map(),listeners=new Set();
let cache={issues:[],reports:[],migrations:[]};
const openDb=()=>new Promise((res,rej)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(ISSUES)){const s=db.createObjectStore(ISSUES,{keyPath:'id'});s.createIndex('status','status');s.createIndex('severity','severity');s.createIndex('ownerEngine','ownerEngine');s.createIndex('dedupeKey','dedupeKey');s.createIndex('detectedAt','detectedAt')}if(!db.objectStoreNames.contains(REPORTS)){const s=db.createObjectStore(REPORTS,{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('type','type')}if(!db.objectStoreNames.contains(MIGRATIONS)){const s=db.createObjectStore(MIGRATIONS,{keyPath:'id'});s.createIndex('status','status')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const put=(store,v)=>openDb().then(db=>new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).put(clone(v));t.oncomplete=()=>{db.close();res(v)};t.onerror=()=>rej(t.error)}));
const del=(store,id)=>openDb().then(db=>new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).delete(id);t.oncomplete=()=>{db.close();res()};t.onerror=()=>rej(t.error)}));
const all=store=>openDb().then(db=>new Promise((res,rej)=>{const t=db.transaction(store),q=t.objectStore(store).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()}));
function emit(){window.dispatchEvent(new CustomEvent('genreactrix:maintenance',{detail:snapshot()}));listeners.forEach(fn=>{try{fn(snapshot())}catch(e){console.warn(e)}});render()}
function snapshot(){return clone({issues:cache.issues,reports:cache.reports,migrations:cache.migrations,summary:{open:cache.issues.filter(i=>!['resolved','ignored'].includes(i.status)).length,critical:cache.issues.filter(i=>i.severity==='critical'&&!['resolved','ignored'].includes(i.status)).length,repairable:cache.issues.filter(i=>i.autoRepairSafe||i.availableRepairs?.length).length,lastReport:cache.reports[0]||null}})}
async function refresh(){const [issues,reports,migrations]=await Promise.all([all(ISSUES),all(REPORTS),all(MIGRATIONS)]);cache={issues:issues.sort((a,b)=>b.detectedAt.localeCompare(a.detectedAt)),reports:reports.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),migrations:migrations.sort((a,b)=>(b.startedAt||'').localeCompare(a.startedAt||''))};emit();return snapshot()}
function normalizeFinding(ownerEngine,f={}){const key=f.dedupeKey||`${ownerEngine}:${f.type||f.issueType||'issue'}:${f.imageId||f.recordId||f.jobId||f.reportId||f.batchId||''}`;return{severity:f.severity||severityFor(f.type||f.issueType),issueType:f.type||f.issueType||'unknown',ownerEngine,affectedIds:[f.imageId,f.recordId,f.jobId,f.reportId,f.batchId].filter(Boolean),summary:f.summary||humanize(f.type||f.issueType||'Issue'),technicalDetails:f.technicalDetails||f.message||f.error||'',suggestedAction:f.suggestedAction||'',availableRepairs:Array.isArray(f.availableRepairs)?f.availableRepairs:[],autoRepairSafe:Boolean(f.autoRepairSafe),dedupeKey:key}}
function humanize(s){return String(s||'issue').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function severityFor(type=''){type=String(type);if(/missing-history|history|data-loss|duplicate-id|critical|restore-failed|migration-failed/.test(type))return'critical';if(/missing|failed|stuck|blocked|mismatch|invalid/.test(type))return'attention';if(/orphan|stale|warning/.test(type))return'warning';return'info'}
async function upsertIssue(f){const existing=cache.issues.find(i=>i.dedupeKey===f.dedupeKey&&!['resolved','ignored'].includes(i.status));if(existing){Object.assign(existing,f,{lastCheckedAt:now(),occurrences:(existing.occurrences||1)+1});await put(ISSUES,existing);return existing}const issue={id:uid('maint_issue'),schemaVersion:1,detectedAt:now(),lastCheckedAt:now(),severity:f.severity,status:f.availableRepairs?.length||f.autoRepairSafe?'repair-available':'open',issueType:f.issueType,ownerEngine:f.ownerEngine,affectedIds:f.affectedIds||[],summary:f.summary,technicalDetails:f.technicalDetails||'',suggestedAction:f.suggestedAction||'',availableRepairs:f.availableRepairs||[],autoRepairSafe:Boolean(f.autoRepairSafe),repairAttempts:[],resolvedAt:null,ignoredAt:null,relatedNotificationId:null,dedupeKey:f.dedupeKey,occurrences:1};await put(ISSUES,issue);return issue}
function registerChecker(id,fn,{quick=true,label=id}={}){checkers.set(id,{fn,quick,label});return()=>checkers.delete(id)}
function registerRepair(id,fn,{destructive=false,label=id}={}){repairs.set(id,{fn,destructive,label});return()=>repairs.delete(id)}
async function runCheck(type='full',selected=[]){const startedAt=now(),chosen=[...checkers.entries()].filter(([id,c])=>type==='quick'?c.quick:type==='selected'?selected.includes(id):true);const raw=[],errors=[];for(const [id,c] of chosen){try{const result=await c.fn();const findings=result?.issues||result?.storageIssues||[];for(const f of findings)raw.push(normalizeFinding(id,f));if(result?.historyIntegrity?.issues)for(const f of result.historyIntegrity.issues)raw.push(normalizeFinding('history',f))}catch(e){errors.push({checker:id,error:e.message});raw.push(normalizeFinding(id,{type:'checker-failed',severity:'attention',message:e.message}))}}
const seen=new Set();for(const f of raw){seen.add(f.dedupeKey);await upsertIssue(f)}for(const issue of cache.issues.filter(i=>!['resolved','ignored'].includes(i.status)&&chosen.some(([id])=>id===issue.ownerEngine)&&!seen.has(issue.dedupeKey))){issue.status='resolved';issue.resolvedAt=now();issue.lastCheckedAt=now();await put(ISSUES,issue)}
const report={id:uid('maint_report'),schemaVersion:1,type,createdAt:now(),startedAt,completedAt:now(),checkers:chosen.map(([id])=>id),recordsChecked:chosen.length,findings:raw,errors,summary:{total:raw.length,critical:raw.filter(x=>x.severity==='critical').length,attention:raw.filter(x=>x.severity==='attention').length,warning:raw.filter(x=>x.severity==='warning').length,info:raw.filter(x=>x.severity==='info').length}};await put(REPORTS,report);await refresh();if(report.summary.critical||report.summary.attention)window.genreactrixNotificationsEngine?.create?.({severity:report.summary.critical?'critical':'attention',title:'Maintenance findings',message:`${report.summary.total} issue(s) found`,ownerEngine:'maintenance',relatedReportId:report.id,actionTarget:'maintenance',actionLabel:'Review',dedupeKey:`maintenance:${report.id}`});return report}
const runQuickCheck=()=>runCheck('quick');const runFullCheck=()=>runCheck('full');const runSelectedChecks=ids=>runCheck('selected',ids);
async function patchIssue(id,changes){const issue=cache.issues.find(i=>i.id===id);if(!issue)return null;Object.assign(issue,changes,{lastCheckedAt:now()});await put(ISSUES,issue);await refresh();return clone(issue)}
const ignoreIssue=id=>patchIssue(id,{status:'ignored',ignoredAt:now()});const unignoreIssue=id=>patchIssue(id,{status:'open',ignoredAt:null});
async function executeRepair(issueId,repairId,options={}){const issue=cache.issues.find(i=>i.id===issueId);const repair=repairs.get(repairId);if(!issue||!repair)throw new Error('Repair is not available');if(repair.destructive&&!options.confirmed)throw new Error('Destructive repair requires confirmation');issue.status='repairing';issue.repairAttempts.push({repairId,startedAt:now(),status:'running'});await put(ISSUES,issue);try{const result=await repair.fn(issue,options);const attempt=issue.repairAttempts.at(-1);Object.assign(attempt,{completedAt:now(),status:'complete',result});issue.status='resolved';issue.resolvedAt=now();await put(ISSUES,issue);await refresh();window.genreactrixNotificationsEngine?.create?.({severity:'info',title:'Repair complete',message:issue.summary,ownerEngine:'maintenance',actionTarget:'maintenance',actionLabel:'Maintenance',dedupeKey:`repair:${issue.id}:complete`,resolved:true});return result}catch(e){const attempt=issue.repairAttempts.at(-1);Object.assign(attempt,{completedAt:now(),status:'failed',error:e.message});issue.status='cannot-repair';await put(ISSUES,issue);await refresh();window.genreactrixNotificationsEngine?.create?.({severity:'critical',title:'Repair failed',message:`${issue.summary} · ${e.message}`,ownerEngine:'maintenance',actionTarget:'maintenance',actionLabel:'Maintenance',dedupeKey:`repair:${issue.id}:failed`});throw e}}
async function recoverImage(imageId,{file=null}={}){const record=window.genreactrixImagesEngine?.recordById?.(imageId);if(!record)throw new Error('Image record not found');if(record.attributes?.inRecycleBin){const r=await window.genreactrixImagesEngine.restoreFromRecycle(imageId);await appendRecoveryReport('recycle-restore',imageId,{success:Boolean(r)});return r}if(file&&window.genreactrixImagesEngine?.importFiles){const result=await window.genreactrixImagesEngine.importFiles([file],{batchId:record.batchId||null,provenance:{recoveryOf:imageId}});await appendRecoveryReport('manual-relink',imageId,{success:true,newIds:result?.ids||[]});return result}throw new Error('No automatic recovery source is currently accessible')}
async function appendRecoveryReport(type,imageId,result){const report={id:uid('maint_report'),schemaVersion:1,type:'recovery',createdAt:now(),startedAt:now(),completedAt:now(),checkers:['recovery'],recordsChecked:1,findings:[],errors:result.success?[]:[result],summary:{total:result.success?0:1,critical:result.success?0:1,attention:0,warning:0,info:result.success?1:0},recovery:{type,imageId,result}};await put(REPORTS,report);await refresh();return report}
async function restoreRecycleItem(id){const r=await window.genreactrixImagesEngine?.restoreFromRecycle?.(id);await appendRecoveryReport('recycle-restore',id,{success:Boolean(r)});return r}
async function purgeRecycle(options={}){const records=(window.genreactrixImagesEngine?.allRecords?.()||[]).filter(r=>r.attributes?.inRecycleBin&&!r.attributes?.saved&&!r.attributes?.flagged);const preview={count:records.length,size:records.reduce((n,r)=>n+(Number(r.storage?.size)||0),0),records:records.map(r=>({id:r.id,name:r.source?.originalFilename||r.id,size:r.storage?.size||0,deletedAt:r.storage?.recycle?.deletedAt||null}))};if(options.previewOnly!==false)return preview;const result=await window.genreactrixImagesEngine?.purgeRecycle?.(options);await appendRecoveryReport('recycle-purge','multiple',{success:true,...result});return result}
async function previewBackupRestore(file){const payload=await window.genreactrixSettingsEngine.previewBackup(file);const dbs=payload.databases||[];return{payload,summary:{type:payload.type,schemaVersion:payload.schemaVersion,createdAt:payload.createdAt,projectId:payload.projectId||payload.settings?.values?.['project.id']||'',databaseCount:dbs.length,recordCount:payload.manifest?.recordCount||dbs.reduce((n,d)=>n+Object.values(d.stores||{}).reduce((s,v)=>s+(Array.isArray(v)?v.length:0),0),0)}}}
async function restoreBackup(payload,{mode='merge'}={}){if(payload.type!=='genreactrix-backup')throw new Error('A complete Genreactrix backup is required');const emergency=await window.genreactrixSettingsEngine.createBackup('data');downloadJson(emergency,`genreactrix-emergency-backup-${new Date().toISOString().replace(/[:.]/g,'-')}.json`);const startedAt=now(),result={databases:0,records:0,mode};for(const dbDump of payload.databases||[]){if(mode==='replace')await deleteDatabase(dbDump.name);await restoreDatabase(dbDump,{merge:mode!=='replace'});result.databases++;result.records+=Object.values(dbDump.stores||{}).reduce((n,a)=>n+(Array.isArray(a)?a.length:0),0)}if(payload.settings)await window.genreactrixSettingsEngine.importSettings(payload.settings);const report={id:uid('maint_report'),schemaVersion:1,type:'restore',createdAt:now(),startedAt,completedAt:now(),checkers:['backup'],recordsChecked:result.records,findings:[],errors:[],summary:{total:0,critical:0,attention:0,warning:0,info:1},restore:result};await put(REPORTS,report);await refresh();await runFullCheck();window.genreactrixNotificationsEngine?.create?.({severity:'info',title:'Restore complete',message:`${result.records} record(s) restored`,ownerEngine:'maintenance',actionTarget:'maintenance',actionLabel:'Maintenance',dedupeKey:`restore:${report.id}`,resolved:true});return result}
const deleteDatabase=name=>new Promise((res,rej)=>{const r=indexedDB.deleteDatabase(name);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);r.onblocked=()=>rej(new Error(`Database ${name} is open`))});
async function restoreDatabase(dump,{merge=true}={}){if(!dump?.name)return;const db=await new Promise((res,rej)=>{const r=indexedDB.open(dump.name,dump.version||1);r.onupgradeneeded=()=>{const d=r.result;for(const [name,rows] of Object.entries(dump.stores||{}))if(!d.objectStoreNames.contains(name)){const first=rows?.[0];d.createObjectStore(name,{keyPath:first&&typeof first==='object'&&'id'in first?'id':undefined,autoIncrement:!(first&&typeof first==='object'&&'id'in first)})}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});for(const [name,rows] of Object.entries(dump.stores||{})){if(!db.objectStoreNames.contains(name))continue;await new Promise((res,rej)=>{const t=db.transaction(name,'readwrite'),s=t.objectStore(name);if(!merge)s.clear();for(const row of rows||[])try{s.put(clone(row))}catch(e){console.warn(e)}t.oncomplete=res;t.onerror=()=>rej(t.error)})}db.close()}
function downloadJson(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportReport(id,format='json'){const r=cache.reports.find(x=>x.id===id);if(!r)return;if(format==='json')return downloadJson(r,`genreactrix-maintenance-${id}.json`);const rows=r.findings||[],csv=['severity,owner,type,summary,details',...rows.map(x=>[x.severity,x.ownerEngine,x.issueType,x.summary,x.technicalDetails].map(v=>`"${String(v||'').replace(/"/g,'""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`genreactrix-maintenance-${id}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const list=document.getElementById('maintenanceIssueList');if(list){const filter=document.getElementById('maintenanceIssueFilter')?.value||'open';const rows=cache.issues.filter(i=>filter==='all'||filter==='open'?!['resolved','ignored'].includes(i.status):i.status===filter||i.severity===filter);list.innerHTML=rows.map(i=>`<article class="maintenance-issue severity-${i.severity}"><div><strong>${escape(i.summary)}</strong><small>${escape(i.ownerEngine)} · ${escape(i.status)} · ${new Date(i.detectedAt).toLocaleString()}</small>${i.technicalDetails?`<p>${escape(i.technicalDetails)}</p>`:''}</div><div>${i.availableRepairs?.map(r=>`<button data-repair="${escape(r)}" data-issue="${i.id}">${escape(repairs.get(r)?.label||r)}</button>`).join('')||''}<button data-ignore="${i.id}">${i.status==='ignored'?'Unignore':'Ignore'}</button></div></article>`).join('')||'<p class="maintenance-empty">No matching issues.</p>'}const summary=document.getElementById('maintenanceSummary');if(summary){const s=snapshot().summary;summary.textContent=`Open ${s.open} · Critical ${s.critical} · Repairable ${s.repairable}`}}
function openConsole(){document.getElementById('maintenanceDialog')?.showModal();render()}
function initUi(){document.getElementById('maintenanceClose')?.addEventListener('click',()=>document.getElementById('maintenanceDialog')?.close());document.getElementById('maintenanceQuick')?.addEventListener('click',async()=>{setStatus('Running quick check…');const r=await runQuickCheck();setStatus(`Quick check: ${r.summary.total} issue(s).`)});document.getElementById('maintenanceFull')?.addEventListener('click',async()=>{setStatus('Running full check…');const r=await runFullCheck();setStatus(`Full check: ${r.summary.total} issue(s).`)});document.getElementById('maintenanceIssueFilter')?.addEventListener('change',render);document.getElementById('maintenanceIssueList')?.addEventListener('click',async e=>{const id=e.target.dataset.issue;if(!id)return;if(e.target.dataset.repair){if(repairs.get(e.target.dataset.repair)?.destructive&&!confirm('This repair may permanently remove data. Continue?'))return;await executeRepair(id,e.target.dataset.repair,{confirmed:true})}else if(e.target.dataset.ignore){const issue=cache.issues.find(i=>i.id===id);issue?.status==='ignored'?await unignoreIssue(id):await ignoreIssue(id)}});document.getElementById('maintenanceRecyclePreview')?.addEventListener('click',async()=>{const p=await purgeRecycle({previewOnly:true});setStatus(`${p.count} eligible recycle item(s) · ${(p.size/1048576).toFixed(1)} MB.`)});document.getElementById('maintenanceReports')?.addEventListener('click',()=>{const out=document.getElementById('maintenanceReportList');out.innerHTML=cache.reports.map(r=>`<div class="maintenance-report-row"><span>${escape(r.type)} · ${new Date(r.createdAt).toLocaleString()} · ${r.summary?.total||0} issue(s)</span><button data-export-report="${r.id}">JSON</button><button data-export-csv="${r.id}">CSV</button></div>`).join('')||'No reports.'});document.getElementById('maintenanceReportList')?.addEventListener('click',e=>{if(e.target.dataset.exportReport)exportReport(e.target.dataset.exportReport,'json');if(e.target.dataset.exportCsv)exportReport(e.target.dataset.exportCsv,'csv')});document.getElementById('maintenanceRestoreFile')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const p=await previewBackupRestore(file);const s=p.summary;document.getElementById('maintenanceRestorePreview').textContent=`${s.createdAt||''} · ${s.databaseCount} database(s) · ${s.recordCount} record(s)`;document.getElementById('maintenanceRestoreRun').disabled=false;document.getElementById('maintenanceRestoreRun').onclick=async()=>{const mode=document.getElementById('maintenanceRestoreMode').value;if(!confirm(`Restore backup using ${mode} mode? An emergency backup will download first.`))return;setStatus('Restoring…');await restoreBackup(p.payload,{mode});setStatus('Restore complete.')}}catch(err){setStatus(err.message)}})}
function setStatus(s){const el=document.getElementById('maintenanceStatus');if(el)el.textContent=s;const settings=document.getElementById('settingsStatus');if(settings)settings.textContent=s}
function registerBuiltIns(){registerChecker('images',async()=>window.genreactrixImagesEngine?.verifyStorage?.()||{issues:[]},{quick:true,label:'Images'});registerChecker('history',async()=>window.genreactrixHistoryEngine?.verifyContinuity?.(window.genreactrixImagesEngine?.allRecords?.()||[])||{issues:[]},{quick:false,label:'History'});registerChecker('queue',async()=>window.genreactrixQueueEngine?.verify?.()||{issues:[]},{quick:true,label:'Queue'});registerChecker('reports',async()=>window.genreactrixReportsEngine?.integrity?.()||{issues:[]},{quick:false,label:'Reports'});registerChecker('notifications',async()=>window.genreactrixNotificationsEngine?.verify?.()||{issues:[]},{quick:false,label:'Notifications'});registerChecker('settings',async()=>window.genreactrixSettingsEngine?.verify?.()||{issues:[]},{quick:true,label:'Settings'});registerChecker('batch',async()=>window.genreactrixBatchEngine?.verify?.()||{issues:[]},{quick:true,label:'Batch'});registerChecker('ai',async()=>window.genreactrixAIAnalysisEngine?.verify?.()||{issues:[]},{quick:true,label:'AI'});registerRepair('restore-recycle',async issue=>{const id=issue.affectedIds?.[0];if(!id)throw new Error('No image ID');return restoreRecycleItem(id)},{label:'Restore'});registerRepair('reset-processing',async issue=>{const q=window.genreactrixQueueEngine;const id=issue.affectedIds?.[0];if(!q||!id)throw new Error('Queue item unavailable');return q.patchItem?.(id,{state:'queued',error:'Recovered by maintenance'})},{label:'Reset to queued'});window.genreactrixNotificationsEngine?.registerAction?.('maintenance',openConsole)}
const api={registerChecker,registerRepair,runQuickCheck,runFullCheck,runSelectedChecks,getIssue:id=>clone(cache.issues.find(i=>i.id===id)),queryIssues:()=>clone(cache.issues),ignoreIssue,unignoreIssue,executeRepair,recoverImage,restoreRecycleItem,purgeRecycle,previewBackupRestore,restoreBackup,reports:()=>clone(cache.reports),exportReport,openConsole,refresh,snapshot,subscribe:fn=>(listeners.add(fn),()=>listeners.delete(fn))};window.genreactrixMaintenanceEngine=api;window.addEventListener('DOMContentLoaded',async()=>{registerBuiltIns();initUi();await refresh()});
})();
