(()=>{
'use strict';
const DB='genreactrix-methodology-v1', VERSION=1, STORE='methods';
const now=()=>new Date().toISOString();
const uid=()=>`method-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('title','title');s.createIndex('status','status');s.createIndex('category','category');s.createIndex('updatedAt','updatedAt')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getAll(){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve((r.result||[]).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))));r.onerror=()=>reject(r.error)})}
async function get(id){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function put(v){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(v);r.onsuccess=()=>resolve(v);r.onerror=()=>reject(r.error)})}
async function save(input={}){const old=input.id?await get(input.id):null;const title=String(input.title??old?.title??'').trim();if(!title)throw new Error('Methodology title required');const item={id:old?.id||input.id||uid(),schemaVersion:1,title,category:String(input.category??old?.category??'general'),summary:String(input.summary??old?.summary??''),body:String(input.body??old?.body??''),versionLabel:String(input.versionLabel??old?.versionLabel??'1.0'),status:input.status??old?.status??'draft',termIds:[...(input.termIds??old?.termIds??[])],evidence:{publicationIds:[...(input.evidence?.publicationIds??old?.evidence?.publicationIds??[])],reportIds:[...(input.evidence?.reportIds??old?.evidence?.reportIds??[])],findingIds:[...(input.evidence?.findingIds??old?.evidence?.findingIds??[])]},revision:Number(old?.revision||0)+1,revisionHistory:old?[...(old.revisionHistory||[]),{revision:old.revision,title:old.title,versionLabel:old.versionLabel,status:old.status,summary:old.summary,body:old.body,updatedAt:old.updatedAt}]:[],createdAt:old?.createdAt||now(),updatedAt:now(),publishedAt:input.status==='published'&&!old?.publishedAt?now():old?.publishedAt||null};return put(item)}
async function search(query='',options={}){const q=String(query).trim().toLowerCase();let rows=await getAll();if(options.category)rows=rows.filter(m=>m.category===options.category);if(options.status)rows=rows.filter(m=>m.status===options.status);if(q)rows=rows.filter(m=>[m.title,m.summary,m.body,m.category,m.versionLabel].some(v=>String(v||'').toLowerCase().includes(q)));return rows}
async function verify(){const rows=await getAll(),issues=[];for(const m of rows){if(!m.title)issues.push({severity:'warning',type:'method-title-missing',id:m.id});if(m.status==='published'&&!m.publishedAt)issues.push({severity:'attention',type:'method-published-date-missing',id:m.id});if(m.status==='published'&&!m.body.trim())issues.push({severity:'attention',type:'method-body-missing',id:m.id});if(window.genreactrixTerminologyEngine){for(const termId of m.termIds||[]){if(!(await window.genreactrixTerminologyEngine.get(termId)))issues.push({severity:'warning',type:'method-term-missing',id:m.id,termId})}}}return {checked:rows.length,issues}}
window.genreactrixMethodologyEngine={save,get,getAll,search,verify};
})();
