/* Genreactrix Notifications Engine v1 */
(()=>{'use strict';
const DB='genreactrix-notifications',VERSION=1,STORE='notifications';
const now=()=>new Date().toISOString(),uid=()=>`notice_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`,clone=v=>structuredClone(v);
const openDb=()=>new Promise((res,rej)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('read','read');s.createIndex('archived','archived');s.createIndex('severity','severity');s.createIndex('dedupeKey','dedupeKey')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const all=()=>openDb().then(db=>new Promise((res,rej)=>{const t=db.transaction(STORE),q=t.objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()}));
const put=v=>openDb().then(db=>new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(clone(v));t.oncomplete=()=>{db.close();res(v)};t.onerror=()=>rej(t.error)}));
let cache=[],handlers=new Map();
async function refresh(){cache=(await all()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));render();window.dispatchEvent(new CustomEvent('genreactrix:notifications',{detail:snapshot()}));return snapshot()}
function snapshot(){return{items:clone(cache),unread:cache.filter(n=>!n.read&&!n.archived).length,attention:cache.filter(n=>!n.archived&&['attention','critical'].includes(n.severity)&&!n.resolved).length}}
async function create(input={}){const key=input.dedupeKey||'';let n=key?cache.find(x=>x.dedupeKey===key&&!x.resolved&&!x.archived):null;if(n){n.createdAt=now();n.message=input.message||n.message;n.title=input.title||n.title;n.severity=input.severity||n.severity;n.occurrences=(n.occurrences||1)+1;n.read=false;await put(n);return refresh()}n={id:uid(),schemaVersion:1,createdAt:now(),readAt:null,archivedAt:null,severity:input.severity||'info',title:input.title||'Notification',message:input.message||'',ownerEngine:input.ownerEngine||'',relatedJobId:input.relatedJobId||null,relatedBatchId:input.relatedBatchId||null,relatedReportId:input.relatedReportId||null,actionTarget:input.actionTarget||'',actionLabel:input.actionLabel||'Open',dedupeKey:key,persistent:Boolean(input.persistent),read:false,archived:false,resolved:Boolean(input.resolved),occurrences:1};await put(n);return refresh()}
async function patch(id,changes){const n=cache.find(x=>x.id===id);if(!n)return;Object.assign(n,changes);await put(n);return refresh()}
const markRead=id=>patch(id,{read:true,readAt:now()});const markUnread=id=>patch(id,{read:false,readAt:null});const archive=id=>patch(id,{archived:true,archivedAt:now(),read:true,readAt:now()});const restore=id=>patch(id,{archived:false,archivedAt:null});const resolve=id=>patch(id,{resolved:true});
async function markAllRead(){for(const n of cache.filter(x=>!x.read&&!x.archived)){n.read=true;n.readAt=now();await put(n)}return refresh()}
async function archiveResolved(){for(const n of cache.filter(x=>x.resolved&&!x.archived)){n.archived=true;n.archivedAt=now();await put(n)}return refresh()}
function registerAction(target,fn){handlers.set(target,fn)}
async function openTarget(id){const n=cache.find(x=>x.id===id);if(!n)return;await markRead(id);const fn=handlers.get(n.actionTarget);if(fn)return fn(n);if(n.actionTarget==='queue')return window.genreactrixQueueEngine?.openConsole?.();if(n.actionTarget==='ai')return window.genreactrixAIAnalysisEngine?.openConsole?.();if(n.actionTarget==='batch')return window.genreactrixBatchEngine?.openConsole?.();if(n.actionTarget==='reports')return window.genreactrixReportsEngine?.openConsole?.();if(n.actionTarget==='images')return window.genreactrixImagesEngine?.openConsole?.()}
function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const badge=document.getElementById('portraitMailboxBadge'),snap=snapshot();if(badge){badge.textContent=snap.unread>99?'99+':String(snap.unread);badge.hidden=!snap.unread}const list=document.getElementById('notificationsList');if(!list)return;const filter=document.getElementById('notificationsFilter')?.value||'all';const rows=cache.filter(n=>filter==='all'?!n.archived:filter==='unread'?!n.archived&&!n.read:filter==='attention'?!n.archived&&['attention','critical'].includes(n.severity):filter==='critical'?!n.archived&&n.severity==='critical':n.archived);list.innerHTML=rows.map(n=>`<article class="notification-row ${n.read?'is-read':'is-unread'} severity-${n.severity}" data-id="${n.id}"><div><strong>${escape(n.title)}</strong><small>${new Date(n.createdAt).toLocaleString()} · ${escape(n.ownerEngine||'system')}${n.occurrences>1?` · ×${n.occurrences}`:''}</small><p>${escape(n.message)}</p></div><div class="notification-actions">${n.actionTarget?`<button data-open="${n.id}">${escape(n.actionLabel||'Open')}</button>`:''}<button data-read="${n.id}">${n.read?'Unread':'Read'}</button><button data-archive="${n.id}">${n.archived?'Restore':'Archive'}</button></div></article>`).join('')||'<p class="notifications-empty">No notifications.</p>'}

async function verify(){const issues=[],seen=new Set();for(const n of cache){if(!['info','attention','critical'].includes(n.severity))issues.push({type:'invalid-notification-severity',recordId:n.id});if(n.dedupeKey&&!n.resolved&&!n.archived){if(seen.has(n.dedupeKey))issues.push({type:'duplicate-notification-key',recordId:n.id,severity:'warning'});seen.add(n.dedupeKey)}if(n.archived&&!n.read)issues.push({type:'archived-unread-notification',recordId:n.id,severity:'warning'})}return{notificationCount:cache.length,issueCount:issues.length,issues}}
function openConsole(){document.getElementById('notificationsDialog')?.showModal();render()}
function initUi(){document.getElementById('notificationsClose')?.addEventListener('click',()=>document.getElementById('notificationsDialog')?.close());document.getElementById('notificationsFilter')?.addEventListener('change',render);document.getElementById('notificationsMarkAllRead')?.addEventListener('click',markAllRead);document.getElementById('notificationsArchiveResolved')?.addEventListener('click',archiveResolved);document.getElementById('notificationsList')?.addEventListener('click',e=>{const id=e.target.dataset.open||e.target.dataset.read||e.target.dataset.archive;if(!id)return;if(e.target.dataset.open)openTarget(id);else if(e.target.dataset.read){const n=cache.find(x=>x.id===id);n?.read?markUnread(id):markRead(id)}else{const n=cache.find(x=>x.id===id);n?.archived?restore(id):archive(id)}})}
const engine={create,refresh,snapshot,markRead,markUnread,archive,restore,resolve,markAllRead,archiveResolved,registerAction,openTarget,openConsole,verify};window.genreactrixNotificationsEngine=engine;window.addEventListener('DOMContentLoaded',()=>{initUi();refresh()});
})();
