/* Genreactrix Queue Engine v1
   Shared persistent scheduling/state for engine-owned work. Domain engines retain business logic. */
(()=>{'use strict';
 const DB='genreactrix-queue',VERSION=2,JOBS='jobs',ITEMS='items';
 const now=()=>new Date().toISOString(),uid=p=>`${p}_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`,clone=v=>v==null?v:structuredClone(v);
 const adapters=new Map(),listeners=new Set();
 let cache={jobs:[],items:[],summary:{queued:0,running:0,paused:0,failed:0,blocked:0,completedToday:0,acquisitionPending:0,aiPending:0,reportsPending:0}};
 const openDb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(JOBS)){const s=db.createObjectStore(JOBS,{keyPath:'id'});s.createIndex('state','state');s.createIndex('type','type');s.createIndex('createdAt','createdAt')}if(!db.objectStoreNames.contains(ITEMS)){const s=db.createObjectStore(ITEMS,{keyPath:'id'});s.createIndex('jobId','jobId');s.createIndex('state','state');s.createIndex('imageId','imageId')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
 const tx=(store,mode,fn)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,mode),s=t.objectStore(store);let out;try{out=fn(s,t)}catch(e){db.close();reject(e);return}t.oncomplete=()=>{db.close();resolve(out)};t.onerror=()=>{db.close();reject(t.error)}}));
 const put=(store,value)=>tx(store,'readwrite',s=>s.put(clone(value)));
 const del=(store,id)=>tx(store,'readwrite',s=>s.delete(id));
 const all=store=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readonly'),r=t.objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
 const byIndex=(store,index,value)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readonly'),r=t.objectStore(store).index(index).getAll(value);r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
 function summarize(jobs,items){const today=new Date().toDateString(),visibleJobs=jobs.filter(j=>j.type!=='ai'),visibleIds=new Set(visibleJobs.map(j=>j.id)),visibleItems=items.filter(i=>visibleIds.has(i.jobId)),count=s=>visibleJobs.filter(j=>j.state===s).length,pendingType=t=>visibleJobs.filter(j=>j.type===t&&['queued','running','paused','stopping'].includes(j.state)).length;return{queued:count('queued'),running:count('running'),paused:count('paused'),failed:count('failed')+count('completed-with-failures'),blocked:visibleItems.filter(i=>i.state==='blocked').length,completedToday:visibleJobs.filter(j=>j.completedAt&&new Date(j.completedAt).toDateString()===today).length,acquisitionPending:pendingType('acquisition'),aiPending:items.filter(i=>i.type==='ai'&&['waiting','queued','processing'].includes(i.state)).length,reportsPending:pendingType('report')}}
 async function refresh(){const [jobs,items]=await Promise.all([all(JOBS),all(ITEMS)]);cache={jobs,items,summary:summarize(jobs,items)};emit();render();return snapshot()}
 function snapshot(){return clone(cache)}
 function emit(){window.dispatchEvent(new CustomEvent('genreactrix:queue',{detail:snapshot()}));listeners.forEach(fn=>{try{fn(snapshot())}catch(e){console.warn(e)}});window.renderPortraitControlStation?.()}
 function registerType(type,adapter){adapters.set(type,adapter||{});return()=>adapters.delete(type)}
 async function createJob(input={}){const requestedId=input.id||uid('queue_job'),existing=cache.jobs.find(j=>j.id===requestedId)||(await all(JOBS)).find(j=>j.id===requestedId);if(existing)return clone(existing);const ctx=window.genreactrixProjectRuntimeEngine,job={id:requestedId,schemaVersion:2,projectId:input.projectId||ctx?.projectId?.()||'',runtimeId:input.runtimeId||ctx?.runtimeId?.()||null,type:input.type||'generic',ownerEngine:input.ownerEngine||input.type||'generic',ownerJobId:input.ownerJobId||null,label:input.label||'Queued work',createdAt:input.createdAt||now(),startedAt:null,pausedAt:null,resumedAt:null,completedAt:null,failedAt:null,state:input.state||'queued',priority:input.priority||'normal',total:Number(input.total)||0,completed:Number(input.completed)||0,failed:Number(input.failed)||0,skipped:Number(input.skipped)||0,active:0,progress:Number(input.progress)||0,message:input.message||'Queued',stopRequested:false,batchId:input.batchId||null,imageIds:Array.isArray(input.imageIds)?[...input.imageIds]:[],configurationRef:input.configurationRef||null};await put(JOBS,job);await refresh();return clone(job)}
 async function addItems(jobId,rows=[]){const created=[],existingItems=await byIndex(ITEMS,'jobId',jobId),existingIds=new Set(existingItems.map(i=>i.id)),existingOwnerIds=new Set(existingItems.map(i=>i.ownerItemId).filter(Boolean));for(const [index,row] of rows.entries()){const itemId=row.id||uid('queue_item');if(existingIds.has(itemId)||(row.ownerItemId&&existingOwnerIds.has(row.ownerItemId)))continue;const ctx=window.genreactrixProjectRuntimeEngine,item={id:itemId,schemaVersion:2,projectId:row.projectId||ctx?.projectId?.()||'',runtimeId:row.runtimeId||ctx?.runtimeId?.()||null,jobId,imageId:row.imageId||null,type:row.type||'generic',ownerItemId:row.ownerItemId||null,order:Number.isFinite(row.order)?row.order:index,priority:row.priority||'normal',state:row.state||'queued',attempts:Number(row.attempts)||0,createdAt:row.createdAt||now(),startedAt:null,completedAt:null,error:row.error||'',blockedReason:row.blockedReason||'',dependencyIds:Array.isArray(row.dependencyIds)?[...row.dependencyIds]:[]};await put(ITEMS,item);created.push(item);existingIds.add(itemId);if(item.ownerItemId)existingOwnerIds.add(item.ownerItemId)}await recalculate(jobId);return created}
 async function patchJob(id,patch){const job=cache.jobs.find(j=>j.id===id)||(await all(JOBS)).find(j=>j.id===id);if(!job)return null;Object.assign(job,clone(patch));await put(JOBS,job);await refresh();return clone(job)}
 async function patchItem(id,patch){const item=cache.items.find(i=>i.id===id)||(await all(ITEMS)).find(i=>i.id===id);if(!item)return null;Object.assign(item,clone(patch));await put(ITEMS,item);await recalculate(item.jobId);return clone(item)}
 async function recalculate(jobId){const items=await byIndex(ITEMS,'jobId',jobId),job=(await all(JOBS)).find(j=>j.id===jobId);if(job){job.total=items.length||job.total;job.completed=items.filter(i=>i.state==='complete').length;job.failed=items.filter(i=>i.state==='failed').length;job.skipped=items.filter(i=>['skipped','cancelled'].includes(i.state)).length;job.active=items.filter(i=>i.state==='processing').length;job.progress=job.total?Math.round(((job.completed+job.failed+job.skipped)/job.total)*100):0;await put(JOBS,job)}await refresh();return job}
 async function setJobState(id,state,message=''){const stamps={running:{startedAt:now()},paused:{pausedAt:now()},completed:{completedAt:now()},'completed-with-failures':{completedAt:now()},failed:{failedAt:now()},cancelled:{completedAt:now()}}[state]||{};const job=await patchJob(id,{state,message:message||state,...stamps});if(job&&['completed','completed-with-failures','failed','paused'].includes(state)){const severity=state==='failed'?'critical':state==='completed-with-failures'?'attention':state==='paused'?'attention':'info';const title=state==='completed'?'Job completed':state==='completed-with-failures'?'Job completed with failures':state==='failed'?'Job failed':'Job paused';window.genreactrixNotificationsEngine?.create?.({severity,title,message:`${job.label}${message?` · ${message}`:''}`,ownerEngine:job.ownerEngine||job.type,relatedJobId:job.id,actionTarget:'queue',actionLabel:'Queue',dedupeKey:`queue:${job.id}:${state}`,resolved:state==='completed'});}return job}
 async function setItemState(id,state,patch={}){const stamps={processing:{startedAt:now()},complete:{completedAt:now()},failed:{completedAt:now()},skipped:{completedAt:now()},cancelled:{completedAt:now()}}[state]||{};return patchItem(id,{state,...stamps,...patch})}
 async function pause(id){const job=cache.jobs.find(j=>j.id===id);if(!job)return;const adapter=adapters.get(job.type);await adapter?.pause?.(job.ownerJobId||job.id);return setJobState(id,'paused','Paused safely')}
 async function resume(id){const job=cache.jobs.find(j=>j.id===id);if(!job)return;const adapter=adapters.get(job.type);await adapter?.resume?.(job.ownerJobId||job.id);return setJobState(id,'queued','Ready to resume')}
 async function stop(id){const job=cache.jobs.find(j=>j.id===id);if(!job)return;const terminal=['completed','completed-with-failures','failed','cancelled'];if(terminal.includes(job.state))return clone(job);const adapter=adapters.get(job.type);if(adapter?.stop){await adapter.stop(job.ownerJobId||job.id);await refresh();const after=cache.jobs.find(j=>j.id===id);if(after&&[...terminal,'stopping'].includes(after.state))return clone(after);return patchJob(id,{state:'stopping',stopRequested:true,message:'Stopping safely'})}for(const item of cache.items.filter(i=>i.jobId===id&&['waiting','queued','processing'].includes(i.state)))await setItemState(item.id,'cancelled',{error:'Stopped by user'});return setJobState(id,'cancelled','Stopped safely')}
 async function retry(id){const job=cache.jobs.find(j=>j.id===id);if(!job)return;const adapter=adapters.get(job.type);await adapter?.retry?.(job.ownerJobId||job.id);for(const item of cache.items.filter(i=>i.jobId===id&&i.state==='failed'))await setItemState(item.id,'queued',{error:''});return setJobState(id,'queued','Retry queued')}
 async function reprioritize(id,priority){return patchJob(id,{priority})}
 async function move(id,direction){const job=cache.jobs.find(j=>j.id===id);if(!job)return;const peers=cache.jobs.filter(j=>j.priority===job.priority).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),index=peers.findIndex(j=>j.id===id),swap=peers[index+(direction==='up'?-1:1)];if(!swap)return;const a=job.createdAt;await patchJob(job.id,{createdAt:swap.createdAt});await patchJob(swap.id,{createdAt:a})}
 async function removeCompleted(id){const job=cache.jobs.find(j=>j.id===id);if(!job||!['completed','completed-with-failures','failed','cancelled'].includes(job.state))throw new Error('Only finished queue records can be removed');for(const item of cache.items.filter(i=>i.jobId===id))await del(ITEMS,item.id);await del(JOBS,id);await refresh()}
 async function recoverInterrupted(){const jobs=await all(JOBS),items=await all(ITEMS);let recovered=0;for(const job of jobs.filter(j=>['running','stopping'].includes(j.state))){const rows=items.filter(i=>i.jobId===job.id);const pending=rows.filter(i=>['waiting','queued','processing'].includes(i.state));if(job.state==='stopping'&&rows.length&&!pending.length){job.state=rows.some(i=>i.state==='failed')?'completed-with-failures':'completed';job.message=job.state==='completed'?'Recovered completed job':'Recovered completed job with failures';job.completedAt=now();job.active=0;await put(JOBS,job);recovered++;continue}if(job.state==='stopping'&&job.type==='acquisition'){for(const item of pending){item.state='cancelled';item.error='Recovered stopped acquisition';item.completedAt=now();await put(ITEMS,item);recovered++}job.state='cancelled';job.message='Stopped safely';job.completedAt=now();job.active=0;await put(JOBS,job);recovered++;continue}for(const item of pending.filter(i=>i.state==='processing')){item.state='queued';item.error='Recovered after interruption';await put(ITEMS,item);recovered++}job.state='paused';job.message='Interrupted · review before resuming';job.active=0;await put(JOBS,job);recovered++}await refresh();return recovered}
 async function migrateLegacyAiQueue(){let legacy=[];try{legacy=JSON.parse(localStorage.getItem('genreactrix-ai-lookahead-queue')||'[]')}catch(e){legacy=[]}if(!Array.isArray(legacy)||!legacy.length)return 0;const valid=new Set((window.genreactrixImageRecordEngine?.all?.()||[]).map(r=>r.id));const imageIds=legacy.filter(id=>valid.has(id));if(imageIds.length){const job=await createJob({type:'ai',ownerEngine:'ai-analysis',label:'Migrated AI look-ahead',state:'paused',total:imageIds.length,imageIds,message:'Migrated from legacy look-ahead queue'});await addItems(job.id,imageIds.map((imageId,order)=>({imageId,order,type:'ai',state:'queued'})))}localStorage.removeItem('genreactrix-ai-lookahead-queue');return imageIds.length}
 function queryJobs(filter={}){return cache.jobs.filter(j=>(!filter.type||j.type===filter.type)&&(!filter.state||j.state===filter.state)&&(!filter.ownerEngine||j.ownerEngine===filter.ownerEngine)).map(clone)}
 function getJob(id){return clone(cache.jobs.find(j=>j.id===id)||null)}
 function getItems(jobId){return cache.items.filter(i=>i.jobId===jobId).sort((a,b)=>a.order-b.order).map(clone)}
 function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}
 function render(){
  const s=cache.summary,life=window.genreactrixLifecycleEngine?.snapshot?.()||{},bundles=window.genreactrixBundleEngine?.snapshot?.()||{},quarantine=window.genreactrixQuarantineEngine?.snapshot?.()||{open:0,cases:[]},set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=String(v)},esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  set('portraitQueuedCount',s.queued);set('queueRunningCount',s.running);set('queueQueuedCount',s.queued);set('queuePausedCount',s.paused);set('queueFailedCount',quarantine.open||life.quarantine||0);set('queuePartialCount',life.partial||0);set('queueStagedCount',life.staged||0);
  const auto=document.getElementById('queueAutoFlow');if(auto)auto.checked=Boolean(window.genreactrixSettingsEngine?.get?.('queue.flow.enabled',true));
  const size=document.getElementById('queueBundleSize');if(size&&document.activeElement!==size)size.value=String(Math.max(1,Number(window.genreactrixSettingsEngine?.get?.('queue.bundle.size',50))||50));
  const visibleJobs=cache.jobs.filter(j=>j.type!=='ai'),quarantineRows=(quarantine.cases||[]).map(c=>`<article class="queue-job-row" data-quarantine-case="${esc(c.id)}"><button type="button" class="queue-job-select" data-quarantine-action="inspect"><span><strong>Quarantine · ${esc(c.recordName||c.imageId)}</strong><small>${esc(c.imageId)} · ${Number(c.streak)||3} isolated AI failures${c.lastError?` · ${esc(c.lastError)}`:''}</small></span><b>${Array.isArray(c.attempts)?c.attempts.length:0}</b></button><div><button type="button" data-quarantine-action="release">Release</button><button type="button" data-quarantine-action="defective">Defective</button></div></article>`).join(''),jobRows=visibleJobs.sort((a,b)=>({high:0,normal:1,low:2}[a.priority]-({high:0,normal:1,low:2}[b.priority])||a.createdAt.localeCompare(b.createdAt))).map(j=>`<article class="queue-job-row" data-queue-job="${j.id}"><button type="button" class="queue-job-select"><span><strong>${j.label}</strong><small>${j.type} · ${j.state} · ${j.message}</small></span><b>${j.completed}/${j.total}</b></button><div>${j.state==='running'?'<button type="button" data-q-action="pause">Pause</button>':''}${j.state==='paused'?'<button type="button" data-q-action="resume">Resume</button>':''}${['failed','completed-with-failures'].includes(j.state)?'<button type="button" data-q-action="retry">Retry</button>':''}${['queued','running','paused'].includes(j.state)?'<button type="button" data-q-action="stop">Stop</button>':''}<select data-q-action="priority"><option value="high" ${j.priority==='high'?'selected':''}>High</option><option value="normal" ${j.priority==='normal'?'selected':''}>Normal</option><option value="low" ${j.priority==='low'?'selected':''}>Low</option></select></div></article>`).join('');
  const list=document.getElementById('queueJobList');if(list)list.innerHTML=quarantineRows+jobRows||'<p class="queue-empty">No Queue jobs or Quarantine cases.</p>';
 }
 function openConsole(){document.getElementById('queueDialog')?.showModal();render()}
 function initUi(){
  document.getElementById('queueDialogClose')?.addEventListener('click',()=>document.getElementById('queueDialog')?.close());
  document.getElementById('queueJobList')?.addEventListener('click',async e=>{const qrow=e.target.closest('[data-quarantine-case]'),qaction=e.target.closest('[data-quarantine-action]')?.dataset.quarantineAction;if(qrow&&qaction){const id=qrow.dataset.quarantineCase;try{if(qaction==='inspect'){await window.genreactrixInvestigationUI?.openQuarantineCase?.(id);return}if(qaction==='release')await window.genreactrixQuarantineEngine?.release?.(id);if(qaction==='defective'){if(!confirm('Finalize this image as Defective? The full-resolution image will be deleted directly. The permanent thumbnail, Image Record, and diagnostic history will remain.'))return;await window.genreactrixQuarantineEngine?.finalizeDefective?.(id)}window.setPortraitStationStatus?.(qaction==='release'?'Released from Quarantine to Queue for a fresh try.':'Defective finalized; full-resolution image deleted.');render()}catch(error){window.setPortraitStationStatus?.(`Quarantine action failed: ${error.message||error}`)}return}const row=e.target.closest('[data-queue-job]'),action=e.target.closest('[data-q-action]')?.dataset.qAction;if(!row||!action)return;const id=row.dataset.queueJob;if(action==='pause')await pause(id);if(action==='resume')await resume(id);if(action==='retry')await retry(id);if(action==='stop')await stop(id)});
  document.getElementById('queueJobList')?.addEventListener('change',e=>{if(e.target.dataset.qAction==='priority')reprioritize(e.target.closest('[data-queue-job]').dataset.queueJob,e.target.value)});
  document.getElementById('queueAutoFlow')?.addEventListener('change',async e=>{await window.genreactrixSettingsEngine?.set?.('queue.flow.enabled',e.target.checked);window.genreactrixAiAnalysisEngine?.maintainActiveMode?.().catch?.(console.warn);render();});
  document.getElementById('queueBundleSize')?.addEventListener('change',async e=>{const size=Math.max(1,Number(e.target.value)||50);await window.genreactrixSettingsEngine?.set?.('queue.bundle.size',size);await window.genreactrixBundleEngine?.maybeAutoBundle?.();window.genreactrixAiAnalysisEngine?.maintainActiveMode?.().catch?.(console.warn);render();});
  document.getElementById('queueBundleStaged')?.addEventListener('click',async()=>{const bundle=await window.genreactrixBundleEngine?.bundleStaged?.({automatic:false});window.setPortraitStationStatus?.(bundle?`${bundle.label} sent to Inbox · ${bundle.imageIds.length} image${bundle.imageIds.length===1?'':'s'}.`:'No Staged images to Bundle.');render();});
  document.getElementById('queueBundleRemainder')?.addEventListener('click',async()=>{const bundle=await window.genreactrixBundleEngine?.bundleWhateverAvailable?.();window.setPortraitStationStatus?.(bundle?`${bundle.label} sent to Inbox · ${bundle.imageIds.length} image${bundle.imageIds.length===1?'':'s'}.`:'No Staged images available.');render();});
  document.getElementById('queueRecover')?.addEventListener('click',recoverInterrupted);
  document.getElementById('queueClearFinished')?.addEventListener('click',async()=>{for(const j of [...cache.jobs])if(['completed','completed-with-failures','failed','cancelled'].includes(j.state))await removeCompleted(j.id)});
 }


 async function cleanupEmptyJobs(){let removed=0;const jobs=await all(JOBS),items=await all(ITEMS);for(const job of jobs){const rows=items.filter(i=>i.jobId===job.id);if((Number(job.total)||0)===0&&rows.length===0){await del(JOBS,job.id);removed++}}if(removed)await refresh();return removed}

 async function verify(){const issues=[],jobs=cache.jobs,items=cache.items,jobIds=new Set(jobs.map(j=>j.id));for(const item of items){if(!jobIds.has(item.jobId))issues.push({type:'orphan-queue-item',recordId:item.id,severity:'attention'});if(item.state==='processing'&&!jobs.some(j=>j.id===item.jobId&&j.state==='running'))issues.push({type:'stuck-processing-item',recordId:item.id,severity:'attention',availableRepairs:['reset-processing'],autoRepairSafe:true})}for(const job of jobs){const rows=items.filter(i=>i.jobId===job.id);if(['completed','completed-with-failures'].includes(job.state)&&rows.some(i=>['queued','waiting','processing'].includes(i.state)))issues.push({type:'completed-job-has-pending-items',jobId:job.id,severity:'attention'});if(job.total&&job.total!==rows.length)issues.push({type:'queue-count-mismatch',jobId:job.id,severity:'warning'})}return{checkedAt:now(),jobCount:jobs.length,itemCount:items.length,issueCount:issues.length,issues}}
 const engine={registerType,createJob,addItems,patchJob,patchItem,setJobState,setItemState,pause,resume,stop,retry,reprioritize,move,removeCompleted,recoverInterrupted,migrateLegacyAiQueue,queryJobs,getJob,getItems,snapshot,refresh,subscribe,openConsole,cleanupEmptyJobs,verify};window.genreactrixQueueEngine=engine;
 window.addEventListener('DOMContentLoaded',async()=>{initUi();await refresh();await cleanupEmptyJobs();await recoverInterrupted();await migrateLegacyAiQueue();render()});
 window.addEventListener('genreactrix:image-record',()=>refresh().catch(()=>{}));
 window.addEventListener('genreactrix:batch',()=>refresh().catch(()=>{}));
 window.addEventListener('genreactrix:lifecycle',()=>render());
 window.addEventListener('genreactrix:bundle',()=>render());
 window.addEventListener('genreactrix:quarantine',()=>render());
 window.addEventListener('genreactrix:setting',event=>{if(['queue.flow.enabled','queue.bundle.size','ai.lookAhead.enabled','ai.buffer.target','ai.buffer.refillThreshold','ai.lookAhead.priority'].includes(event.detail?.id))render();});
})();
