(()=>{
'use strict';
const DB='genreactrix-reports-engine-v1', REPORTS='reports', PRESETS='presets', VERSION=1;
const now=()=>new Date().toISOString();
const SESSION_STARTED=now();
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const clone=v=>v==null?v:structuredClone(v);
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(REPORTS)){const s=db.createObjectStore(REPORTS,{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('type','type');s.createIndex('batchId','batchId');}if(!db.objectStoreNames.contains(PRESETS)){const s=db.createObjectStore(PRESETS,{keyPath:'id'});s.createIndex('name','name');}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function tx(name,mode='readonly'){const db=await openDb();return db.transaction(name,mode).objectStore(name)}
async function getAll(name){const s=await tx(name);return new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function get(name,id){const s=await tx(name);return new Promise((res,rej)=>{const r=s.get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function put(name,v){const s=await tx(name,'readwrite');return new Promise((res,rej)=>{const r=s.put(v);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})}
function records(){return window.genreactrixImageRecordEngine?.all?.()||[]}
const LOCAL_DIRECTOR_REACTION_NAME_BY_INDEX=Object.freeze(['Beautiful','Adorable','Tragic','Funny','Intense','Weird','Ticket','Dreamy','Zazzly','Disgusting','Scary','Smart','Celebration','Angry']);
function customReactionLabel(token){
 const id=String(token||'').replace(/^custom:/,'');if(!id)return'';
 try{const key=window.genreactrixProjectRuntimeEngine?.projectKey?.('genreactrix-custom-reactions-v1')||'genreactrix-custom-reactions-v1';const rows=JSON.parse(localStorage.getItem(key)||localStorage.getItem('genreactrix-custom-reactions-v1')||'[]');const hit=Array.isArray(rows)?rows.find(row=>String(row?.id||'')===id):null;return String(hit?.label||hit?.name||token)}catch{return String(token)}
}
function directorReactionName(value){
 if(value==null)return'';
 if(typeof value==='number'&&Number.isInteger(value)&&value>=0&&value<LOCAL_DIRECTOR_REACTION_NAME_BY_INDEX.length)return LOCAL_DIRECTOR_REACTION_NAME_BY_INDEX[value];
 const raw=String(value).trim();if(!raw)return'';
 if(/^\d+$/.test(raw)){const index=Number(raw);if(index>=0&&index<LOCAL_DIRECTOR_REACTION_NAME_BY_INDEX.length)return LOCAL_DIRECTOR_REACTION_NAME_BY_INDEX[index]}
 if(/^custom:/i.test(raw))return customReactionLabel(raw);
 if(AI_REACTION_NAME_BY_ID[raw])return AI_REACTION_NAME_BY_ID[raw];
 return raw;
}
function directorReactions(r){const d=r.analysis?.director||{};return [...new Set((d.selectedReactions||d.reactions||[]).map(directorReactionName).filter(Boolean))]}
function directorThemes(r){return (r.analysis?.director?.themes||[]).filter(Boolean).map(x=>typeof x==='string'?x:(x.label||x.id||'Unknown'))}
function aiComponents(r){return r.analysis?.ai?.components||r.analysis?.ai||{}}
const AI_REACTION_NAME_BY_ID=Object.freeze({P01:'Adorable',P02:'Beautiful',P03:'Tragic',P04:'Funny',P05:'Intense',P06:'Weird',P07:'Ticket',P08:'Dreamy',P09:'Zazzly',P10:'Disgusting',P11:'Scary',P12:'Smart',P13:'Celebration',P14:'Angry'});
const AI_REACTION_ID_BY_NAME=Object.freeze(Object.fromEntries(Object.entries(AI_REACTION_NAME_BY_ID).map(([id,name])=>[name,id])));
const DEFAULT_ROW_FIELDS=Object.freeze(['imageId','filename','batch','directorReactions','directorThemes','primFusion','aiAgreement','saved','flagged']);
function aiReactionNames(r){const a=aiComponents(r).reactions;if(!a)return[];if(Array.isArray(a))return a.map(x=>String(x?.name||x?.reaction||AI_REACTION_NAME_BY_ID[x?.id]||x?.id||'')).filter(Boolean);return Object.keys(a).map(key=>AI_REACTION_NAME_BY_ID[key]||key)}
function aiThemeSelections(r){const raw=aiComponents(r).themes;return Array.isArray(raw)?raw.filter(Boolean):[]}
function aiThemeName(item){return String(item?.name||item?.proposedName||item?.label||item?.code||'Unknown').trim()}
function average(values){const nums=values.filter(Number.isFinite);return nums.length?Math.round(nums.reduce((a,b)=>a+b,0)/nums.length*10)/10:null}
function aiThemeUsage(items){
 const matrix=new Map(),custom=new Map();let analyzedImages=0,totalSelections=0,matrixSelections=0,customSelections=0;const promptVersions={},models={};
 for(const r of items){
  const selections=aiThemeSelections(r);if(selections.length)analyzedImages++;
  const ai=r.analysis?.ai||{};const pv=ai.promptVersions?.themes||ai.promptVersion||'';if(pv)increment(promptVersions,pv);const model=typeof ai.model==='string'?ai.model:(ai.model?.name||ai.provider?.model||'');if(model)increment(models,model);
  for(const item of selections){
   totalSelections++;const source=item?.source==='custom'?'custom':'matrix';const name=aiThemeName(item);const confidence=Number(item?.confidence);const rank=Math.max(1,Math.min(3,Number(item?.rank)||1));
   const map=source==='custom'?custom:matrix,key=source==='custom'?name:(item?.code||name);let row=map.get(key);if(!row){row={code:source==='matrix'?String(item?.code||''):'',name,selected:0,rank1:0,rank2:0,rank3:0,confidences:[],imageIds:new Set()};map.set(key,row)}
   row.selected++;row[`rank${rank}`]++;if(Number.isFinite(confidence))row.confidences.push(confidence);row.imageIds.add(r.id);if(source==='custom')customSelections++;else matrixSelections++;
  }
 }
 const finish=row=>({code:row.code,name:row.name,selected:row.selected,percentImages:analyzedImages?Math.round(row.imageIds.size/analyzedImages*1000)/10:0,rank1:row.rank1,rank2:row.rank2,rank3:row.rank3,avgConfidence:average(row.confidences)});
 const rows=[...matrix.values()].map(finish).sort((a,b)=>b.selected-a.selected||b.rank1-a.rank1||(b.avgConfidence||0)-(a.avgConfidence||0)||a.name.localeCompare(b.name));
 const customRows=[...custom.values()].map(finish).sort((a,b)=>b.selected-a.selected||b.rank1-a.rank1||a.name.localeCompare(b.name));
 const used=new Set(rows.map(x=>x.name));const allCurrent=[...(window.genreactrixCurrentFusionThemes||[])];const neverSelected=allCurrent.filter(name=>!used.has(name)).sort((a,b)=>a.localeCompare(b));
 return{scopeImages:items.length,analyzedImages,missingThemeResults:Math.max(0,items.length-analyzedImages),totalSelections,matrixSelections,customSelections,customRate:totalSelections?Math.round(customSelections/totalSelections*1000)/10:0,promptVersions,models,rows,customRows,neverSelected};
}
function aiReactionScore(r,name){const a=aiComponents(r).reactions;if(!a)return null;const id=AI_REACTION_ID_BY_NAME[name]||name;if(Array.isArray(a)){const hit=a.find(x=>String(x?.name||x?.reaction||AI_REACTION_NAME_BY_ID[x?.id]||x?.id||'')===name||String(x?.id||'')===id);return Number(hit?.percentage??hit?.confidence??hit?.score??hit?.weight);}const v=a[name]??a[id];return typeof v==='number'?v:Number(v?.percentage??v?.confidence??v?.score??v?.weight)}
function localDateBoundary(value,nextDay=false){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value||''));if(!match)return NaN;const [,y,m,d]=match;return new Date(Number(y),Number(m)-1,Number(d)+(nextDay?1:0),0,0,0,0).getTime()}
async function latestAiScope(all,{component=null}={}){const snap=await window.genreactrixAiAnalysisEngine?.snapshot?.().catch?.(()=>null)||null;const jobs=[...(snap?.jobs||[])].filter(j=>j?.id&&(!component||j?.config?.components?.[component]?.enabled)).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));const job=jobs[0]||null;if(!job)return{records:[],batchIds:[],aiJob:null};const ids=new Set((snap?.items||[]).filter(i=>i.jobId===job.id).map(i=>i.imageId));return{records:all.filter(r=>ids.has(r.id)),batchIds:[],aiJob:job}}
async function resolveScope(scope={type:'all-records'}){
 const all=records(), batches=await window.genreactrixBatchEngine?.all?.()||[];
 switch(scope.type){
  case 'selected':{const ids=new Set(scope.imageIds||[]);return{records:all.filter(r=>ids.has(r.id)),batchIds:[]}}
  case 'latest-ai-job':return latestAiScope(all);
  case 'latest-ai-theme-job':return latestAiScope(all,{component:'themes'});
  case 'session': return {records:all.filter(r=>String(r.createdAt||'')>=SESSION_STARTED),batchIds:[]};
  case 'last-submitted-images':{const n=Math.max(1,Number(scope.count)||100);return{records:[...all].filter(r=>r.workflow?.stage==='batched').sort((a,b)=>String(b.timestamps?.batchedAt||b.updatedAt).localeCompare(String(a.timestamps?.batchedAt||a.updatedAt))).slice(0,n),batchIds:[]}}
  case 'current-batch':{const b=await window.genreactrixBatchEngine?.active?.();return {records:all.filter(r=>b?.imageIds?.includes(r.id)),batchIds:b?[b.id]:[]}}
  case 'most-recent-batch':{const b=[...batches].sort((a,b)=>String(b.submittedAt||b.createdAt).localeCompare(String(a.submittedAt||a.createdAt)))[0];return{records:all.filter(r=>b?.imageIds?.includes(r.id)),batchIds:b?[b.id]:[]}}
  case 'latest-batches':{const n=Math.max(1,Number(scope.count)||1);const chosen=[...batches].filter(b=>b.status==='submitted').sort((a,b)=>String(b.submittedAt).localeCompare(String(a.submittedAt))).slice(0,n);const ids=new Set(chosen.flatMap(b=>b.imageIds||[]));return{records:all.filter(r=>ids.has(r.id)),batchIds:chosen.map(b=>b.id)}}
  case 'date-range':{const start=scope.start?localDateBoundary(scope.start):0,end=scope.end?localDateBoundary(scope.end,true):Infinity;return{records:all.filter(r=>{const t=Date.parse(r.createdAt);return Number.isFinite(t)&&t>=start&&t<end}),batchIds:[]}}
  case 'saved': return {records:all.filter(r=>r.attributes?.saved),batchIds:[]};
  case 'flagged': return {records:all.filter(r=>r.attributes?.flagged),batchIds:[]};
  case 'submitted': return {records:all.filter(r=>r.workflow?.stage==='batched'),batchIds:batches.filter(b=>b.status==='submitted').map(b=>b.id)};
  default:return{records:all,batchIds:[]};
 }
}
function withOp(match,c){return c?.op==='not'?!Boolean(match):Boolean(match)}
function condition(record,c){
 const value=String(c.value||'').trim();
 switch(c.field){
  case 'director-reaction':return withOp(directorReactions(record).includes(value),c);
  case 'director-reaction-exact':{const wanted=value.split(',').map(x=>x.trim()).filter(Boolean).sort();const actual=[...directorReactions(record)].sort();return withOp(JSON.stringify(wanted)===JSON.stringify(actual),c)}
  case 'director-theme-exact':{const wanted=value.split(',').map(x=>x.trim()).filter(Boolean).sort();const actual=[...directorThemes(record)].sort();return withOp(JSON.stringify(wanted)===JSON.stringify(actual),c)}
  case 'director-theme':return withOp(directorThemes(record).includes(value),c);
  case 'saved':return withOp(Boolean(record.attributes?.saved),c);
  case 'flagged':return withOp(Boolean(record.attributes?.flagged),c);
  case 'source-type':return withOp(String(record.source?.type||'unknown')===value,c);
  case 'ai-reaction-min':{const score=aiReactionScore(record,c.name);return withOp(Number.isFinite(score)&&score>=Number(c.value),c)}
  case 'ai-reaction-max':{const score=aiReactionScore(record,c.name);return withOp(Number.isFinite(score)&&score<=Number(c.value),c)}
  case 'ai-agreement-min':{const score=recordAgreement(record);return withOp(Number.isFinite(score)&&score>=Number(c.value),c)}
  case 'ai-agreement-max':{const score=recordAgreement(record);return withOp(Number.isFinite(score)&&score<=Number(c.value),c)}
  case 'batch':return withOp((record.batchIds||[]).includes(value),c);
  case 'ai-disagreement':{const rs=directorReactions(record);const mismatch=rs.some(name=>{const score=aiReactionScore(record,name);return Number.isFinite(score)&&score<50})||aiReactionNames(record).some(name=>{const score=aiReactionScore(record,name);return Number.isFinite(score)&&score>=70&&!rs.includes(name)});return withOp(mismatch,c)}
  default:return true;
 }
}
function applyFilters(items,definition={logic:'and',conditions:[]}){const cs=(definition.conditions||[]).filter(c=>c.field);if(!cs.length)return items;return items.filter(r=>definition.logic==='or'?cs.some(c=>condition(r,c)):cs.every(c=>condition(r,c)))}
function increment(map,key,n=1){if(key)map[key]=(map[key]||0)+n}
function recordAgreement(record){const rs=directorReactions(record);const names=new Set([...rs,...aiReactionNames(record)]);let comparable=0,agree=0;for(const name of names){const score=aiReactionScore(record,name);if(!Number.isFinite(score))continue;comparable++;if((score>=50)===rs.includes(name))agree++}return comparable?Math.round(agree/comparable*1000)/10:null}
function rowFor(record,fields=[]){const d=record.analysis?.director||{},ai=record.analysis?.ai||{};const row={};for(const f of fields){if(f==='imageId')row.imageId=record.id;if(f==='filename')row.filename=record.source?.filename||record.source?.url||record.id;if(f==='batch')row.batch=(record.batchIds||[]).join(', ');if(f==='directorReactions')row.directorReactions=directorReactions(record).join(' + ');if(f==='directorThemes')row.directorThemes=directorThemes(record).join(' + ');if(f==='primFusion')row.primFusion=d.primFusion?.label||d.primFusion?.id||'';if(f==='aiAgreement')row.aiAgreement=recordAgreement(record);if(f==='dates'){row.importedAt=record.createdAt||'';row.classifiedAt=d.timestamp||record.timestamps?.directorAt||''}if(f==='provider'){row.provider=ai.provider||'';row.model=ai.model||'';row.promptVersion=ai.promptVersion||''}if(f==='saved')row.saved=Boolean(record.attributes?.saved);if(f==='flagged')row.flagged=Boolean(record.attributes?.flagged)}return row}
function groupKey(record,groupBy){switch(groupBy){case'directorReaction':return directorReactions(record);case'directorTheme':return directorThemes(record);case'primFusion':return record.analysis?.director?.primFusion?.label||record.analysis?.director?.primFusion?.id||'None';case'batch':return record.batchIds||['Unassigned'];case'saved':return record.attributes?.saved?'Saved':'Not saved';case'flagged':return record.attributes?.flagged?'Flagged':'Not flagged';case'aiAgreement':{const v=recordAgreement(record);return v==null?'No comparison':`${Math.round(v/10)*10}%`}case'source':return record.source?.type||'unknown';case'classifiedDate':return String(record.analysis?.director?.timestamp||record.timestamps?.directorAt||'Unclassified').slice(0,10);case'workflowStage':return record.workflow?.stage||'unknown';default:return'All'}}
function buildGroups(items,groupBy){if(!groupBy||groupBy==='none')return{};const out={};for(const r of items){const keys=groupKey(r,groupBy),list=Array.isArray(keys)?keys:[keys];for(const key of list){const k=String(key||'None');(out[k]||(out[k]=[])).push(r.id)}}return out}
function statisticsFor(items,requested=[]){const total=items.length,complete=items.filter(r=>r.analysis?.director?.completion==='complete'||r.workflow?.stage==='director-complete'||r.workflow?.stage==='batched').length;const agreements=items.map(recordAgreement).filter(Number.isFinite).sort((a,b)=>a-b);const stats={};if(requested.includes('count'))stats.count=total;if(requested.includes('percentage'))stats.percentOfPopulation=100;if(requested.includes('average'))stats.averageAgreement=agreements.length?Math.round(agreements.reduce((a,b)=>a+b,0)/agreements.length*10)/10:null;if(requested.includes('median'))stats.medianAgreement=agreements.length?agreements[Math.floor(agreements.length/2)]:null;if(requested.includes('agreementRate'))stats.agreementRate=agreements.length?Math.round(agreements.reduce((a,b)=>a+b,0)/agreements.length*10)/10:null;if(requested.includes('completionRate'))stats.completionRate=total?Math.round(complete/total*1000)/10:0;return stats}
function sortRows(rows,sortBy='imageId',direction='asc'){const sign=direction==='desc'?-1:1;return [...rows].sort((a,b)=>String(a[sortBy]??'').localeCompare(String(b[sortBy]??''))*sign)}
function aggregate(items,modules=['summary','reactions','themes','ai-themes','primfusion','agreement','sources','workflow']){
 const result={};
 if(modules.includes('summary'))result.summary={images:items.length,saved:items.filter(r=>r.attributes?.saved).length,flagged:items.filter(r=>r.attributes?.flagged).length,aiCovered:items.filter(r=>r.analysis?.ai&&Object.keys(r.analysis.ai).length).length,directorCovered:items.filter(r=>r.analysis?.director).length,incomplete:items.filter(r=>!r.analysis?.director).length};
 if(modules.includes('reactions')){const counts={},combos={};for(const r of items){const rs=directorReactions(r);rs.forEach(x=>increment(counts,x));increment(combos,[...rs].sort().join(' + '));}result.reactions={counts,combinations:combos};}
 if(modules.includes('themes')){const counts={},combos={};for(const r of items){const ts=directorThemes(r);ts.forEach(x=>increment(counts,x));increment(combos,[...ts].sort().join(' + '));}result.themes={counts,combinations:combos};}
 if(modules.includes('ai-themes'))result.aiThemes=aiThemeUsage(items);
 if(modules.includes('reaction-info'))result.reactionInfo=items.map(r=>({imageId:r.id,info:clone(aiComponents(r).reactionReasons||aiComponents(r).reactionDiagnostics||null)})).filter(row=>row.info);
 if(modules.includes('theme-info'))result.themeInfo=items.map(r=>({imageId:r.id,info:clone(aiComponents(r).genreReasons||null)})).filter(row=>row.info);
 if(modules.includes('primfusion')){const counts={};for(const r of items){const d=r.analysis?.director||{};const key=d.primFusion?.label||d.primFusion?.id||(directorReactions(r).length>=2?directorReactions(r).join(' × '):'');increment(counts,key)}result.primfusion={counts};}
 if(modules.includes('agreement')){const reactions=new Set(items.flatMap(directorReactions));const byReaction={};for(const name of reactions){let comparable=0,agree=0,highAiDirectorNo=0;for(const r of items){const score=aiReactionScore(r,name);if(!Number.isFinite(score))continue;comparable++;const selected=directorReactions(r).includes(name),aiYes=score>=50;if(selected===aiYes)agree++;if(!selected&&score>=70)highAiDirectorNo++;}byReaction[name]={comparable,agree,agreementRate:comparable?Math.round(agree/comparable*1000)/10:null,highAiDirectorNo};}result.agreement={byReaction};}
 if(modules.includes('sources')){const counts={};items.forEach(r=>increment(counts,r.source?.type||'unknown'));result.sources={counts};}
 if(modules.includes('workflow'))result.workflow={stages:items.reduce((a,r)=>(increment(a,r.workflow?.stage||'unknown'),a),{}),failed:items.filter(r=>r.attributes?.failed).length,recycled:items.filter(r=>r.attributes?.inRecycleBin).length,missingSource:items.filter(r=>r.storage?.missingReference).length};
 return result;
}
const HISTORY_FILTER_FIELDS=new Set(['reanalyzed','director-revised','undo-redo','restored']);
async function historyMatch(record,c){const h=window.genreactrixHistoryEngine;if(!h)return withOp(false,c);const timeline=await h.timeline(record.id);let match=true;switch(c.field){case 'reanalyzed':match=timeline.filter(e=>e.eventType==='ai-analysis').length>1;break;case 'director-revised':match=timeline.filter(e=>e.eventType.startsWith('director-')).length>1;break;case 'undo-redo':match=timeline.some(e=>/undo|redo/.test(e.eventType));break;case 'restored':match=timeline.some(e=>e.eventType==='recycle-restored');break;default:match=true;}return withOp(match,c)}
async function filterMatch(record,c){return HISTORY_FILTER_FIELDS.has(c.field)?historyMatch(record,c):condition(record,c)}
async function applyAllFilters(items,definition={logic:'and',conditions:[]}){const cs=(definition.conditions||[]).filter(c=>c.field);if(!cs.length)return items;const useOr=definition.logic==='or',out=[];for(const record of items){if(useOr){let matched=false;for(const c of cs){if(await filterMatch(record,c)){matched=true;break}}if(matched)out.push(record)}else{let matched=true;for(const c of cs){if(!(await filterMatch(record,c))){matched=false;break}}if(matched)out.push(record)}}return out}
async function generate(definition={}){const qJob=await window.genreactrixQueueEngine?.createJob?.({type:'report',ownerEngine:'reports',label:definition.title||'Generate report',state:'running',total:1,batchId:definition.batchId||null,message:'Building report'});let qItemId=null;if(qJob){qItemId=`queue_report_${qJob.id}`;await window.genreactrixQueueEngine.addItems(qJob.id,[{id:qItemId,type:'report',state:'processing'}])}try{const scope=definition.scope||{type:'all-records'};const resolved=await resolveScope(scope);const matched=await applyAllFilters(resolved.records,definition.filters||{});const results=aggregate(matched,definition.modules);const rows=sortRows(matched.map(r=>rowFor(r,definition.fields||[])),definition.sortBy,definition.sortDirection);results.rows=rows;results.groups=buildGroups(matched,definition.groupBy);results.statistics=statisticsFor(matched,definition.statistics||[]);const report={id:uid('report'),schemaVersion:1,type:definition.type||'custom',title:definition.title||'Custom Report',createdAt:now(),scope:clone(scope),filters:clone(definition.filters||{logic:'and',conditions:[]}),description:definition.description||'',fields:clone(definition.fields||[]),groupBy:definition.groupBy||'none',sortBy:definition.sortBy||'imageId',sortDirection:definition.sortDirection||'asc',statistics:clone(definition.statistics||[]),outputFormat:definition.outputFormat||'json',modules:definition.modules||['summary','reactions','themes','ai-themes','primfusion','agreement','sources','workflow'],batchId:definition.batchId||resolved.batchIds[0]||null,batchIds:resolved.batchIds,imageIds:matched.map(r=>r.id),results,counts:{total:matched.length,...(results.summary||{})},submissionVersion:definition.submissionVersion||null,warnings:[],generatedBy:definition.generatedBy||'director',automatic:Boolean(definition.automatic),dataSources:{imageRecordSchema:1,reportEngine:1}};await put(REPORTS,report);if(qItemId)await window.genreactrixQueueEngine.setItemState(qItemId,'complete');if(qJob)await window.genreactrixQueueEngine.setJobState(qJob.id,'completed','Report ready');window.dispatchEvent(new CustomEvent('genreactrix:report',{detail:{report}}));window.genreactrixNotificationsEngine?.create?.({severity:'info',title:'Report ready',message:`${report.title} · ${report.imageIds.length} images`,ownerEngine:'reports',relatedReportId:report.id,actionTarget:'reports',actionLabel:'Open',dedupeKey:`report:${report.id}`,resolved:true});render().catch(()=>{});return clone(report)}catch(error){if(qItemId)await window.genreactrixQueueEngine.setItemState(qItemId,'failed',{error:String(error.message||error)});if(qJob)await window.genreactrixQueueEngine.setJobState(qJob.id,'failed',String(error.message||error));throw error}}
async function generateStandardBatchReport(batchId,submissionVersion=1){const b=(await window.genreactrixBatchEngine?.all?.()||[]).find(x=>x.id===batchId);if(!b)throw new Error('Batch not found');const acceptedIds=(b.imageIds||[]).filter(id=>!records().find(r=>r.id===id)?.attributes?.rejected);return generate({type:'standard-batch',title:`${b.name} · Submission ${submissionVersion}`,scope:{type:'selected',imageIds:acceptedIds},batchId,modules:['summary','reactions','themes','primfusion','agreement','sources','workflow'],automatic:true,generatedBy:'batch-engine',submissionVersion})}
const originalResolve=resolveScope;
resolveScope=async function(scope={}){if(scope.type==='selected'){const all=records(),ids=new Set(scope.imageIds||[]);return{records:all.filter(r=>ids.has(r.id)),batchIds:[]}}return originalResolve(scope)};
async function allReports(){return (await getAll(REPORTS)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
async function savePreset(input){const preset={id:input.id||uid('preset'),schemaVersion:1,name:input.name||'Report preset',createdAt:input.createdAt||now(),updatedAt:now(),definition:clone(input.definition||input)};await put(PRESETS,preset);return preset}
async function presets(){return getAll(PRESETS)}
async function runPreset(id){const p=await get(PRESETS,id);if(!p)throw new Error('Preset not found');return generate({...p.definition,title:p.name})}
function csvCell(value){return `"${String(value??'').replaceAll('"','""')}"`}
function csv(report){
 const imageRows=Array.isArray(report.results?.rows)?report.results.rows.filter(row=>row&&typeof row==='object'&&Object.keys(row).length):[];
 if(imageRows.length){const columns=[...new Set(imageRows.flatMap(row=>Object.keys(row)))];return [columns,...imageRows.map(row=>columns.map(key=>row[key]??''))].map(row=>row.map(csvCell).join(',')).join('\n')}
 const rows=[['module','key','value']];for(const [module,data] of Object.entries(report.results||{})){if(module==='rows')continue;for(const [key,val] of Object.entries(data||{})){if(val&&typeof val==='object'&&!Array.isArray(val)){for(const [sub,v] of Object.entries(val))rows.push([module,`${key}.${sub}`,typeof v==='object'?JSON.stringify(v):v]);}else rows.push([module,key,val&&typeof val==='object'?JSON.stringify(val):val])}}return rows.map(row=>row.map(csvCell).join(',')).join('\n')}

function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},100)}
async function exportJson(id){const r=await get(REPORTS,id);if(r)download(`${r.title.replace(/[^a-z0-9]+/gi,'_')}.json`,JSON.stringify(r,null,2),'application/json')}
async function exportCsv(id){const r=await get(REPORTS,id);if(r)download(`${r.title.replace(/[^a-z0-9]+/gi,'_')}.csv`,csv(r),'text/csv')}
function reportHtml(r){const sections=Object.entries(r.results||{}).map(([k,v])=>`<section><h2>${k}</h2><pre>${escapeHtml(JSON.stringify(v,null,2))}</pre></section>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(r.title)}</title><style>body{font:16px system-ui;max-width:900px;margin:auto;padding:30px}pre{white-space:pre-wrap;background:#f5f5f5;padding:12px}</style></head><body><h1>${escapeHtml(r.title)}</h1><p>${new Date(r.createdAt).toLocaleString()} · ${r.imageIds.length} images</p>${sections}</body></html>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function printReport(id){const r=await get(REPORTS,id);if(!r)return;const w=open('','_blank');w.document.write(reportHtml(r));w.document.close();w.print()}
function formDefinition(){const scopeType=document.getElementById('reportScope').value;const count=Number(document.getElementById('reportScopeCount').value)||1;const conditions=[];document.querySelectorAll('#reportConditions .report-condition').forEach(row=>{const field=row.querySelector('[data-role=field]').value;if(!field)return;conditions.push({field,op:row.querySelector('[data-role=op]').value,value:row.querySelector('[data-role=value]').value,name:row.querySelector('[data-role=name]')?.value||''})});return{title:document.getElementById('reportTitle').value||'Custom Report',description:document.getElementById('reportDescription')?.value||'',scope:{type:scopeType,count,start:document.getElementById('reportStart').value,end:document.getElementById('reportEnd').value},filters:{logic:document.getElementById('reportLogic').value,conditions},modules:[...document.querySelectorAll('[data-report-module]:checked')].map(x=>x.value),fields:((rows)=>rows.length?rows:[...DEFAULT_ROW_FIELDS])([...document.querySelectorAll('[data-report-field]:checked')].map(x=>x.value)),statistics:[...document.querySelectorAll('[data-report-stat]:checked')].map(x=>x.value),groupBy:document.getElementById('reportGroupBy')?.value||'none',sortBy:document.getElementById('reportSortBy')?.value||'imageId',sortDirection:document.getElementById('reportSortDirection')?.value||'asc',outputFormat:document.getElementById('reportOutputFormat')?.value||'json'}}
function addCondition(initial={}){const row=document.createElement('div');row.className='report-condition';row.innerHTML=`<select data-role="field"><option value="">Choose filter</option><option value="director-reaction">Director reaction</option><option value="director-reaction-exact">Exact Director reaction set</option><option value="director-theme">Director theme</option><option value="director-theme-exact">Exact Director theme set</option><option value="ai-reaction-min">AI reaction minimum %</option><option value="ai-reaction-max">AI reaction maximum %</option><option value="ai-agreement-min">AI–Director agreement minimum %</option><option value="ai-agreement-max">AI–Director agreement maximum %</option><option value="source-type">Source type</option><option value="batch">Batch ID</option><option value="saved">Saved</option><option value="flagged">Flagged</option><option value="reanalyzed">AI reanalyzed</option><option value="director-revised">Director revised</option><option value="undo-redo">Undo/redo used</option><option value="restored">Restored from recycle</option></select><input data-role="name" placeholder="Reaction (AI filters)"><select data-role="op"><option value="has">Has / equals</option><option value="not">Does not have</option></select><input data-role="value" placeholder="Value"><button type="button" data-remove>×</button>`;for(const [k,v] of Object.entries(initial)){const e=row.querySelector(`[data-role=${k}]`);if(e)e.value=v}row.querySelector('[data-remove]').onclick=()=>row.remove();document.getElementById('reportConditions').appendChild(row)}
async function render(){const all=await allReports(),ps=await presets();const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=String(v)};set('portraitReportCount',all.length);set('portraitLastReport',all[0]?.title||'None');const list=document.getElementById('reportHistory');if(list)list.innerHTML=all.slice(0,30).map(r=>`<article class="report-row" data-report-id="${r.id}"><button type="button" data-open-report="${r.id}"><span>${escapeHtml(r.title)}<small>${new Date(r.createdAt).toLocaleString()}</small></span><strong>${r.imageIds.length}</strong></button><div><button type="button" data-json="${r.id}">JSON</button><button type="button" data-csv="${r.id}">CSV</button><button type="button" data-print="${r.id}">Print</button></div></article>`).join('')||'<p>No reports yet.</p>';const preset=document.getElementById('reportPresets');if(preset)preset.innerHTML=ps.map(p=>`<button type="button" data-run-preset="${p.id}">${escapeHtml(p.name)}</button>`).join('')||'<span>No presets yet.</span>'}
function renderAiThemeUsage(data){if(!data)return'';const rows=data.rows||[],custom=data.customRows||[],top=rows[0];const rowHtml=rows.map(x=>`<tr><td><strong>${escapeHtml(x.name)}</strong>${x.code?`<small>${escapeHtml(x.code)}</small>`:''}</td><td>${x.selected}</td><td>${x.percentImages}%</td><td>${x.rank1}</td><td>${x.rank2}</td><td>${x.rank3}</td><td>${x.avgConfidence??'—'}</td></tr>`).join('');const customHtml=custom.length?`<h4>Custom proposals</h4><table class="ai-theme-report-table"><thead><tr><th>Custom</th><th>Selected</th><th>% images</th><th>#1</th><th>#2</th><th>#3</th><th>Avg conf.</th></tr></thead><tbody>${custom.map(x=>`<tr><td><strong>${escapeHtml(x.name)}</strong></td><td>${x.selected}</td><td>${x.percentImages}%</td><td>${x.rank1}</td><td>${x.rank2}</td><td>${x.rank3}</td><td>${x.avgConfidence??'—'}</td></tr>`).join('')}</tbody></table>`:'';const never=(data.neverSelected||[]);return `<div class="ai-theme-report-kpis"><div><strong>${data.scopeImages}</strong><span>Images in scope</span></div><div><strong>${data.analyzedImages}</strong><span>Theme results</span></div><div><strong>${data.missingThemeResults}</strong><span>Missing theme results</span></div><div><strong>${data.customRate}%</strong><span>Custom selection rate</span></div></div>${top?`<p class="ai-theme-report-lead"><strong>Most selected:</strong> ${escapeHtml(top.name)} · ${top.selected} selections · ${top.percentImages}% of analyzed images</p>`:'<p>No AI Theme selections in this scope.</p>'}<div class="ai-theme-report-scroll"><table class="ai-theme-report-table"><thead><tr><th>Theme</th><th>Selected</th><th>% images</th><th>#1</th><th>#2</th><th>#3</th><th>Avg conf.</th></tr></thead><tbody>${rowHtml}</tbody></table></div>${customHtml}<details class="ai-theme-report-never"><summary>Never selected (${never.length})</summary><p>${never.map(escapeHtml).join(', ')||'None'}</p></details><details><summary>Run metadata</summary><pre>${escapeHtml(JSON.stringify({promptVersions:data.promptVersions,models:data.models,totalSelections:data.totalSelections,matrixSelections:data.matrixSelections,customSelections:data.customSelections},null,2))}</pre></details>`}
async function openReport(id){const r=await get(REPORTS,id);if(!r)return;const raw=document.getElementById('reportOutput'),visual=document.getElementById('reportVisualOutput');raw.textContent=JSON.stringify(r.results,null,2);raw.dataset.reportId=id;document.getElementById('reportOutputTitle').textContent=r.title;if(r.results?.aiThemes){visual.innerHTML=renderAiThemeUsage(r.results.aiThemes);visual.hidden=false;raw.hidden=true}else{visual.innerHTML='';visual.hidden=true;raw.hidden=false}}
function openConsole(){document.getElementById('reportsDialog')?.showModal();render()}
function initUi(){document.getElementById('reportsClose')?.addEventListener('click',()=>document.getElementById('reportsDialog')?.close());document.getElementById('reportAddCondition')?.addEventListener('click',()=>addCondition());document.getElementById('reportRun')?.addEventListener('click',async()=>{const r=await generate(formDefinition());openReport(r.id)});document.getElementById('reportAiThemeUsage')?.addEventListener('click',async()=>{const r=await generate({type:'ai-theme-usage',title:'AI Theme Usage · Latest AI Run',scope:{type:'latest-ai-theme-job'},filters:{logic:'and',conditions:[]},modules:['summary','ai-themes'],fields:[],statistics:['count'],generatedBy:'research-reports'});openReport(r.id)});document.getElementById('reportSavePreset')?.addEventListener('click',async()=>{const name=prompt('Preset name',document.getElementById('reportTitle').value||'Report preset');if(name){await savePreset({name,definition:formDefinition()});render()}});document.getElementById('reportHistory')?.addEventListener('click',e=>{const id=e.target.closest('[data-open-report]')?.dataset.openReport;if(id)openReport(id);const j=e.target.dataset.json,c=e.target.dataset.csv,p=e.target.dataset.print;if(j)exportJson(j);if(c)exportCsv(c);if(p)printReport(p)});document.getElementById('reportPresets')?.addEventListener('click',async e=>{const id=e.target.dataset.runPreset;if(id){const r=await runPreset(id);openReport(r.id)}});document.getElementById('reportExportCurrentJson')?.addEventListener('click',()=>{const id=document.getElementById('reportOutput').dataset.reportId;if(id)exportJson(id)});document.getElementById('reportExportCurrentCsv')?.addEventListener('click',()=>{const id=document.getElementById('reportOutput').dataset.reportId;if(id)exportCsv(id)});addCondition()}
async function ingestBatchRecord(old,{generatedBy='batch-engine'}={}){if(!old?.id)return null;const existing=await get(REPORTS,old.id);if(existing)return existing;const report={id:old.id,schemaVersion:1,type:'standard-batch',title:`${old.batchName||'Batch'} · Submission ${old.submissionVersion||1}`,createdAt:old.createdAt||now(),scope:{type:'selected',imageIds:old.imageIds||[]},filters:{logic:'and',conditions:[]},modules:['summary','reactions','themes','primfusion','sources'],batchId:old.batchId||null,batchIds:old.batchId?[old.batchId]:[],imageIds:old.imageIds||[],results:{summary:{...(old.counts||{}),aiCovered:old.aiCoverage||0},reactions:{counts:old.reactionTotals||{}},themes:{counts:old.themeTotals||{}},primfusion:{counts:old.primFusionTotals||{}},sources:{counts:old.sourceSummary||{}}},warnings:[],generatedBy,automatic:true,dataSources:{batchRecord:true}};await put(REPORTS,report);window.dispatchEvent(new CustomEvent('genreactrix:report',{detail:{report:clone(report)}}));render().catch(()=>{});return clone(report)}
async function migrateLegacy(){try{const db=await new Promise((res,rej)=>{const r=indexedDB.open('genreactrix-batch-engine-v1');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(!db.objectStoreNames.contains('reports')){db.close();return}const legacy=await new Promise((res,rej)=>{const tx=db.transaction('reports');const q=tx.objectStore('reports').getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);tx.oncomplete=()=>db.close()});for(const old of legacy)await ingestBatchRecord(old,{generatedBy:'migration'})}catch(e){console.warn('Legacy report migration skipped',e)}}
async function integrity(){const rs=await allReports(),issues=[],ids=new Set();const recordIds=new Set(records().map(r=>r.id));for(const r of rs){if(ids.has(r.id))issues.push({type:'duplicate-report-id',reportId:r.id});ids.add(r.id);for(const id of r.imageIds||[])if(!recordIds.has(id))issues.push({type:'missing-image-record',reportId:r.id,imageId:id});if((r.results?.summary?.images??r.imageIds.length)!==r.imageIds.length)issues.push({type:'count-mismatch',reportId:r.id})}return{checkedAt:now(),reportCount:rs.length,issueCount:issues.length,issues}}
async function contextual(imageId,type){const record=records().find(r=>r.id===imageId);if(!record)throw new Error('Image record not found');let def={title:'Context report',scope:{type:'all-records'},filters:{logic:'and',conditions:[]},modules:['summary','reactions','themes','primfusion','agreement'],fields:['imageId','filename','batch','directorReactions','directorThemes','primFusion','aiAgreement']};if(type==='same-reactions')def.filters.conditions.push({field:'director-reaction-exact',op:'has',value:directorReactions(record).join(',')});if(type==='same-themes')def.filters.conditions.push({field:'director-theme-exact',op:'has',value:directorThemes(record).join(',')});if(type==='same-batch')def.filters.conditions.push({field:'batch',op:'has',value:(record.batchIds||[])[0]||''});if(type==='ai-disagreement')def.filters.conditions.push({field:'ai-disagreement',op:'has',value:true});def.title=`${type.replaceAll('-',' ')} · ${imageId}`;return generate(def)}
const engine={generate,generateStandardBatchReport,ingestBatchRecord,contextual,all:allReports,get:id=>get(REPORTS,id),savePreset,presets,runPreset,openConsole,exportJson,exportCsv,printReport,integrity};window.genreactrixReportsEngine=engine;window.addEventListener('DOMContentLoaded',async()=>{initUi();await migrateLegacy();render()});window.addEventListener('genreactrix:batch',()=>render());window.addEventListener('genreactrix:image-record',()=>render());
})();
