(()=>{
'use strict';
const DB='genreactrix-reports-engine-v1', REPORTS='reports', PRESETS='presets', VERSION=1;
const now=()=>new Date().toISOString();
const SESSION_STARTED=now();
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const clone=v=>v==null?v:structuredClone(v);
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(REPORTS)){const s=db.createObjectStore(REPORTS,{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('type','type');s.createIndex('batchId','batchId');}if(!db.objectStoreNames.contains(PRESETS)){const s=db.createObjectStore(PRESETS,{keyPath:'id'});s.createIndex('name','name');}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function tx(name,mode='readonly'){const db=await openDb();return db.transaction(name,mode).objectStore(name)}
async function getAll(name){const s=await tx(name);return new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function get(name,id){const s=await tx(name);return new Promise((res,rej)=>{const r=s.get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function put(name,v){const s=await tx(name,'readwrite');return new Promise((res,rej)=>{const r=s.put(v);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})}
function records(){return window.genreactrixImageRecordEngine?.all?.()||[]}
function directorReactions(r){return r.analysis?.director?.selectedReactions||[]}
function directorThemes(r){return (r.analysis?.director?.themes||[]).filter(Boolean).map(x=>typeof x==='string'?x:(x.label||x.id||'Unknown'))}
function aiComponents(r){return r.analysis?.ai?.components||r.analysis?.ai||{}}
function aiReactionScore(r,name){const a=aiComponents(r).reactions; if(!a)return null; if(Array.isArray(a)){const hit=a.find(x=>(x.name||x.id||x.reaction)===name);return Number(hit?.percentage??hit?.confidence??hit?.score);} const v=a[name];return typeof v==='number'?v:Number(v?.percentage??v?.confidence??v?.score)}
async function resolveScope(scope={type:'all-records'}){
 const all=records(), batches=await window.genreactrixBatchEngine?.all?.()||[];
 switch(scope.type){
  case 'session': return {records:all.filter(r=>String(r.createdAt||'')>=SESSION_STARTED),batchIds:[]};
  case 'last-submitted-images':{const n=Math.max(1,Number(scope.count)||100);return{records:[...all].filter(r=>r.workflow?.stage==='batched').sort((a,b)=>String(b.timestamps?.batchedAt||b.updatedAt).localeCompare(String(a.timestamps?.batchedAt||a.updatedAt))).slice(0,n),batchIds:[]}}
  case 'current-batch':{const b=await window.genreactrixBatchEngine?.active?.();return {records:all.filter(r=>b?.imageIds?.includes(r.id)),batchIds:b?[b.id]:[]}}
  case 'most-recent-batch':{const b=[...batches].sort((a,b)=>String(b.submittedAt||b.createdAt).localeCompare(String(a.submittedAt||a.createdAt)))[0];return{records:all.filter(r=>b?.imageIds?.includes(r.id)),batchIds:b?[b.id]:[]}}
  case 'latest-batches':{const n=Math.max(1,Number(scope.count)||1);const chosen=[...batches].filter(b=>b.status==='submitted').sort((a,b)=>String(b.submittedAt).localeCompare(String(a.submittedAt))).slice(0,n);const ids=new Set(chosen.flatMap(b=>b.imageIds||[]));return{records:all.filter(r=>ids.has(r.id)),batchIds:chosen.map(b=>b.id)}}
  case 'date-range':{const start=scope.start?Date.parse(scope.start):0,end=scope.end?Date.parse(scope.end)+86400000:Infinity;return{records:all.filter(r=>{const t=Date.parse(r.createdAt);return t>=start&&t<end}),batchIds:[]}}
  case 'saved': return {records:all.filter(r=>r.attributes?.saved),batchIds:[]};
  case 'flagged': return {records:all.filter(r=>r.attributes?.flagged),batchIds:[]};
  case 'submitted': return {records:all.filter(r=>r.workflow?.stage==='batched'),batchIds:batches.filter(b=>b.status==='submitted').map(b=>b.id)};
  default:return{records:all,batchIds:[]};
 }
}
function condition(record,c){
 const value=String(c.value||'').trim();
 switch(c.field){
  case 'director-reaction':{const has=directorReactions(record).includes(value);return c.op==='not'? !has:has}
  case 'director-reaction-exact':{const wanted=value.split(',').map(x=>x.trim()).filter(Boolean).sort();const actual=[...directorReactions(record)].sort();return JSON.stringify(wanted)===JSON.stringify(actual)}
  case 'director-theme-exact':{const wanted=value.split(',').map(x=>x.trim()).filter(Boolean).sort();const actual=[...directorThemes(record)].sort();return JSON.stringify(wanted)===JSON.stringify(actual)}
  case 'director-theme':{const has=directorThemes(record).includes(value);return c.op==='not'?!has:has}
  case 'saved':return Boolean(record.attributes?.saved)===Boolean(c.value);
  case 'flagged':return Boolean(record.attributes?.flagged)===Boolean(c.value);
  case 'source-type':return String(record.source?.type||'unknown')===value;
  case 'ai-reaction-min':{const score=aiReactionScore(record,c.name);return Number.isFinite(score)&&score>=Number(c.value)}
  case 'ai-reaction-max':{const score=aiReactionScore(record,c.name);return Number.isFinite(score)&&score<=Number(c.value)}
  case 'batch':return (record.batchIds||[]).includes(value);
  default:return true;
 }
}
function applyFilters(items,definition={logic:'and',conditions:[]}){const cs=(definition.conditions||[]).filter(c=>c.field);if(!cs.length)return items;return items.filter(r=>definition.logic==='or'?cs.some(c=>condition(r,c)):cs.every(c=>condition(r,c)))}
function increment(map,key,n=1){if(key)map[key]=(map[key]||0)+n}
function aggregate(items,modules=['summary','reactions','themes','primfusion','agreement','sources','workflow']){
 const result={};
 if(modules.includes('summary'))result.summary={images:items.length,saved:items.filter(r=>r.attributes?.saved).length,flagged:items.filter(r=>r.attributes?.flagged).length,aiCovered:items.filter(r=>r.analysis?.ai&&Object.keys(r.analysis.ai).length).length,directorCovered:items.filter(r=>r.analysis?.director).length,incomplete:items.filter(r=>!r.analysis?.director).length};
 if(modules.includes('reactions')){const counts={},combos={};for(const r of items){const rs=directorReactions(r);rs.forEach(x=>increment(counts,x));increment(combos,[...rs].sort().join(' + '));}result.reactions={counts,combinations:combos};}
 if(modules.includes('themes')){const counts={},combos={};for(const r of items){const ts=directorThemes(r);ts.forEach(x=>increment(counts,x));increment(combos,[...ts].sort().join(' + '));}result.themes={counts,combinations:combos};}
 if(modules.includes('primfusion')){const counts={};for(const r of items){const d=r.analysis?.director||{};const key=d.primFusion?.label||d.primFusion?.id||(directorReactions(r).length>=2?directorReactions(r).join(' × '):'');increment(counts,key)}result.primfusion={counts};}
 if(modules.includes('agreement')){const reactions=new Set(items.flatMap(directorReactions));const byReaction={};for(const name of reactions){let comparable=0,agree=0,highAiDirectorNo=0;for(const r of items){const score=aiReactionScore(r,name);if(!Number.isFinite(score))continue;comparable++;const selected=directorReactions(r).includes(name),aiYes=score>=50;if(selected===aiYes)agree++;if(!selected&&score>=70)highAiDirectorNo++;}byReaction[name]={comparable,agree,agreementRate:comparable?Math.round(agree/comparable*1000)/10:null,highAiDirectorNo};}result.agreement={byReaction};}
 if(modules.includes('sources')){const counts={};items.forEach(r=>increment(counts,r.source?.type||'unknown'));result.sources={counts};}
 if(modules.includes('workflow'))result.workflow={stages:items.reduce((a,r)=>(increment(a,r.workflow?.stage||'unknown'),a),{}),failed:items.filter(r=>r.attributes?.failed).length,recycled:items.filter(r=>r.attributes?.inRecycleBin).length,missingSource:items.filter(r=>r.storage?.missingReference).length};
 return result;
}
async function historyMatch(record,c){const h=window.genreactrixHistoryEngine;if(!h)return false;const timeline=await h.timeline(record.id);switch(c.field){case 'reanalyzed':return timeline.filter(e=>e.eventType==='ai-analysis').length>1;case 'director-revised':return timeline.filter(e=>e.eventType.startsWith('director-')).length>1;case 'undo-redo':return timeline.some(e=>/undo|redo/.test(e.eventType));case 'restored':return timeline.some(e=>e.eventType==='recycle-restored');default:return true}}
async function applyAllFilters(items,definition={logic:'and',conditions:[]}){const historyFields=new Set(['reanalyzed','director-revised','undo-redo','restored']);const normal={...definition,conditions:(definition.conditions||[]).filter(c=>!historyFields.has(c.field))};let matched=applyFilters(items,normal);const hc=(definition.conditions||[]).filter(c=>historyFields.has(c.field));if(!hc.length)return matched;const out=[];for(const r of matched){const values=[];for(const c of hc)values.push(await historyMatch(r,c));if(definition.logic==='or'?values.some(Boolean):values.every(Boolean))out.push(r)}return out}
async function generate(definition={}){const qJob=await window.genreactrixQueueEngine?.createJob?.({type:'report',ownerEngine:'reports',label:definition.title||'Generate report',state:'running',total:1,batchId:definition.batchId||null,message:'Building report'});let qItemId=null;if(qJob){qItemId=`queue_report_${qJob.id}`;await window.genreactrixQueueEngine.addItems(qJob.id,[{id:qItemId,type:'report',state:'processing'}])}try{const scope=definition.scope||{type:'all-records'};const resolved=await resolveScope(scope);const matched=await applyAllFilters(resolved.records,definition.filters||{});const results=aggregate(matched,definition.modules);const report={id:uid('report'),schemaVersion:1,type:definition.type||'custom',title:definition.title||'Custom Report',createdAt:now(),scope:clone(scope),filters:clone(definition.filters||{logic:'and',conditions:[]}),modules:definition.modules||['summary','reactions','themes','primfusion','agreement','sources','workflow'],batchId:definition.batchId||resolved.batchIds[0]||null,batchIds:resolved.batchIds,imageIds:matched.map(r=>r.id),results,counts:{total:matched.length,...(results.summary||{})},submissionVersion:definition.submissionVersion||null,warnings:[],generatedBy:definition.generatedBy||'director',automatic:Boolean(definition.automatic),dataSources:{imageRecordSchema:1,reportEngine:1}};await put(REPORTS,report);if(qItemId)await window.genreactrixQueueEngine.setItemState(qItemId,'complete');if(qJob)await window.genreactrixQueueEngine.setJobState(qJob.id,'completed','Report ready');window.dispatchEvent(new CustomEvent('genreactrix:report',{detail:{report}}));window.genreactrixNotificationsEngine?.create?.({severity:'info',title:'Report ready',message:`${report.title} · ${report.imageIds.length} images`,ownerEngine:'reports',relatedReportId:report.id,actionTarget:'reports',actionLabel:'Open',dedupeKey:`report:${report.id}`,resolved:true});render().catch(()=>{});return clone(report)}catch(error){if(qItemId)await window.genreactrixQueueEngine.setItemState(qItemId,'failed',{error:String(error.message||error)});if(qJob)await window.genreactrixQueueEngine.setJobState(qJob.id,'failed',String(error.message||error));throw error}}
async function generateStandardBatchReport(batchId,submissionVersion=1){const b=(await window.genreactrixBatchEngine?.all?.()||[]).find(x=>x.id===batchId);if(!b)throw new Error('Batch not found');return generate({type:'standard-batch',title:`${b.name} · Submission ${submissionVersion}`,scope:{type:'selected',imageIds:b.imageIds},batchId,modules:['summary','reactions','themes','primfusion','agreement','sources','workflow'],automatic:true,generatedBy:'batch-engine',submissionVersion})}
const originalResolve=resolveScope;
resolveScope=async function(scope={}){if(scope.type==='selected'){const all=records(),ids=new Set(scope.imageIds||[]);return{records:all.filter(r=>ids.has(r.id)),batchIds:[]}}return originalResolve(scope)};
async function allReports(){return (await getAll(REPORTS)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
async function savePreset(input){const preset={id:input.id||uid('preset'),schemaVersion:1,name:input.name||'Report preset',createdAt:input.createdAt||now(),updatedAt:now(),definition:clone(input.definition||input)};await put(PRESETS,preset);return preset}
async function presets(){return getAll(PRESETS)}
async function runPreset(id){const p=await get(PRESETS,id);if(!p)throw new Error('Preset not found');return generate({...p.definition,title:p.name})}
function csv(report){const rows=[['module','key','value']];for(const [module,data] of Object.entries(report.results||{})){for(const [key,val] of Object.entries(data||{})){if(val&&typeof val==='object'&&!Array.isArray(val)){for(const [sub,v] of Object.entries(val))rows.push([module,`${key}.${sub}`,typeof v==='object'?JSON.stringify(v):v]);}else rows.push([module,key,val])}}return rows.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n')}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},100)}
async function exportJson(id){const r=await get(REPORTS,id);if(r)download(`${r.title.replace(/[^a-z0-9]+/gi,'_')}.json`,JSON.stringify(r,null,2),'application/json')}
async function exportCsv(id){const r=await get(REPORTS,id);if(r)download(`${r.title.replace(/[^a-z0-9]+/gi,'_')}.csv`,csv(r),'text/csv')}
function reportHtml(r){const sections=Object.entries(r.results||{}).map(([k,v])=>`<section><h2>${k}</h2><pre>${escapeHtml(JSON.stringify(v,null,2))}</pre></section>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(r.title)}</title><style>body{font:16px system-ui;max-width:900px;margin:auto;padding:30px}pre{white-space:pre-wrap;background:#f5f5f5;padding:12px}</style></head><body><h1>${escapeHtml(r.title)}</h1><p>${new Date(r.createdAt).toLocaleString()} · ${r.imageIds.length} images</p>${sections}</body></html>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function printReport(id){const r=await get(REPORTS,id);if(!r)return;const w=open('','_blank');w.document.write(reportHtml(r));w.document.close();w.print()}
function formDefinition(){const scopeType=document.getElementById('reportScope').value;const count=Number(document.getElementById('reportScopeCount').value)||1;const conditions=[];document.querySelectorAll('#reportConditions .report-condition').forEach(row=>{const field=row.querySelector('[data-role=field]').value;if(!field)return;const op=row.querySelector('[data-role=op]').value;const value=row.querySelector('[data-role=value]').value;const name=row.querySelector('[data-role=name]')?.value||'';conditions.push({field,op,value,name})});const modules=[...document.querySelectorAll('[data-report-module]:checked')].map(x=>x.value);return{title:document.getElementById('reportTitle').value||'Custom Report',scope:{type:scopeType,count,start:document.getElementById('reportStart').value,end:document.getElementById('reportEnd').value},filters:{logic:document.getElementById('reportLogic').value,conditions},modules}}
function addCondition(initial={}){const row=document.createElement('div');row.className='report-condition';row.innerHTML=`<select data-role="field"><option value="">Choose filter</option><option value="director-reaction">Director reaction</option><option value="director-reaction-exact">Exact Director reaction set</option><option value="director-theme">Director theme</option><option value="director-theme-exact">Exact Director theme set</option><option value="ai-reaction-min">AI reaction minimum %</option><option value="ai-reaction-max">AI reaction maximum %</option><option value="source-type">Source type</option><option value="batch">Batch ID</option><option value="saved">Saved</option><option value="flagged">Flagged</option><option value="reanalyzed">AI reanalyzed</option><option value="director-revised">Director revised</option><option value="undo-redo">Undo/redo used</option><option value="restored">Restored from recycle</option></select><input data-role="name" placeholder="Reaction (AI filters)"><select data-role="op"><option value="has">Has / equals</option><option value="not">Does not have</option></select><input data-role="value" placeholder="Value"><button type="button" data-remove>×</button>`;for(const [k,v] of Object.entries(initial)){const e=row.querySelector(`[data-role=${k}]`);if(e)e.value=v}row.querySelector('[data-remove]').onclick=()=>row.remove();document.getElementById('reportConditions').appendChild(row)}
async function render(){const all=await allReports(),ps=await presets();const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=String(v)};set('portraitReportCount',all.length);set('portraitLastReport',all[0]?.title||'None');const list=document.getElementById('reportHistory');if(list)list.innerHTML=all.slice(0,30).map(r=>`<article class="report-row" data-report-id="${r.id}"><button type="button" data-open-report="${r.id}"><span>${escapeHtml(r.title)}<small>${new Date(r.createdAt).toLocaleString()}</small></span><strong>${r.imageIds.length}</strong></button><div><button type="button" data-json="${r.id}">JSON</button><button type="button" data-csv="${r.id}">CSV</button><button type="button" data-print="${r.id}">Print</button></div></article>`).join('')||'<p>No reports yet.</p>';const preset=document.getElementById('reportPresets');if(preset)preset.innerHTML=ps.map(p=>`<button type="button" data-run-preset="${p.id}">${escapeHtml(p.name)}</button>`).join('')||'<span>No presets yet.</span>'}
async function openReport(id){const r=await get(REPORTS,id);if(!r)return;document.getElementById('reportOutput').textContent=JSON.stringify(r.results,null,2);document.getElementById('reportOutputTitle').textContent=r.title;document.getElementById('reportOutput').dataset.reportId=id}
function openConsole(){document.getElementById('reportsDialog')?.showModal();render()}
function initUi(){document.getElementById('reportsClose')?.addEventListener('click',()=>document.getElementById('reportsDialog')?.close());document.getElementById('reportAddCondition')?.addEventListener('click',()=>addCondition());document.getElementById('reportRun')?.addEventListener('click',async()=>{const r=await generate(formDefinition());openReport(r.id)});document.getElementById('reportSavePreset')?.addEventListener('click',async()=>{const name=prompt('Preset name',document.getElementById('reportTitle').value||'Report preset');if(name){await savePreset({name,definition:formDefinition()});render()}});document.getElementById('reportHistory')?.addEventListener('click',e=>{const id=e.target.closest('[data-open-report]')?.dataset.openReport;if(id)openReport(id);const j=e.target.dataset.json,c=e.target.dataset.csv,p=e.target.dataset.print;if(j)exportJson(j);if(c)exportCsv(c);if(p)printReport(p)});document.getElementById('reportPresets')?.addEventListener('click',async e=>{const id=e.target.dataset.runPreset;if(id){const r=await runPreset(id);openReport(r.id)}});document.getElementById('reportExportCurrentJson')?.addEventListener('click',()=>{const id=document.getElementById('reportOutput').dataset.reportId;if(id)exportJson(id)});document.getElementById('reportExportCurrentCsv')?.addEventListener('click',()=>{const id=document.getElementById('reportOutput').dataset.reportId;if(id)exportCsv(id)});addCondition()}
async function migrateLegacy(){try{const db=await new Promise((res,rej)=>{const r=indexedDB.open('genreactrix-batch-engine-v1');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(!db.objectStoreNames.contains('reports')){db.close();return}const legacy=await new Promise((res,rej)=>{const tx=db.transaction('reports');const q=tx.objectStore('reports').getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);tx.oncomplete=()=>db.close()});for(const old of legacy){if(await get(REPORTS,old.id))continue;await put(REPORTS,{id:old.id,schemaVersion:1,type:'legacy-standard-batch',title:`${old.batchName||'Batch'} · Submission ${old.submissionVersion||1}`,createdAt:old.createdAt,scope:{type:'selected',imageIds:old.imageIds||[]},filters:{logic:'and',conditions:[]},modules:['summary','reactions','themes','primfusion','sources'],batchId:old.batchId,batchIds:old.batchId?[old.batchId]:[],imageIds:old.imageIds||[],results:{summary:{...(old.counts||{}),aiCovered:old.aiCoverage||0},reactions:{counts:old.reactionTotals||{}},themes:{counts:old.themeTotals||{}},primfusion:{counts:old.primFusionTotals||{}},sources:{counts:old.sourceSummary||{}}},warnings:['Migrated from Batch Engine report store'],generatedBy:'migration',automatic:true,dataSources:{legacyBatchReport:true}})} }catch(e){console.warn('Legacy report migration skipped',e)}}
async function integrity(){const rs=await allReports(),issues=[],ids=new Set();const recordIds=new Set(records().map(r=>r.id));for(const r of rs){if(ids.has(r.id))issues.push({type:'duplicate-report-id',reportId:r.id});ids.add(r.id);for(const id of r.imageIds||[])if(!recordIds.has(id))issues.push({type:'missing-image-record',reportId:r.id,imageId:id});if((r.results?.summary?.images??r.imageIds.length)!==r.imageIds.length)issues.push({type:'count-mismatch',reportId:r.id})}return{checkedAt:now(),reportCount:rs.length,issueCount:issues.length,issues}}
const engine={generate,generateStandardBatchReport,all:allReports,get:id=>get(REPORTS,id),savePreset,presets,runPreset,openConsole,exportJson,exportCsv,printReport,integrity};window.genreactrixReportsEngine=engine;window.addEventListener('DOMContentLoaded',async()=>{initUi();await migrateLegacy();render()});window.addEventListener('genreactrix:batch',()=>render());window.addEventListener('genreactrix:image-record',()=>render());
})();
