/* Genreactrix Settings Engine v2
   Canonical project-wide configuration registry. Runtime/browser facts live in
   ProjectRuntimeEngine and are not a second preference layer. */
(()=>{'use strict';
 const DB='genreactrix-settings',VERSION=2,STORE='settings',META='meta';
 const now=()=>new Date().toISOString(), clone=v=>v==null?v:structuredClone(v);
 const listeners=new Set(), registry=new Map(); let cache=new Map(),ready=false;
 const definitions=[
  ['defaults.images.amount','Default image amount','number',100,{min:1,max:100000,section:'defaults',legacy:['genreactrix-portrait-default-amount']}],
  ['defaults.urls.amount','Default URL amount','number',100,{min:1,max:100000,section:'defaults'}],
  ['defaults.ai.quickAdd','AI manual expansion','number',100,{min:1,max:100000,section:'defaults',legacy:['genreactrix-ai-quick-add']}],
  ['ai.buffer.target','Buffer target','number',25,{min:0,max:100000,section:'ai',legacy:['genreactrix-ai-buffer-target']}],
  ['ai.buffer.refillThreshold','Buffer refill threshold','number',10,{min:0,max:100000,section:'ai'}],
  ['ai.lookAhead.enabled','Buffer enabled','boolean',true,{section:'ai'}],
  ['ai.lookAhead.priority','Queue Priority','string','low',{section:'ai',allowed:['low','normal','high']}],
  ['ai.queue.holdUntilManualStart','Hold Queue until manual AI start','boolean',false,{section:'ai'}],
  ['queue.flow.enabled','Automatic flow-through','boolean',true,{section:'queue'}],
  ['queue.bundle.size','Automatic Bundle size','number',50,{min:1,max:100000,section:'queue'}],
  ['queue.bundle.completeAvailable','Complete whatever is available','boolean',false,{section:'queue'}],
  ['ai.provider.model','AI model label','string','',{section:'ai'}],
  ['ai.prompt.version','AI prompt set','string','',{section:'ai'}],
  ['ai.components.default','Default AI components','json',{reactions:true,themes:true,description:true,emotion:false,reactionReasons:false,genreReasons:false},{section:'ai',legacy:['genreactrix-portrait-ai-outputs']}],
  ['ai.components.behavior','Default AI component behavior','json',{reactions:'analyze',themes:'analyze',description:'analyze'},{section:'ai'}],
  ['acquisition.mode','Default acquisition mode','string','temporary',{section:'acquisition',allowed:['temporary','link','prefetch']}],
  ['acquisition.fallbackToLink','Fallback to hyperlink','boolean',true,{section:'acquisition'}],
  ['recycle.retentionDays','Recycle retention days','number',30,{min:0,max:3650,section:'storage',legacy:['genreactrix-recycle-retention-days']}],
  ['batch.defaultSize','Default batch size','number',100,{min:1,max:100000,section:'batch'}],
  ['batch.flaggedBlockSubmission','Flagged images block submission','boolean',false,{section:'batch'}],
  ['batch.partialSubmission','Allow partial submission','boolean',false,{section:'batch'}],
  ['batch.postSubmit','After submission','string','new',{section:'batch',allowed:['new','none','next']}],
  ['queue.defaultPriority','Default queue priority','string','normal',{section:'queue',allowed:['high','normal','low']}],
  ['queue.autoResumeAutomatic','Auto-resume automatic jobs','boolean',true,{section:'queue'}],
  ['director.postCommit','After Director commit','string','stay',{section:'director',allowed:['stay','next','next-incomplete']}],
  ['director.warnDirtyNavigation','Warn before leaving a draft','boolean',true,{section:'director'}],
  ['director.restoreZoom','Restore per-image zoom','boolean',true,{section:'director'}],
  ['director.restoreAiOverlay','Restore AI overlay state','boolean',true,{section:'director'}],
  ['director.defaultNavigation','Default Director navigation','string','next',{section:'director',allowed:['next','next-incomplete','next-flagged','next-blocked','random']}],
  ['notifications.retentionDays','Resolved notification retention','number',30,{min:0,max:3650,section:'notifications'}],
  ['notifications.unreadBadge','Show unread badge','boolean',true,{section:'notifications'}],
  ['project.name','Project name','string','Genreactrix',{section:'project'}],
  ['project.directorId','Director identifier','string','local-director',{section:'project',legacy:['genreactrix-director-account']}],
  ['project.id','Project ID','string','',{section:'project'}],
  ['quick.presets','Quick action presets','json',{}, {section:'quick',legacy:['genreactrix-quick-action-presets-v1']}],
  ['ai.worker.base','AI Worker URL','string','',{section:'ai',legacy:['genreactrix-ai-worker-base']}],
  ['ai.worker.accessKey','AI analysis key','string','',{section:'ai',sensitive:true,legacy:['genreactrix-ai-access-key']}]
 ];
 const openDb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(META))db.createObjectStore(META,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
 const request=(store,mode,op)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,mode),s=t.objectStore(store),r=op(s);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
 const put=v=>request(STORE,'readwrite',s=>s.put(clone(v))), all=()=>request(STORE,'readonly',s=>s.getAll());
 function register(id,label,type,defaultValue,opts={}){registry.set(id,{id,label,type,defaultValue,section:'general',scope:'project',...opts});if(!cache.has(id))cache.set(id,clone(defaultValue))}
 definitions.forEach(d=>register(...d));
 function normalize(def,value){if(value===undefined||value===null)return clone(def.defaultValue);if(def.type==='number'){value=Number(value);if(!Number.isFinite(value))value=Number(def.defaultValue);if(def.min!=null)value=Math.max(def.min,value);if(def.max!=null)value=Math.min(def.max,value);return value}if(def.type==='boolean')return value===true||value==='true'||value===1||value==='1';if(def.type==='json'){if(typeof value==='string'){try{return JSON.parse(value)}catch{return clone(def.defaultValue)}}return clone(value)}value=String(value);if(def.allowed&&!def.allowed.includes(value))return clone(def.defaultValue);return value}
 function get(id,fallback){return cache.has(id)?clone(cache.get(id)):fallback}
 async function set(id,value,{silent=false}={}){const def=registry.get(id);if(!def)throw new Error(`Unknown setting: ${id}`);const normalized=normalize(def,value),ctx=window.genreactrixProjectRuntimeEngine;if(id==='project.id'&&normalized&&ctx?.projectId?.()!==normalized)await ctx.bindProject?.(normalized,{name:get('project.name'),directorId:get('project.directorId')});cache.set(id,normalized);await put({id,value:normalized,updatedAt:now(),schemaVersion:2,scope:def.scope||'project',projectId:ctx?.projectId?.()||normalized||''});if(id==='project.name')await ctx?.updateProject?.({name:normalized});if(id==='project.directorId')await ctx?.updateProject?.({directorId:normalized});if(!silent){const detail={id,value:clone(normalized),definition:clone(def),projectId:ctx?.projectId?.()||''};window.dispatchEvent(new CustomEvent('genreactrix:setting',{detail}));listeners.forEach(fn=>fn(detail))}return clone(normalized)}
 async function migrate(){let changed=0;for(const def of registry.values()){if(cache.has(def.id)&&cache.get(def.id)!==def.defaultValue)continue;for(const key of def.legacy||[]){const raw=localStorage.getItem(key);if(raw==null)continue;const value=normalize(def,raw);await set(def.id,value,{silent:true});localStorage.removeItem(key);changed++;break}}if(['genreactrix-v1','genreactrix-v2-theme-catalog','genreactrix-v3-114-point-prims'].includes(get('ai.prompt.version')))await set('ai.prompt.version','',{silent:true});const ctx=window.genreactrixProjectRuntimeEngine;if(ctx?.ready)await ctx.ready;const canonicalProjectId=ctx?.projectId?.()||get('project.id')||`project_${crypto.randomUUID()}`;if(get('project.id')!==canonicalProjectId)await set('project.id',canonicalProjectId,{silent:true});await ctx?.updateProject?.({name:get('project.name'),directorId:get('project.directorId')});return changed}
 async function init(){if(window.genreactrixProjectRuntimeEngine?.ready)await window.genreactrixProjectRuntimeEngine.ready;const rows=await all();rows.forEach(r=>{const def=registry.get(r.id);if(def)cache.set(r.id,normalize(def,r.value))});await migrate();const pid=window.genreactrixProjectRuntimeEngine?.projectId?.()||get('project.id');for(const def of registry.values()){const row=rows.find(r=>r.id===def.id);if(row&&(!row.projectId||row.scope!=='project'))await put({...row,projectId:pid,scope:'project',schemaVersion:2,updatedAt:row.updatedAt||now()})}ready=true;window.dispatchEvent(new CustomEvent('genreactrix:settings-ready',{detail:{projectId:pid,runtimeId:window.genreactrixProjectRuntimeEngine?.runtimeId?.()||null}}));render();return api}
 function definitionsFor(section){return [...registry.values()].filter(d=>!section||d.section===section).map(clone)}
 function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}
 async function reset(id){const def=registry.get(id);return set(id,clone(def.defaultValue))}
 async function exportSettings({includeSensitive=false}={}){const values={},scopes={};for(const def of registry.values()){if(def.sensitive&&!includeSensitive)continue;values[def.id]=get(def.id);scopes[def.id]=def.scope||'project'}return{type:'genreactrix-settings',schemaVersion:2,createdAt:now(),projectId:window.genreactrixProjectRuntimeEngine?.projectId?.()||get('project.id'),scope:'project',values,scopes}}
 async function importSettings(payload,{includeSensitive=false}={}){if(payload?.type!=='genreactrix-settings'&&payload?.type!=='genreactrix-backup')throw new Error('Not a Genreactrix settings or backup file');const values=payload.values||payload.settings?.values||{},entries=Object.entries(values).sort(([a],[b])=>a==='project.id'?-1:b==='project.id'?1:0);let imported=0;for(const [id,value] of entries){const def=registry.get(id);if(!def||def.sensitive&&!includeSensitive)continue;await set(id,value);imported++}return imported}
 async function createBackup(mode='data'){const p=window.genreactrixPersistenceEngine;if(!p?.createBackup)throw new Error('Portable persistence engine is unavailable');return p.createBackup({mode})}
 function downloadJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function previewBackup(file){const text=await file.text(),payload=JSON.parse(text);if(payload.type==='genreactrix-settings')return payload;if(payload.type==='genreactrix-backup'){const p=window.genreactrixPersistenceEngine;if(!p?.verifyPayload)throw new Error('Portable persistence engine is unavailable');await p.verifyPayload(payload);return payload}throw new Error('Unsupported backup file')}
 async function verify(){const issues=[],pid=window.genreactrixProjectRuntimeEngine?.projectId?.()||get('project.id');for(const def of registry.values()){const value=get(def.id),normalized=normalize(def,value);if(JSON.stringify(value)!==JSON.stringify(normalized))issues.push({id:def.id,type:'invalid-value'});if((def.scope||'project')!=='project')issues.push({id:def.id,type:'unexpected-nonproject-setting'})}if(get('project.id')!==pid)issues.push({id:'project.id',type:'project-context-mismatch',settingProjectId:get('project.id'),contextProjectId:pid});return{settingCount:registry.size,projectId:pid,scope:'project',issueCount:issues.length,issues,ready}}
 async function projectInfo(){const dbs=await indexedDB.databases?.()||[],ctx=window.genreactrixProjectRuntimeEngine,runtime=ctx?.currentRuntime?.();return{projectId:ctx?.projectId?.()||get('project.id'),projectName:get('project.name'),directorId:get('project.directorId'),runtimeId:ctx?.runtimeId?.()||null,browserFamily:runtime?.browserFamily||'',settings:registry.size,databases:dbs.map(d=>({name:d.name,version:d.version}))}}
 function bindInput(id,settingId){const el=document.getElementById(id);if(!el)return;const def=registry.get(settingId),value=get(settingId);if(el.type==='checkbox')el.checked=Boolean(value);else el.value=typeof value==='object'?JSON.stringify(value):String(value??'');el.onchange=async()=>{const v=el.type==='checkbox'?el.checked:el.value;await set(settingId,v);status(`${def.label} saved.`)}}
 function status(msg){const el=document.getElementById('settingsStatus');if(el)el.textContent=msg;window.setPortraitStationStatus?.(msg)}
 async function render(){if(!document.getElementById('portraitSettingsDialog'))return;bindInput('settingDefaultImages','defaults.images.amount');bindInput('settingDefaultUrls','defaults.urls.amount');bindInput('settingAiQuickAdd','defaults.ai.quickAdd');bindInput('settingAiBuffer','ai.buffer.target');bindInput('settingAiRefill','ai.buffer.refillThreshold');bindInput('settingQueueFlow','queue.flow.enabled');bindInput('settingBundleSize','queue.bundle.size');bindInput('settingCompleteAvailable','queue.bundle.completeAvailable');bindInput('settingRecycleDays','recycle.retentionDays');bindInput('settingBatchSize','batch.defaultSize');bindInput('settingNotifyDays','notifications.retentionDays');bindInput('settingProjectName','project.name');bindInput('settingDirectorId','project.directorId');const info=await projectInfo();const el=document.getElementById('settingsProjectInfo');if(el)el.textContent=`Project ${info.projectId} · Runtime ${info.runtimeId||'unavailable'}${info.browserFamily?` (${info.browserFamily})`:''} · ${info.databases.length} database(s) · ${info.settings} project settings`;}
 function initUi(){document.getElementById('portraitSettingsBtn')?.addEventListener('click',async()=>{await render();document.getElementById('portraitSettingsDialog')?.showModal()});document.getElementById('portraitSettingsClose')?.addEventListener('click',()=>document.getElementById('portraitSettingsDialog')?.close());document.querySelectorAll('[data-settings-section]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-settings-panel]').forEach(p=>p.hidden=p.dataset.settingsPanel!==b.dataset.settingsSection);document.querySelectorAll('[data-settings-section]').forEach(x=>x.classList.toggle('active',x===b))}));document.getElementById('settingsExport')?.addEventListener('click',async()=>downloadJson(await exportSettings(),`genreactrix-settings-${new Date().toISOString().slice(0,10)}.json`));document.getElementById('settingsBackupData')?.addEventListener('click',async()=>{try{status('Creating verified portable backup…');const backup=await createBackup('data');window.genreactrixPersistenceEngine.downloadJson(backup,`genreactrix-backup-${new Date().toISOString().slice(0,10)}.json`);status(`Backup ready: ${backup.manifest?.recordCount||0} record(s), ${backup.manifest?.binaryCount||0} binary asset(s).`)}catch(err){status(`Backup failed: ${err.message}`)}});document.getElementById('settingsImportFile')?.addEventListener('change',async e=>{try{const p=await previewBackup(e.target.files[0]);if(p.type==='genreactrix-backup'){status('Complete backup verified. Use Maintenance → Restore backup to restore project data and image bytes.');return}const count=await importSettings(p);status(`Imported ${count} setting(s).`);render()}catch(err){status(err.message)}});document.getElementById('settingsVerify')?.addEventListener('click',async()=>{const r=await verify();status(`Settings verification: ${r.issueCount} issue(s).`)});document.getElementById('settingsVerifyProject')?.addEventListener('click',()=>window.genreactrixMaintenanceEngine?.openConsole?.());document.getElementById('recycleEmptyNow')?.addEventListener('click',async()=>{const r=await window.genreactrixImagesEngine?.purgeRecycle?.({all:true});status(`Recycle bin purged ${r?.purged||0} image(s).`)});document.getElementById('recycleEmptyBefore')?.addEventListener('click',async()=>{const date=document.getElementById('recycleBeforeDate')?.value;if(!date)return status('Choose a cutoff date.');const r=await window.genreactrixImagesEngine?.purgeRecycle?.({before:new Date(`${date}T23:59:59`).toISOString()});status(`Purged ${r?.purged||0} image(s).`)});document.getElementById('recycleFreeMb')?.addEventListener('click',async()=>{const mb=Math.max(1,Number(document.getElementById('recycleFreeMbAmount')?.value)||100),r=await window.genreactrixImagesEngine?.purgeRecycle?.({freeBytes:mb*1048576});status(`Freed ${((r?.freed||0)/1048576).toFixed(1)} MB.`)});}
 const api={init,register,get,set,reset,definitions:definitionsFor,subscribe,exportSettings,importSettings,createBackup,previewBackup,verify,projectInfo,get ready(){return ready}};window.genreactrixSettingsEngine=api;window.addEventListener('DOMContentLoaded',()=>{initUi();init().catch(e=>status(`Settings failed: ${e.message}`))});
})();
