/* Genreactrix Settings Engine v1
   Canonical configuration registry, legacy migration, backups, restore preview, and maintenance access. */
(()=>{'use strict';
 const DB='genreactrix-settings',VERSION=1,STORE='settings',META='meta';
 const now=()=>new Date().toISOString(), clone=v=>v==null?v:structuredClone(v);
 const listeners=new Set(), registry=new Map(); let cache=new Map(),ready=false;
 const definitions=[
  ['defaults.images.amount','Default image amount','number',100,{min:1,max:100000,section:'defaults',legacy:['genreactrix-portrait-default-amount']}],
  ['defaults.urls.amount','Default URL amount','number',100,{min:1,max:100000,section:'defaults'}],
  ['defaults.ai.quickAdd','AI manual expansion','number',100,{min:1,max:100000,section:'defaults',legacy:['genreactrix-ai-quick-add']}],
  ['ai.buffer.target','AI buffer target','number',25,{min:0,max:100000,section:'ai',legacy:['genreactrix-ai-buffer-target']}],
  ['ai.buffer.refillThreshold','AI refill threshold','number',10,{min:0,max:100000,section:'ai'}],
  ['ai.lookAhead.enabled','Automatic AI look-ahead','boolean',true,{section:'ai'}],
  ['ai.components.default','Default AI components','json',{reactions:true,themes:true,description:true,emotion:false,reactionReasons:false,genreReasons:false},{section:'ai',legacy:['genreactrix-portrait-ai-outputs']}],
  ['acquisition.mode','Default acquisition mode','string','temporary',{section:'acquisition',allowed:['temporary','link','prefetch']}],
  ['acquisition.fallbackToLink','Fallback to hyperlink','boolean',true,{section:'acquisition'}],
  ['recycle.retentionDays','Recycle retention days','number',30,{min:0,max:3650,section:'storage',legacy:['genreactrix-recycle-retention-days']}],
  ['batch.defaultSize','Default batch size','number',100,{min:1,max:100000,section:'batch'}],
  ['batch.flaggedBlockSubmission','Flagged images block submission','boolean',false,{section:'batch'}],
  ['batch.partialSubmission','Allow partial submission','boolean',false,{section:'batch'}],
  ['batch.postSubmit','After submission','string','new',{section:'batch',allowed:['new','none','next']}],
  ['queue.defaultPriority','Default queue priority','string','normal',{section:'queue',allowed:['high','normal','low']}],
  ['queue.autoResumeAutomatic','Auto-resume automatic jobs','boolean',true,{section:'queue'}],
  ['notifications.retentionDays','Resolved notification retention','number',30,{min:0,max:3650,section:'notifications'}],
  ['notifications.unreadBadge','Show unread badge','boolean',true,{section:'notifications'}],
  ['project.name','Project name','string','Genreactrix',{section:'project'}],
  ['project.directorId','Director identifier','string','local-director',{section:'project',legacy:['genreactrix-director-account']}],
  ['project.id','Project ID','string','',{section:'project'}],
  ['quick.presets','Quick action presets','json',{}, {section:'quick',legacy:['genreactrix-quick-action-presets-v1']}],
  ['ai.worker.base','AI Worker URL','string','',{section:'ai',legacy:['genreactrix-ai-worker-base']}],
  ['ai.worker.accessKey','AI analysis key','string','',{section:'ai',sensitive:true,legacy:['genreactrix-ai-access-key']}]
 ];
 const openDb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(META))db.createObjectStore(META,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
 const request=(store,mode,op)=>openDb().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,mode),s=t.objectStore(store),r=op(s);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);t.oncomplete=()=>db.close()}));
 const put=v=>request(STORE,'readwrite',s=>s.put(clone(v))), all=()=>request(STORE,'readonly',s=>s.getAll());
 function register(id,label,type,defaultValue,opts={}){registry.set(id,{id,label,type,defaultValue,section:'general',...opts});if(!cache.has(id))cache.set(id,clone(defaultValue))}
 definitions.forEach(d=>register(...d));
 function normalize(def,value){if(value===undefined||value===null)return clone(def.defaultValue);if(def.type==='number'){value=Number(value);if(!Number.isFinite(value))value=Number(def.defaultValue);if(def.min!=null)value=Math.max(def.min,value);if(def.max!=null)value=Math.min(def.max,value);return value}if(def.type==='boolean')return value===true||value==='true'||value===1||value==='1';if(def.type==='json'){if(typeof value==='string'){try{return JSON.parse(value)}catch{return clone(def.defaultValue)}}return clone(value)}value=String(value);if(def.allowed&&!def.allowed.includes(value))return clone(def.defaultValue);return value}
 function get(id,fallback){return cache.has(id)?clone(cache.get(id)):fallback}
 async function set(id,value,{silent=false}={}){const def=registry.get(id);if(!def)throw new Error(`Unknown setting: ${id}`);const normalized=normalize(def,value);cache.set(id,normalized);await put({id,value:normalized,updatedAt:now(),schemaVersion:1});if(!silent){const detail={id,value:clone(normalized),definition:clone(def)};window.dispatchEvent(new CustomEvent('genreactrix:setting',{detail}));listeners.forEach(fn=>fn(detail))}return clone(normalized)}
 async function migrate(){let changed=0;for(const def of registry.values()){if(cache.has(def.id)&&cache.get(def.id)!==def.defaultValue)continue;for(const key of def.legacy||[]){const raw=localStorage.getItem(key);if(raw==null)continue;const value=normalize(def,raw);await set(def.id,value,{silent:true});localStorage.removeItem(key);changed++;break}}if(!get('project.id'))await set('project.id',`project_${crypto.randomUUID()}`,{silent:true});return changed}
 async function init(){const rows=await all();rows.forEach(r=>{const def=registry.get(r.id);if(def)cache.set(r.id,normalize(def,r.value))});await migrate();ready=true;window.dispatchEvent(new CustomEvent('genreactrix:settings-ready'));render();return api}
 function definitionsFor(section){return [...registry.values()].filter(d=>!section||d.section===section).map(clone)}
 function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}
 async function reset(id){const def=registry.get(id);return set(id,clone(def.defaultValue))}
 async function exportSettings({includeSensitive=false}={}){const values={};for(const def of registry.values()){if(def.sensitive&&!includeSensitive)continue;values[def.id]=get(def.id)}return{type:'genreactrix-settings',schemaVersion:1,createdAt:now(),values}}
 async function importSettings(payload,{includeSensitive=false}={}){if(payload?.type!=='genreactrix-settings'&&payload?.type!=='genreactrix-backup')throw new Error('Not a Genreactrix settings or backup file');const values=payload.values||payload.settings?.values||{};let imported=0;for(const [id,value] of Object.entries(values)){const def=registry.get(id);if(!def||def.sensitive&&!includeSensitive)continue;await set(id,value);imported++}return imported}
 async function dumpDatabase(name){return new Promise((resolve)=>{const r=indexedDB.open(name);r.onerror=()=>resolve({name,error:String(r.error)});r.onsuccess=()=>{const db=r.result,stores=[...db.objectStoreNames];if(!stores.length){db.close();resolve({name,stores:{}});return}const t=db.transaction(stores,'readonly'),out={};let pending=stores.length;stores.forEach(store=>{const q=t.objectStore(store).getAll();q.onsuccess=()=>{out[store]=q.result||[];if(--pending===0){db.close();resolve({name,stores:out})}};q.onerror=()=>{out[store]={error:String(q.error)};if(--pending===0){db.close();resolve({name,stores:out})}}})}})}
 async function createBackup(mode='data'){const names=(await indexedDB.databases?.()||[]).map(x=>x.name).filter(Boolean).filter(n=>n.startsWith('genreactrix-'));const databases=[];for(const name of names)databases.push(await dumpDatabase(name));return{type:'genreactrix-backup',schemaVersion:1,mode,createdAt:now(),projectId:get('project.id'),settings:await exportSettings(),databases,manifest:{databaseCount:databases.length,recordCount:databases.reduce((n,d)=>n+Object.values(d.stores||{}).reduce((s,v)=>s+(Array.isArray(v)?v.length:0),0),0)}}}
 function downloadJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function previewBackup(file){const text=await file.text(),payload=JSON.parse(text);if(payload.type!=='genreactrix-backup'&&payload.type!=='genreactrix-settings')throw new Error('Unsupported backup file');return payload}
 async function verify(){const issues=[];for(const def of registry.values()){const value=get(def.id);const normalized=normalize(def,value);if(JSON.stringify(value)!==JSON.stringify(normalized))issues.push({id:def.id,type:'invalid-value'})}return{settingCount:registry.size,issueCount:issues.length,issues,ready}}
 async function projectInfo(){const dbs=await indexedDB.databases?.()||[];return{projectId:get('project.id'),projectName:get('project.name'),directorId:get('project.directorId'),settings:registry.size,databases:dbs.map(d=>({name:d.name,version:d.version}))}}
 function bindInput(id,settingId){const el=document.getElementById(id);if(!el)return;const def=registry.get(settingId),value=get(settingId);if(el.type==='checkbox')el.checked=Boolean(value);else el.value=typeof value==='object'?JSON.stringify(value):String(value??'');el.onchange=async()=>{const v=el.type==='checkbox'?el.checked:el.value;await set(settingId,v);status(`${def.label} saved.`)}}
 function status(msg){const el=document.getElementById('settingsStatus');if(el)el.textContent=msg;window.setPortraitStationStatus?.(msg)}
 async function render(){if(!document.getElementById('portraitSettingsDialog'))return;bindInput('settingDefaultImages','defaults.images.amount');bindInput('settingDefaultUrls','defaults.urls.amount');bindInput('settingAiQuickAdd','defaults.ai.quickAdd');bindInput('settingAiBuffer','ai.buffer.target');bindInput('settingAiRefill','ai.buffer.refillThreshold');bindInput('settingRecycleDays','recycle.retentionDays');bindInput('settingBatchSize','batch.defaultSize');bindInput('settingNotifyDays','notifications.retentionDays');bindInput('settingProjectName','project.name');bindInput('settingDirectorId','project.directorId');const info=await projectInfo();const el=document.getElementById('settingsProjectInfo');if(el)el.textContent=`Project ${info.projectId} · ${info.databases.length} database(s) · ${info.settings} settings`;}
 function initUi(){document.getElementById('portraitSettingsBtn')?.addEventListener('click',async()=>{await render();document.getElementById('portraitSettingsDialog')?.showModal()});document.getElementById('portraitSettingsClose')?.addEventListener('click',()=>document.getElementById('portraitSettingsDialog')?.close());document.querySelectorAll('[data-settings-section]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-settings-panel]').forEach(p=>p.hidden=p.dataset.settingsPanel!==b.dataset.settingsSection);document.querySelectorAll('[data-settings-section]').forEach(x=>x.classList.toggle('active',x===b))}));document.getElementById('settingsExport')?.addEventListener('click',async()=>downloadJson(await exportSettings(),`genreactrix-settings-${new Date().toISOString().slice(0,10)}.json`));document.getElementById('settingsBackupData')?.addEventListener('click',async()=>downloadJson(await createBackup('data'),`genreactrix-backup-${new Date().toISOString().slice(0,10)}.json`));document.getElementById('settingsImportFile')?.addEventListener('change',async e=>{try{const p=await previewBackup(e.target.files[0]);const count=await importSettings(p);status(`Imported ${count} setting(s).`);render()}catch(err){status(err.message)}});document.getElementById('settingsVerify')?.addEventListener('click',async()=>{const r=await verify();status(`Settings verification: ${r.issueCount} issue(s).`)});document.getElementById('settingsVerifyProject')?.addEventListener('click',()=>window.genreactrixMaintenanceEngine?.openConsole?.());document.getElementById('recycleEmptyNow')?.addEventListener('click',async()=>{const r=await window.genreactrixImagesEngine?.purgeRecycle?.({all:true});status(`Recycle bin purged ${r?.purged||0} image(s).`)});document.getElementById('recycleEmptyBefore')?.addEventListener('click',async()=>{const date=document.getElementById('recycleBeforeDate')?.value;if(!date)return status('Choose a cutoff date.');const r=await window.genreactrixImagesEngine?.purgeRecycle?.({before:new Date(`${date}T23:59:59`).toISOString()});status(`Purged ${r?.purged||0} image(s).`)});document.getElementById('recycleFreeMb')?.addEventListener('click',async()=>{const mb=Math.max(1,Number(document.getElementById('recycleFreeMbAmount')?.value)||100),r=await window.genreactrixImagesEngine?.purgeRecycle?.({freeBytes:mb*1048576});status(`Freed ${((r?.freed||0)/1048576).toFixed(1)} MB.`)});}
 const api={init,register,get,set,reset,definitions:definitionsFor,subscribe,exportSettings,importSettings,createBackup,previewBackup,verify,projectInfo,get ready(){return ready}};window.genreactrixSettingsEngine=api;window.addEventListener('DOMContentLoaded',()=>{initUi();init().catch(e=>status(`Settings failed: ${e.message}`))});
})();
