(()=>{
'use strict';
const DB='genreactrix-analytics-engine-v1', STORE='workspaces', VERSION=1;
const now=()=>new Date().toISOString();
const clone=v=>v==null?v:structuredClone(v);
const uid=()=>`analytics-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('updatedAt','updatedAt')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function allWorkspaces(){const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res((q.result||[]).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))));q.onerror=()=>rej(q.error)})}
async function saveWorkspace(input={}){const value={id:input.id||uid(),schemaVersion:1,name:String(input.name||'Research workspace'),view:input.view||'primfusion',reactionA:input.reactionA||'',reactionB:input.reactionB||'',theme:input.theme||'',selectedCell:input.selectedCell||'',favoriteReportIds:[...(input.favoriteReportIds||[])],createdAt:input.createdAt||now(),updatedAt:now()};const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(value);q.onsuccess=()=>res(value);q.onerror=()=>rej(q.error)})}
function records(){return window.genreactrixImageRecordEngine?.all?.()||[]}
function director(r){return r.analysis?.director||{}}
function reactions(r){return [...new Set(director(r).reactions||director(r).selectedReactions||[])]}
function themes(r){return (director(r).themes||[]).filter(Boolean).map(x=>typeof x==='string'?x:(x.label||x.id||'Unknown'))}
function pairKey(a,b){return [String(a),String(b)].sort((x,y)=>x.localeCompare(y)).join(' × ')}
function primFusionKey(r){const p=director(r).primFusion;return typeof p==='string'?p:(p?.label||p?.id||((reactions(r).length>=2)?pairKey(reactions(r)[0],reactions(r)[1]):''))}
function aiReactionMap(r){const raw=r.analysis?.ai?.components?.reactions||r.analysis?.ai?.reactions||{};const out={};if(Array.isArray(raw)){for(const x of raw){const key=x.name||x.id||x.reaction;if(key)out[key]=Number(x.percentage??x.confidence??x.score)}}else for(const [k,v] of Object.entries(raw))out[k]=typeof v==='number'?v:Number(v?.percentage??v?.confidence??v?.score);return out}
function agreement(r){const rs=reactions(r), ai=aiReactionMap(r), names=new Set([...rs,...Object.keys(ai)]);let n=0,agree=0;for(const name of names){const score=ai[name];if(!Number.isFinite(score))continue;n++;if(rs.includes(name)===(score>=50))agree++}return n?Math.round(agree/n*1000)/10:null}
function calculate(){const items=records();const reactionNames=[...new Set(items.flatMap(reactions))].sort();const themeNames=[...new Set(items.flatMap(themes))].sort();const pairCounts={},pairImages={},themeReaction={},themePairs={},agreementRows=[];
 for(const r of items){const rs=reactions(r), ts=themes(r);for(let i=0;i<rs.length;i++)for(let j=i;j<rs.length;j++){const key=pairKey(rs[i],rs[j]);pairCounts[key]=(pairCounts[key]||0)+1;(pairImages[key]||(pairImages[key]=[])).push(r.id)}
  const pf=primFusionKey(r);if(pf){pairCounts[pf]=(pairCounts[pf]||0)+1;(pairImages[pf]||(pairImages[pf]=[])).push(r.id)}
  for(const t of ts){const tr=themeReaction[t]||(themeReaction[t]={});for(const x of rs)tr[x]=(tr[x]||0)+1;const tp=themePairs[t]||(themePairs[t]={});if(rs.length>=2){const k=pairKey(rs[0],rs[1]);tp[k]=(tp[k]||0)+1}}
  const a=agreement(r);if(Number.isFinite(a))agreementRows.push({imageId:r.id,agreement:a,reactions:rs,themes:ts})
 }
 const possiblePairs=[];for(let i=0;i<reactionNames.length;i++)for(let j=i;j<reactionNames.length;j++){const key=pairKey(reactionNames[i],reactionNames[j]);possiblePairs.push({key,a:reactionNames[i],b:reactionNames[j],count:pairCounts[key]||0,imageIds:pairImages[key]||[]})}
 const avgAgreement=agreementRows.length?Math.round(agreementRows.reduce((s,x)=>s+x.agreement,0)/agreementRows.length*10)/10:null;
 return{generatedAt:now(),recordCount:items.length,reactionNames,themeNames,pairCounts,pairImages,possiblePairs,themeReaction,themePairs,agreementRows,avgAgreement,agreementBuckets:{high:agreementRows.filter(x=>x.agreement>=80).length,mixed:agreementRows.filter(x=>x.agreement>=50&&x.agreement<80).length,low:agreementRows.filter(x=>x.agreement<50).length}}}
let cache=null, cacheStamp='';
function snapshot(){const list=records(),stamp=`${list.length}:${list.map(r=>r.updatedAt||r.timestamps?.updatedAt||'').sort().at(-1)||''}`;if(!cache||stamp!==cacheStamp){cache=calculate();cacheStamp=stamp}return clone(cache)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function heatTone(count,max){if(!max)return 0;return Math.max(.08,Math.min(1,count/max))}
async function drillDown(title,imageIds){const ids=[...new Set(imageIds||[])];const report=await window.genreactrixReportsEngine?.generate?.({title,scope:{type:'selected',imageIds:ids},filters:{logic:'and',conditions:[]},modules:['summary','reactions','themes','primfusion','agreement'],fields:['imageId','filename','batch','directorReactions','directorThemes','primFusion','aiAgreement'],statistics:['count','agreementRate']});window.genreactrixReportsEngine?.openConsole?.();return report}
function renderMatrix(data){const root=document.getElementById('analyticsBody');if(!root)return;const names=data.reactionNames,max=Math.max(1,...data.possiblePairs.map(x=>x.count));if(!names.length){root.innerHTML='<p>No Director reaction data yet.</p>';return}let html='<div class="analytics-matrix-wrap"><table class="analytics-matrix"><thead><tr><th></th>'+names.map(n=>`<th title="${esc(n)}">${esc(n)}</th>`).join('')+'</tr></thead><tbody>';for(let i=0;i<names.length;i++){html+=`<tr><th>${esc(names[i])}</th>`;for(let j=0;j<names.length;j++){if(j<i){html+='<td class="is-na"></td>';continue}const key=pairKey(names[i],names[j]),count=data.pairCounts[key]||0,tone=heatTone(count,max);html+=`<td><button data-analytics-pair="${esc(key)}" data-count="${count}" style="--heat:${tone}" title="${esc(key)} · ${count}">${count}</button></td>`}html+='</tr>'}html+='</tbody></table></div><div class="analytics-legend">Tap a cell to open the matching images. Darker cells contain more classifications.</div>';root.innerHTML=html}
function renderCorrelations(data){const root=document.getElementById('analyticsBody');if(!root)return;const rows=[];for(const [theme,map] of Object.entries(data.themeReaction)){const total=Object.values(map).reduce((a,b)=>a+b,0);for(const [reaction,count] of Object.entries(map))rows.push({theme,reaction,count,share:total?Math.round(count/total*1000)/10:0})}rows.sort((a,b)=>b.count-a.count);root.innerHTML=rows.length?`<table class="analytics-list"><thead><tr><th>Theme</th><th>Reaction</th><th>Count</th><th>Share</th></tr></thead><tbody>${rows.slice(0,250).map(x=>`<tr><td>${esc(x.theme)}</td><td>${esc(x.reaction)}</td><td>${x.count}</td><td>${x.share}%</td></tr>`).join('')}</tbody></table>`:'<p>No theme correlation data yet.</p>'}
function renderAgreement(data){const root=document.getElementById('analyticsBody');if(!root)return;const lowest=[...data.agreementRows].sort((a,b)=>a.agreement-b.agreement).slice(0,30);root.innerHTML=`<div class="analytics-kpis"><button data-agreement-filter="all"><strong>${data.avgAgreement??'—'}%</strong><span>Average agreement</span></button><button data-agreement-filter="high"><strong>${data.agreementBuckets.high}</strong><span>80–100%</span></button><button data-agreement-filter="mixed"><strong>${data.agreementBuckets.mixed}</strong><span>50–79%</span></button><button data-agreement-filter="low"><strong>${data.agreementBuckets.low}</strong><span>Below 50%</span></button></div><h3>Lowest agreement</h3>${lowest.length?`<table class="analytics-list"><thead><tr><th>Image</th><th>Agreement</th><th>Director reactions</th></tr></thead><tbody>${lowest.map(x=>`<tr><td><button data-agreement-image="${esc(x.imageId)}">${esc(x.imageId)}</button></td><td>${x.agreement}%</td><td>${esc(x.reactions.join(' + '))}</td></tr>`).join('')}</tbody></table>`:'<p>No comparable AI reaction data yet.</p>'}`}
function renderDiagnostics(data){const root=document.getElementById('analyticsBody');if(!root)return;const empty=data.possiblePairs.filter(x=>x.count===0),under=data.possiblePairs.filter(x=>x.count>0&&x.count<=2).sort((a,b)=>a.count-b.count);root.innerHTML=`<div class="analytics-kpis"><div><strong>${empty.length}</strong><span>Empty cells</span></div><div><strong>${under.length}</strong><span>Underrepresented (1–2)</span></div><div><strong>${data.possiblePairs.length}</strong><span>Possible observed-reaction cells</span></div></div><h3>Empty cells</h3><div class="analytics-chip-list">${empty.slice(0,300).map(x=>`<button data-empty-pair="${esc(x.key)}">${esc(x.key)}</button>`).join('')||'<span>None.</span>'}</div><h3>Underrepresented</h3><div class="analytics-chip-list">${under.map(x=>`<button data-analytics-pair="${esc(x.key)}">${esc(x.key)} · ${x.count}</button>`).join('')||'<span>None.</span>'}</div><p class="analytics-note">An empty cell means no current Director record contains that reaction pair. It may reflect the source pool, Director choices, incomplete classifications, or a genuinely rare combination.</p>`}
function currentView(){return document.getElementById('analyticsView')?.value||'primfusion'}
function render(){const data=snapshot(),view=currentView();document.getElementById('analyticsSummary').textContent=`${data.recordCount} records · ${data.reactionNames.length} reactions · ${data.themeNames.length} themes`;if(view==='primfusion')renderMatrix(data);else if(view==='correlations')renderCorrelations(data);else if(view==='agreement')renderAgreement(data);else renderDiagnostics(data)}
async function saveCurrent(){const name=prompt('Workspace name','Research workspace');if(!name)return;await saveWorkspace({name,view:currentView()});await renderWorkspaces()}
async function renderWorkspaces(){const root=document.getElementById('analyticsWorkspaces');if(!root)return;const list=await allWorkspaces();root.innerHTML=list.map(w=>`<button data-load-workspace="${w.id}" data-view="${esc(w.view)}">${esc(w.name)}</button>`).join('')||'<span>No saved workspaces.</span>'}
async function openConsole(view){document.getElementById('analyticsDialog')?.showModal();if(view)document.getElementById('analyticsView').value=view;render();renderWorkspaces()}
function initUi(){document.getElementById('analyticsClose')?.addEventListener('click',()=>document.getElementById('analyticsDialog')?.close());document.getElementById('analyticsView')?.addEventListener('change',render);document.getElementById('analyticsRefresh')?.addEventListener('click',()=>{cache=null;render()});document.getElementById('analyticsSaveWorkspace')?.addEventListener('click',saveCurrent);document.getElementById('analyticsWorkspaces')?.addEventListener('click',e=>{const b=e.target.closest('[data-load-workspace]');if(!b)return;document.getElementById('analyticsView').value=b.dataset.view||'primfusion';render()});document.getElementById('analyticsBody')?.addEventListener('click',async e=>{const pair=e.target.closest('[data-analytics-pair]')?.dataset.analyticsPair;if(pair){const d=snapshot();await drillDown(`PrimFusion · ${pair}`,d.pairImages[pair]||[]);return}const img=e.target.closest('[data-agreement-image]')?.dataset.agreementImage;if(img){await drillDown(`AI–Director comparison · ${img}`,[img]);return}const band=e.target.closest('[data-agreement-filter]')?.dataset.agreementFilter;if(band){const d=snapshot(),ids=d.agreementRows.filter(x=>band==='all'||(band==='high'&&x.agreement>=80)||(band==='mixed'&&x.agreement>=50&&x.agreement<80)||(band==='low'&&x.agreement<50)).map(x=>x.imageId);await drillDown(`AI–Director agreement · ${band}`,ids)}});document.getElementById('reportsAnalyticsOpen')?.addEventListener('click',()=>openConsole())}
async function integrity(){const d=snapshot(),issues=[];for(const x of d.agreementRows)if(x.agreement<0||x.agreement>100)issues.push({type:'invalid-agreement',imageId:x.imageId,value:x.agreement});return{checkedAt:now(),recordCount:d.recordCount,pairCount:d.possiblePairs.length,issueCount:issues.length,issues}}
const api={snapshot,openConsole,saveWorkspace,allWorkspaces,drillDown,integrity};window.genreactrixAnalyticsEngine=api;window.addEventListener('DOMContentLoaded',()=>{initUi();renderWorkspaces()});['genreactrix:image-record','genreactrix:director','genreactrix:report'].forEach(t=>window.addEventListener(t,()=>{cache=null;if(document.getElementById('analyticsDialog')?.open)render()}));
})();
