(()=>{
'use strict';
const DB='genreactrix-consensus-v1', VERSION=1;
const STORES={records:'records',runs:'runs'};
const now=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORES.records)){const s=db.createObjectStore(STORES.records,{keyPath:'id'});s.createIndex('imageId','imageId');s.createIndex('voteType','voteType');s.createIndex('computedAt','computedAt');s.createIndex('sourceBatchId','sourceBatchId')}if(!db.objectStoreNames.contains(STORES.runs)){const s=db.createObjectStore(STORES.runs,{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('scope','scope')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function all(store){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function put(store,value){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=()=>resolve(value);r.onerror=()=>reject(r.error)})}
async function remove(store,id){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>resolve(true);r.onerror=()=>reject(r.error)})}
const normalizeValues=v=>Array.isArray(v)?v.map(String).filter(Boolean):String(v??'').split('|').map(x=>x.trim()).filter(Boolean);
const key=(imageId,voteType)=>`${imageId}::${voteType}`;
function directorFor(imageId,voteType){const rec=window.genreactrixImageRecordEngine?.get?.(imageId,{touch:false});const d=rec?.analysis?.director||{};if(voteType==='reaction')return (d.reactions||[]).map(String);if(voteType==='theme')return (d.themes||[]).filter(Boolean).map(String);if(voteType==='primfusion')return d.primFusion?[String(d.primFusion)]:[];return []}
function entropy(options,totalWeight){if(!totalWeight||options.length<2)return 0;const h=-options.reduce((sum,o)=>{const p=o.weight/totalWeight;return p>0?sum+p*Math.log2(p):sum},0);return h/Math.log2(options.length)}
function confidence(topShare,participants,totalWeight){const sample=Math.min(1,Math.log10(Math.max(1,participants)+1)/2);const weighted=Math.min(1,totalWeight/Math.max(1,participants));return Math.max(0,Math.min(1,(topShare*.72)+(sample*.2)+(weighted*.08)))}
function computeGroup(votes,previous){
 const optionMap=new Map(), participantSet=new Set(), batchSet=new Set(), datasetSet=new Set();let totalWeight=0;
 for(const vote of votes){const w=Math.max(0,Number(vote.weight)||1);participantSet.add(String(vote.participantId||vote.id));if(vote.sourceBatchId)batchSet.add(String(vote.sourceBatchId));if(vote.metadata?.datasetVersion)datasetSet.add(String(vote.metadata.datasetVersion));for(const value of normalizeValues(vote.value)){const o=optionMap.get(value)||{value,count:0,weight:0};o.count++;o.weight+=w;optionMap.set(value,o);totalWeight+=w}}
 const options=[...optionMap.values()].sort((a,b)=>b.weight-a.weight||a.value.localeCompare(b.value));for(const o of options)o.share=totalWeight?o.weight/totalWeight:0;
 const top=options[0]||null,second=options[1]||null,topShare=top?.share||0,normalizedEntropy=entropy(options,totalWeight),controversy=Math.max(0,Math.min(1,(normalizedEntropy*.7)+((1-topShare)*.3)));
 const director=directorFor(votes[0]?.imageId,votes[0]?.voteType);const directorSet=new Set(director);const topAgreement=top?directorSet.has(top.value):false;const anyAgreement=options.some(o=>directorSet.has(o.value));
 const stability=previous?{previousTop:previous.topValue||null,topUnchanged:previous.topValue===top?.value,shareDelta:Number(((topShare||0)-(previous.topShare||0)).toFixed(4))}:null;
 return {participants:participantSet.size,totalVotes:votes.length,totalWeight,options,topValue:top?.value||null,topShare:Number(topShare.toFixed(4)),margin:Number(((top?.share||0)-(second?.share||0)).toFixed(4)),confidence:Number(confidence(topShare,participantSet.size,totalWeight).toFixed(4)),controversy:Number(controversy.toFixed(4)),directorValues:director,directorTopAgreement:topAgreement,directorAnyAgreement:anyAgreement,sourceBatchIds:[...batchSet],datasetVersions:[...datasetSet],stability};
}
async function calculate(options={}){
 const votes=await window.genreactrixCommunityInputEngine?.allVotes?.()||[];const prior=await all(STORES.records);const priorMap=new Map(prior.map(r=>[r.id,r]));let selected=votes;
 if(options.importId)selected=selected.filter(v=>v.importId===options.importId);if(options.sourceBatchId)selected=selected.filter(v=>v.sourceBatchId===options.sourceBatchId);if(options.imageIds?.length){const ids=new Set(options.imageIds.map(String));selected=selected.filter(v=>ids.has(String(v.imageId)))}
 const groups=new Map();for(const vote of selected){const k=key(vote.imageId,vote.voteType);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(vote)}
 const run={id:uid('consensus-run'),schemaVersion:1,scope:options.importId?'import':options.sourceBatchId?'source-batch':options.imageIds?.length?'selected':'all',scopeValue:options.importId||options.sourceBatchId||null,createdAt:now(),voteCount:selected.length,recordCount:groups.size,status:'completed'};
 const records=[];for(const [id,rows] of groups){const calc=computeGroup(rows,priorMap.get(id));const rec={id,imageId:String(rows[0].imageId),voteType:String(rows[0].voteType),schemaVersion:1,computedAt:run.createdAt,runId:run.id,...calc};await put(STORES.records,rec);records.push(rec)}await put(STORES.runs,run);
 try{await window.genreactrixHistoryEngine?.append?.({eventType:'consensus-calculated',summary:`Calculated ${records.length} consensus records from ${selected.length} votes`,createdAt:run.createdAt,details:{runId:run.id,scope:run.scope}})}catch{}
 return {run,records};
}
async function summary(){const records=await all(STORES.records),runs=await all(STORES.runs);const controversial=records.filter(r=>r.controversy>=.55).length,lowConfidence=records.filter(r=>r.confidence<.5).length,agreements=records.filter(r=>r.directorTopAgreement).length;return {records:records.length,runs:runs.length,controversial,lowConfidence,directorAgreementRate:records.length?agreements/records.length:0,lastRun:runs.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]||null}}
async function query(filters={}){let rows=await all(STORES.records);if(filters.voteType)rows=rows.filter(r=>r.voteType===filters.voteType);if(filters.imageId)rows=rows.filter(r=>r.imageId===String(filters.imageId));if(filters.controversial)rows=rows.filter(r=>r.controversy>=Number(filters.controversy));if(filters.maxConfidence!=null)rows=rows.filter(r=>r.confidence<=Number(filters.maxConfidence));if(filters.directorAgreement==='agree')rows=rows.filter(r=>r.directorTopAgreement);if(filters.directorAgreement==='disagree')rows=rows.filter(r=>!r.directorTopAgreement);return rows.sort((a,b)=>b.controversy-a.controversy||b.participants-a.participants)}
async function batchAnalytics(sourceBatchId){const rows=(await query({})).filter(r=>r.sourceBatchIds.includes(String(sourceBatchId)));return {sourceBatchId,records:rows.length,averageConfidence:rows.length?rows.reduce((s,r)=>s+r.confidence,0)/rows.length:0,averageControversy:rows.length?rows.reduce((s,r)=>s+r.controversy,0)/rows.length:0,directorAgreementRate:rows.length?rows.filter(r=>r.directorTopAgreement).length/rows.length:0,mostControversial:rows.slice().sort((a,b)=>b.controversy-a.controversy).slice(0,10)}}
async function verify(){const rows=await all(STORES.records),issues=[];for(const r of rows){if(!r.imageId)issues.push({severity:'critical',type:'consensus-missing-image',id:r.id});if(!['reaction','theme','primfusion'].includes(r.voteType))issues.push({severity:'attention',type:'consensus-invalid-vote-type',id:r.id});if(r.topShare<0||r.topShare>1||r.confidence<0||r.confidence>1||r.controversy<0||r.controversy>1)issues.push({severity:'critical',type:'consensus-invalid-score',id:r.id});if(!Array.isArray(r.options))issues.push({severity:'critical',type:'consensus-options-missing',id:r.id})}return {checked:rows.length,issues}}
async function clear(){for(const r of await all(STORES.records))await remove(STORES.records,r.id);for(const r of await all(STORES.runs))await remove(STORES.runs,r.id);return true}
window.genreactrixConsensusEngine={calculate,summary,query,batchAnalytics,allRecords:()=>all(STORES.records),allRuns:()=>all(STORES.runs),verify,clear};
})();
