/* Genreactrix AI Worker v0.9.6.0 — adapted from Billy Labs' proven Workers AI vision route. */
const API_VERSION='0.9.6.0';
const cors={'access-control-allow-origin':'*','access-control-allow-methods':'GET, POST, OPTIONS','access-control-allow-headers':'content-type, x-analysis-key'};
const json=(body,init={})=>new Response(JSON.stringify(body),{...init,headers:{...cors,'content-type':'application/json; charset=utf-8',...(init.headers||{})}});
const DEFAULT_MODEL='@cf/meta/llama-3.2-11b-vision-instruct';
const COMPONENT_IDS=['reactions','themes','description','emotion','reactionReasons','genreReasons'];
const strip=text=>String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();
const parse=text=>{const clean=strip(text);try{return JSON.parse(clean)}catch{const a=clean.indexOf('{'),b=clean.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(clean.slice(a,b+1));throw new Error('Vision provider returned invalid JSON')}};
const responseText=p=>typeof p==='string'?p:(p?.response||p?.result?.response||p?.output_text||'');
const fetchBytes=async url=>{if(!/^https:\/\//i.test(url)||url.length>2000)throw new Error('imageUrl must be HTTPS');const r=await fetch(url,{headers:{accept:'image/*'}});if(!r.ok)throw new Error(`Could not retrieve image (${r.status})`);const bytes=new Uint8Array(await r.arrayBuffer());if(!bytes.length)throw new Error('Image was empty');if(bytes.length>6_000_000)throw new Error('Image exceeds 6 MB');return Array.from(bytes)};
const dataUrlBytes=value=>{const m=String(value||'').match(/^data:image\/[a-zA-Z0-9.+-]+;base64,(.+)$/);if(!m)throw new Error('imageDataUrl must be a base64 image');const binary=atob(m[1]);if(binary.length>6_000_000)throw new Error('Image exceeds 6 MB');return Array.from(binary,c=>c.charCodeAt(0))};
const validateResult=(result,requested)=>{if(!result||typeof result!=='object'||!result.components||typeof result.components!=='object')throw new Error('Provider returned no components object');const out={};for(const id of requested){if(Object.prototype.hasOwnProperty.call(result.components,id))out[id]=result.components[id]}return out};
const promptFor=components=>`You are Genreactrix, a rigorous visual-research analyst. Analyze only visible evidence in the image. Do not infer hidden identity or backstory. Return only one JSON object with top-level shape {"components":{...},"promptVersions":{...}}. Include only requested components: ${components.join(', ')}.

Component contracts:
- reactions: object keyed by these reaction names: Beautiful, Adorable, Tragic, Funny, Intense, Weird, Hell, Dreamy, Zazzly, Disgusting, Eerie, Smart, Celebration. Each value is {"confidence":0-100,"reason":"visual evidence and emotional mechanism"}.
- themes: array of {"theme":"string","confidence":0-100,"evidence":"string","role":"primary|secondary|ambiguous"}.
- description: detailed factual description of subjects, objects, actions, setting, composition, style, visible text, and unusual juxtapositions.
- emotion: {"dominant":[],"secondary":[],"tone":"string","intensity":0-100,"contrasts":[],"causes":[]}.
- reactionReasons: object keyed by relevant reaction name with detailed rationalization of why a viewer may feel it.
- genreReasons: array of {"theme":"string","reason":"string","evidence":[]}.
Set promptVersions for each returned component to "genreactrix-v1". Do not wrap JSON in Markdown.`;
async function analyze(env,body){if(!env.AI?.run)throw new Error('Workers AI binding AI is not configured');const requested=[...new Set((body.components||[]).filter(x=>COMPONENT_IDS.includes(x)))];if(!body.imageId||!requested.length)throw new Error('imageId and components are required');const image=body.imageDataUrl?dataUrlBytes(body.imageDataUrl):await fetchBytes(body.imageUrl);const model=env.WORKERS_AI_VISION_MODEL||DEFAULT_MODEL;let payload;try{payload=await env.AI.run(model,{prompt:promptFor(requested),image,max_tokens:2600,temperature:0.1})}catch(error){throw new Error(`Workers AI vision failed: ${error?.message||error}`)}const raw=responseText(payload);if(!raw)throw new Error('Workers AI returned no analysis text');const result=parse(raw);return{schemaVersion:1,imageId:body.imageId,analyzedAt:new Date().toISOString(),provider:{id:'cloudflare-workers-ai',displayName:'Genreactrix Vision · Cloudflare Workers AI',model},model,promptVersions:result.promptVersions||Object.fromEntries(requested.map(id=>[id,'genreactrix-v1'])),components:validateResult(result,requested)}}
export default{async fetch(request,env={}){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...cors,'access-control-max-age':'86400'}});if(request.method==='GET'&&url.pathname==='/api/health')return json({ok:true,service:'Genreactrix AI',version:API_VERSION,vision:env.AI?'configured':'not-configured',provider:'cloudflare-workers-ai'});try{if(request.method==='POST'&&url.pathname==='/api/genreactrix/analyze'){if(!env.ANALYSIS_KEY)return json({ok:false,error:'Analysis access is not configured'},{status:503});if(request.headers.get('x-analysis-key')!==env.ANALYSIS_KEY)return json({ok:false,error:'Unauthorized'},{status:401});const body=await request.json().catch(()=>null);if(!body)return json({ok:false,error:'JSON body required'},{status:400});return json({ok:true,result:await analyze(env,body)})}}catch(error){return json({ok:false,error:error.message},{status:500})}return json({ok:false,error:'Not found'},{status:404})}};
