/* Genreactrix Portable Persistence Engine v1 — v0.9.40.39
   Verified local backup/restore for the current browser-local model.
   Preserves IndexedDB schema, keys, indexes, binary Blob/File bytes, and the
   Project/Runtime boundary. This is portability/migration, not cloud sync. */
(()=>{'use strict';
const BUILD='0.9.40.39', TYPE='genreactrix-backup', SCHEMA=3, ENCODING='genreactrix-portable-idb-v1';
const TAG='__genreactrixPortableType';
const now=()=>new Date().toISOString();
const clone=v=>v==null?v:structuredClone(v);
const hex=buf=>[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('');
function bytesToBase64(bytes){let out='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)out+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+chunk)));return btoa(out)}
function base64ToBytes(text){const raw=atob(String(text||'')),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function sha256Text(text){if(!crypto?.subtle)throw new Error('Web Crypto SHA-256 is required for verified backups');return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))}
async function encodeValue(value,stats={binaryCount:0,binaryBytes:0}){
  if(value===undefined)return{[TAG]:'Undefined'};
  if(typeof value==='bigint')return{[TAG]:'BigInt',value:String(value)};
  if(value===null||typeof value!=='object')return value;
  if(typeof File!=='undefined'&&value instanceof File){const bytes=new Uint8Array(await value.arrayBuffer());stats.binaryCount++;stats.binaryBytes+=bytes.byteLength;return{[TAG]:'File',name:value.name||'',type:value.type||'',lastModified:Number(value.lastModified)||0,size:bytes.byteLength,data:bytesToBase64(bytes)}}
  if(typeof Blob!=='undefined'&&value instanceof Blob){const bytes=new Uint8Array(await value.arrayBuffer());stats.binaryCount++;stats.binaryBytes+=bytes.byteLength;return{[TAG]:'Blob',type:value.type||'',size:bytes.byteLength,data:bytesToBase64(bytes)}}
  if(value instanceof ArrayBuffer){const bytes=new Uint8Array(value);stats.binaryCount++;stats.binaryBytes+=bytes.byteLength;return{[TAG]:'ArrayBuffer',size:bytes.byteLength,data:bytesToBase64(bytes)}}
  if(ArrayBuffer.isView(value)){const bytes=new Uint8Array(value.buffer,value.byteOffset,value.byteLength);stats.binaryCount++;stats.binaryBytes+=bytes.byteLength;return{[TAG]:'TypedArray',ctor:value.constructor?.name||'Uint8Array',size:bytes.byteLength,data:bytesToBase64(bytes)}}
  if(value instanceof Date)return{[TAG]:'Date',value:value.toISOString()};
  if(value instanceof RegExp)return{[TAG]:'RegExp',source:value.source,flags:value.flags};
  if(value instanceof Map){const entries=[];for(const [k,v] of value)entries.push([await encodeValue(k,stats),await encodeValue(v,stats)]);return{[TAG]:'Map',entries}}
  if(value instanceof Set){const values=[];for(const v of value)values.push(await encodeValue(v,stats));return{[TAG]:'Set',values}}
  if(Array.isArray(value)){const out=[];for(const item of value)out.push(await encodeValue(item,stats));return out}
  const out={};for(const [k,v] of Object.entries(value))out[k]=await encodeValue(v,stats);return out;
}
function decodeValue(value){
  if(value===null||typeof value!=='object')return value;
  if(Array.isArray(value))return value.map(decodeValue);
  const type=value[TAG];
  if(type==='Undefined')return undefined;
  if(type==='BigInt')return BigInt(value.value);
  if(type==='Date')return new Date(value.value);
  if(type==='RegExp')return new RegExp(value.source||'',value.flags||'');
  if(type==='Blob'){const bytes=base64ToBytes(value.data);if(Number(value.size)!==bytes.byteLength)throw new Error('Backup Blob byte count mismatch');return new Blob([bytes],{type:value.type||''})}
  if(type==='File'){const bytes=base64ToBytes(value.data);if(Number(value.size)!==bytes.byteLength)throw new Error('Backup File byte count mismatch');return typeof File!=='undefined'?new File([bytes],value.name||'file',{type:value.type||'',lastModified:Number(value.lastModified)||0}):new Blob([bytes],{type:value.type||''})}
  if(type==='ArrayBuffer'){const bytes=base64ToBytes(value.data);if(Number(value.size)!==bytes.byteLength)throw new Error('Backup ArrayBuffer byte count mismatch');return bytes.buffer}
  if(type==='TypedArray'){const bytes=base64ToBytes(value.data);if(Number(value.size)!==bytes.byteLength)throw new Error('Backup typed-array byte count mismatch');const C=globalThis[value.ctor]||Uint8Array;if(C===DataView)return new DataView(bytes.buffer);const width=C.BYTES_PER_ELEMENT||1;if(bytes.byteLength%width)return new Uint8Array(bytes);return new C(bytes.buffer)}
  if(type==='Map')return new Map((value.entries||[]).map(([k,v])=>[decodeValue(k),decodeValue(v)]));
  if(type==='Set')return new Set((value.values||[]).map(decodeValue));
  const out={};for(const [k,v] of Object.entries(value))out[k]=decodeValue(v);return out;
}
function requestResult(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('IndexedDB request failed'))})}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('IndexedDB transaction failed'));tx.onabort=()=>reject(tx.error||new Error('IndexedDB transaction aborted'))})}
function openDb(name,version){return new Promise((resolve,reject)=>{const r=version==null?indexedDB.open(name):indexedDB.open(name,version);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error(`Could not open ${name}`))})}
function deleteDb(name){return new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(name);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error||new Error(`Could not delete ${name}`));r.onblocked=()=>reject(new Error(`Database ${name} is still open`))})}
async function databaseNames(){if(typeof indexedDB.databases!=='function')throw new Error('This browser cannot enumerate IndexedDB databases; a verified full backup cannot be created here.');return (await indexedDB.databases()).map(x=>x.name).filter(n=>n&&n.startsWith('genreactrix-')).sort()}
function keyPathValue(v){if(Array.isArray(v))return [...v];return v==null?null:String(v)}
function schemaForStore(store,scope){const indexes=[...store.indexNames].map(name=>{const idx=store.index(name);return{name:String(name),keyPath:keyPathValue(idx.keyPath),unique:Boolean(idx.unique),multiEntry:Boolean(idx.multiEntry)}});return{keyPath:keyPathValue(store.keyPath),autoIncrement:Boolean(store.autoIncrement),scope,indexes}}
async function captureStore(db,name,ctx,stats){const tx=db.transaction(name,'readonly'),store=tx.objectStore(name),schema=schemaForStore(store,ctx?.storageScope?.(db.name,name)||'project');const valuesPromise=requestResult(store.getAll()),keysPromise=requestResult(store.getAllKeys()),done=txDone(tx);const [values,keys]=await Promise.all([valuesPromise,keysPromise,done]).then(x=>[x[0],x[1]]);if(values.length!==keys.length)throw new Error(`${db.name}/${name}: key/value count mismatch while backing up`);const entries=[];for(let i=0;i<values.length;i++)entries.push({key:await encodeValue(keys[i],stats),value:await encodeValue(values[i],stats)});const digest=await sha256Text(JSON.stringify(entries));return{schema,recordCount:entries.length,digest,entries}}
async function captureDatabase(name,ctx,stats){const db=await openDb(name);try{const stores=[...db.objectStoreNames],out={};for(const store of stores)out[store]=await captureStore(db,store,ctx,stats);return{name,version:db.version,scope:ctx?.databaseScope?.(name,stores)||'project',stores:out}}finally{db.close()}}
function projectLocalStorageSnapshot(projectId){const prefix=projectId?`genreactrix-project:${projectId}:`:'';const out={};if(!prefix)return out;try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith(prefix))out[key]=localStorage.getItem(key)}}catch{}return out}
function recordCount(dbs=[]){return dbs.reduce((n,d)=>n+Object.values(d.stores||{}).reduce((s,v)=>s+Number(v.recordCount||v.entries?.length||0),0),0)}
async function createBackup({mode='data'}={}){const ctx=window.genreactrixProjectRuntimeEngine;if(ctx?.ready)await ctx.ready;await ctx?.migrateLegacyProjectKeys?.();await ctx?.migrateProjectScopedRecords?.();const names=await databaseNames(),stats={binaryCount:0,binaryBytes:0},databases=[];for(const name of names)databases.push(await captureDatabase(name,ctx,stats));const projectId=ctx?.projectId?.()||window.genreactrixSettingsEngine?.get?.('project.id')||'',runtimeId=ctx?.runtimeId?.()||null,scopeCounts={project:0,runtime:0,mixed:0};for(const d of databases)scopeCounts[d.scope in scopeCounts?d.scope:'project']++;const payload={type:TYPE,schemaVersion:SCHEMA,encoding:ENCODING,build:BUILD,mode,createdAt:now(),projectId,sourceRuntimeId:runtimeId,scopeModel:'project+runtime-local',settings:await window.genreactrixSettingsEngine?.exportSettings?.({includeSensitive:false}),projectLocalStorage:projectLocalStorageSnapshot(projectId),databases,manifest:{databaseCount:databases.length,projectDatabaseCount:scopeCounts.project,runtimeDatabaseCount:scopeCounts.runtime,mixedDatabaseCount:scopeCounts.mixed,recordCount:recordCount(databases),binaryCount:stats.binaryCount,binaryBytes:stats.binaryBytes,portableBinaryBytes:true,preservesSchema:true,preservesIndexes:true,note:'Portable local backup: logical Project data plus runtime-local assets. Source Runtime provenance is preserved; the target Runtime remains distinct on restore.'}};payload.integrity={algorithm:'SHA-256',digest:await sha256Text(JSON.stringify(payload))};return payload}
async function verifyPayload(payload){if(payload?.type!==TYPE)throw new Error('Not a complete Genreactrix backup');if(Number(payload.schemaVersion)<SCHEMA||payload.encoding!==ENCODING)throw new Error('Legacy backup format is not safe for full restore because binary/schema preservation cannot be verified');const expected=payload.integrity?.digest;if(!expected)throw new Error('Backup integrity digest is missing');const copy=clone(payload);delete copy.integrity;const actual=await sha256Text(JSON.stringify(copy));if(actual!==expected)throw new Error('Backup integrity check failed');let binaryCount=0,binaryBytes=0,records=0;for(const db of payload.databases||[])for(const store of Object.values(db.stores||{})){records+=store.entries?.length||0;for(const entry of store.entries||[]){const walk=v=>{if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach(walk);return}if(['Blob','File','ArrayBuffer','TypedArray'].includes(v[TAG])){binaryCount++;binaryBytes+=Number(v.size)||0;return}Object.values(v).forEach(walk)};walk(entry.key);walk(entry.value)}}if(records!==Number(payload.manifest?.recordCount||records))throw new Error('Backup manifest record count mismatch');if(binaryCount!==Number(payload.manifest?.binaryCount||0)||binaryBytes!==Number(payload.manifest?.binaryBytes||0))throw new Error('Backup binary manifest mismatch');return{ok:true,projectId:payload.projectId||'',build:payload.build||'',createdAt:payload.createdAt||'',databaseCount:payload.databases?.length||0,recordCount:records,binaryCount,binaryBytes,sourceRuntimeId:payload.sourceRuntimeId||null}}
async function previewFile(file){const text=await file.text(),payload=JSON.parse(text);const verification=await verifyPayload(payload);return{payload,summary:{...verification,schemaVersion:payload.schemaVersion,encoding:payload.encoding}}}
function sameKeyPath(a,b){return JSON.stringify(keyPathValue(a))===JSON.stringify(keyPathValue(b))}
function validateStoreSchema(store,dump,dbName,storeName){const schema=dump.schema||{};if(!sameKeyPath(store.keyPath,schema.keyPath)||Boolean(store.autoIncrement)!==Boolean(schema.autoIncrement))throw new Error(`${dbName}/${storeName}: object-store schema mismatch`);for(const expected of schema.indexes||[]){if(!store.indexNames.contains(expected.name))throw new Error(`${dbName}/${storeName}: missing index ${expected.name}`);const idx=store.index(expected.name);if(!sameKeyPath(idx.keyPath,expected.keyPath)||Boolean(idx.unique)!==Boolean(expected.unique)||Boolean(idx.multiEntry)!==Boolean(expected.multiEntry))throw new Error(`${dbName}/${storeName}/${expected.name}: index schema mismatch`)}}
function createStoreFromDump(db,name,dump){const schema=dump.schema||{},options={autoIncrement:Boolean(schema.autoIncrement)};if(schema.keyPath!==null&&schema.keyPath!==undefined)options.keyPath=schema.keyPath;const store=db.createObjectStore(name,options);for(const idx of schema.indexes||[])store.createIndex(idx.name,idx.keyPath,{unique:Boolean(idx.unique),multiEntry:Boolean(idx.multiEntry)});return store}
async function createDatabaseFromDump(dump){return new Promise((resolve,reject)=>{const r=indexedDB.open(dump.name,Math.max(1,Number(dump.version)||1));r.onupgradeneeded=()=>{const db=r.result;for(const [name,storeDump] of Object.entries(dump.stores||{}))createStoreFromDump(db,name,storeDump)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error(`Could not recreate ${dump.name}`))})}
async function putStoreEntries(db,dbName,storeName,dump,{merge}){if(!db.objectStoreNames.contains(storeName))throw new Error(`${dbName}: missing object store ${storeName}`);const tx=db.transaction(storeName,'readwrite'),store=tx.objectStore(storeName);validateStoreSchema(store,dump,dbName,storeName);if(!merge)store.clear();for(const entry of dump.entries||[]){const value=decodeValue(entry.value),key=decodeValue(entry.key);if(store.keyPath==null)store.put(value,key);else store.put(value)}await txDone(tx);return dump.entries?.length||0}
async function restoreDatabase(dump,{merge}){let db;if(merge){db=await openDb(dump.name);for(const [name,storeDump] of Object.entries(dump.stores||{})){if(!db.objectStoreNames.contains(name)){db.close();throw new Error(`${dump.name}: current database lacks store ${name}; use Replace restore with a compatible backup`)}}}else db=await createDatabaseFromDump(dump);try{let count=0;for(const [name,storeDump] of Object.entries(dump.stores||{}))count+=await putStoreEntries(db,dump.name,name,storeDump,{merge});return count}finally{db.close()}}
async function restoreProjectLocalStorage(payload){const ctx=window.genreactrixProjectRuntimeEngine,pid=payload.projectId||'';if(pid)await ctx?.bindProject?.(pid,{name:payload.settings?.values?.['project.name'],directorId:payload.settings?.values?.['project.directorId']});for(const [key,value] of Object.entries(payload.projectLocalStorage||{})){try{localStorage.setItem(key,String(value))}catch{}}for(const key of ['genreactrix-custom-reactions-v1','genreactrix-custom-themes-v2','genreactrix-evaluation-vocabulary-version-v1','genreactrix-evaluation-vocabulary-used-v1'])await ctx?.mirrorProjectValueToLocal?.(key).catch(()=>{});await ctx?.registerRuntime?.({projectId:pid});await window.genreactrixImagesEngine?.backfillRuntimeAssetLocations?.().catch?.(()=>{});}
async function restoreBackup(payload,{mode='merge'}={}){if(!['merge','replace'].includes(mode))throw new Error('Restore mode must be merge or replace');const verification=await verifyPayload(payload),ctx=window.genreactrixProjectRuntimeEngine;if(ctx?.ready)await ctx.ready;const currentProject=ctx?.projectId?.()||'';if(mode==='merge'&&verification.projectId&&currentProject&&verification.projectId!==currentProject)throw new Error(`Merge requires the same Project ID. Backup is ${verification.projectId}; current Project is ${currentProject}. Use Replace to adopt the backup Project.`);let restoredDatabases=0,restoredRecords=0;const existingNames=new Set(await databaseNames());if(mode==='replace'){for(const name of existingNames)await deleteDb(name);existingNames.clear()}for(const dump of payload.databases||[]){const mergeExisting=mode==='merge'&&existingNames.has(dump.name);restoredRecords+=await restoreDatabase(dump,{merge:mergeExisting});existingNames.add(dump.name);restoredDatabases++}await restoreProjectLocalStorage(payload);if(payload.settings)await window.genreactrixSettingsEngine?.importSettings?.(payload.settings,{includeSensitive:false});await ctx?.registerRuntime?.({projectId:payload.projectId});return{mode,projectId:payload.projectId,sourceRuntimeId:payload.sourceRuntimeId||null,targetRuntimeId:ctx?.runtimeId?.()||null,databases:restoredDatabases,records:restoredRecords,binaryCount:verification.binaryCount,binaryBytes:verification.binaryBytes,requiresReload:true}}
function downloadJson(data,name){const blob=new Blob([JSON.stringify(data)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function verify(){const issues=[],ctx=window.genreactrixProjectRuntimeEngine;if(typeof indexedDB?.databases!=='function')issues.push({type:'persistence-database-enumeration-unavailable',severity:'attention',summary:'Verified full backup cannot enumerate IndexedDB databases in this browser.'});if(!crypto?.subtle)issues.push({type:'persistence-sha256-unavailable',severity:'critical',summary:'Verified backup integrity requires Web Crypto SHA-256.'});if(ctx?.ready)await ctx.ready;if(!ctx?.projectId?.())issues.push({type:'persistence-missing-project-context',severity:'attention'});if(!ctx?.runtimeId?.())issues.push({type:'persistence-missing-runtime-context',severity:'attention'});let databaseCount=null;try{databaseCount=(await databaseNames()).length}catch{}return{checkedAt:now(),projectId:ctx?.projectId?.()||'',runtimeId:ctx?.runtimeId?.()||'',databaseCount,issueCount:issues.length,issues}}
const api={BUILD,TYPE,SCHEMA,ENCODING,encodeValue,decodeValue,createBackup,verifyPayload,previewFile,restoreBackup,downloadJson,databaseNames,verify};
window.genreactrixPersistenceEngine=api;
window.addEventListener('DOMContentLoaded',()=>window.genreactrixMaintenanceEngine?.registerChecker?.('persistence',verify,{quick:false,label:'Portable Persistence'}));
})();
