(()=>{
'use strict';
const now=()=>new Date().toISOString();
const allowed={draft:['review','archived'],review:['draft','published','archived'],published:['archived'],archived:['draft']};
async function transition(id,next){const kb=window.genreactrixKnowledgeBaseEngine;if(!kb)throw new Error('Knowledge Base unavailable');const entry=await kb.getEntry(id);if(!entry)throw new Error('Publication not found');if(!(allowed[entry.status]||[]).includes(next))throw new Error(`Cannot move ${entry.status} to ${next}`);const patch={status:next};if(next==='published')patch.publishedAt=now();if(next==='archived')patch.archivedAt=now();return kb.reviseEntry(id,patch)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toMarkdown(e){return `# ${e.title}\n\n${e.summary||''}\n\n${e.body||''}\n\n## Evidence\n\n- Sample size: ${e.evidence?.sampleSize||0}\n- Confidence: ${e.evidence?.confidence||0}\n- Images: ${(e.evidence?.imageIds||[]).join(', ')||'None'}\n- Reports: ${(e.evidence?.reportIds||[]).join(', ')||'None'}\n`}
function toHtml(e){return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(e.title)}</title></head><body><article><h1>${esc(e.title)}</h1><p>${esc(e.summary)}</p><div>${esc(e.body).replace(/\n/g,'<br>')}</div><h2>Evidence</h2><p>Sample size: ${e.evidence?.sampleSize||0}</p><p>Confidence: ${e.evidence?.confidence||0}</p></article></body></html>`}
async function exportEntry(id,format='json'){const e=await window.genreactrixKnowledgeBaseEngine.getEntry(id);if(!e)throw new Error('Publication not found');let body,type,ext;if(format==='markdown'){body=toMarkdown(e);type='text/markdown';ext='md'}else if(format==='html'){body=toHtml(e);type='text/html';ext='html'}else{body=JSON.stringify(e,null,2);type='application/json';ext='json'}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=`${e.title.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'publication'}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function render(){const body=document.getElementById('knowledgeBaseBody');if(!body)return;const q=document.getElementById('knowledgeSearch')?.value||'';const r=await window.genreactrixKnowledgeBaseEngine.search(q);body.innerHTML='';const rows=[...r.entries];if(!rows.length){body.innerHTML='<p class="empty-state">No knowledge entries yet.</p>';return}for(const e of rows){const card=document.createElement('article');card.className='knowledge-card';card.innerHTML=`<header><div><strong>${esc(e.title)}</strong><small>${esc(e.type)} · ${esc(e.status)} · rev ${e.revision}</small></div></header><p>${esc(e.summary)}</p><div class="knowledge-evidence">Evidence: ${(e.evidence?.imageIds||[]).length} images · ${(e.evidence?.reportIds||[]).length} reports · sample ${e.evidence?.sampleSize||0}</div><div class="knowledge-actions"><button data-kb-action="review" data-id="${e.id}">Review</button><button data-kb-action="publish" data-id="${e.id}">Publish</button><button data-kb-action="archive" data-id="${e.id}">Archive</button><button data-kb-action="json" data-id="${e.id}">JSON</button><button data-kb-action="markdown" data-id="${e.id}">Markdown</button><button data-kb-action="html" data-id="${e.id}">HTML</button></div>`;body.appendChild(card)}}
async function createFromForm(){const title=document.getElementById('knowledgeTitle').value.trim();if(!title)throw new Error('Title required');await window.genreactrixKnowledgeBaseEngine.createEntry({title,summary:document.getElementById('knowledgeSummary').value,body:document.getElementById('knowledgeBodyText').value,type:document.getElementById('knowledgeType').value,status:'draft'});document.getElementById('knowledgeTitle').value='';document.getElementById('knowledgeSummary').value='';document.getElementById('knowledgeBodyText').value='';await render()}
function init(){const dialog=document.getElementById('knowledgeBaseDialog');if(!dialog)return;document.getElementById('knowledgeBaseClose')?.addEventListener('click',()=>dialog.close());document.getElementById('knowledgeSearch')?.addEventListener('input',render);document.getElementById('knowledgeCreate')?.addEventListener('click',()=>createFromForm().catch(e=>document.getElementById('knowledgeStatus').textContent=e.message));document.getElementById('knowledgeBaseBody')?.addEventListener('click',async ev=>{const b=ev.target.closest('[data-kb-action]');if(!b)return;try{const a=b.dataset.kbAction,id=b.dataset.id;if(['json','markdown','html'].includes(a))await exportEntry(id,a);else await transition(id,a==='review'?'review':a==='publish'?'published':'archived');await render()}catch(e){document.getElementById('knowledgeStatus').textContent=e.message}});window.openGenreactrixKnowledgeBase=()=>{dialog.showModal();render()};render()}
window.genreactrixPublicationEngine={transition,exportEntry,render};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
