(()=>{
'use strict';
const DB='genreactrix-terminology-v1', VERSION=1, STORE='terms';
const now=()=>new Date().toISOString();
const uid=()=>`term-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('canonicalName','canonicalName',{unique:false});s.createIndex('category','category',{unique:false});s.createIndex('status','status',{unique:false});s.createIndex('updatedAt','updatedAt',{unique:false})}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function tx(mode,fn){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE,mode),s=t.objectStore(STORE);let result;try{result=fn(s)}catch(e){reject(e);return}t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error)})}
async function getAll(){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve((r.result||[]).sort((a,b)=>a.canonicalName.localeCompare(b.canonicalName)));r.onerror=()=>reject(r.error)})}
async function get(id){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
function normalize(input={},existing=null){const canonicalName=String(input.canonicalName??existing?.canonicalName??'').trim();if(!canonicalName)throw new Error('Canonical name required');return {id:existing?.id||input.id||uid(),schemaVersion:1,canonicalName,definition:String(input.definition??existing?.definition??'').trim(),category:String(input.category??existing?.category??'general').trim()||'general',aliases:[...new Set((input.aliases??existing?.aliases??[]).map(v=>String(v).trim()).filter(Boolean))],status:input.status??existing?.status??'active',references:{publicationIds:[...(input.references?.publicationIds??existing?.references?.publicationIds??[])],findingIds:[...(input.references?.findingIds??existing?.references?.findingIds??[])],reportIds:[...(input.references?.reportIds??existing?.references?.reportIds??[])],imageIds:[...(input.references?.imageIds??existing?.references?.imageIds??[])],sessionIds:[...(input.references?.sessionIds??existing?.references?.sessionIds??[])]},revision:Number(existing?.revision||0)+1,revisionHistory:existing?[...(existing.revisionHistory||[]),{revision:existing.revision,canonicalName:existing.canonicalName,definition:existing.definition,aliases:existing.aliases,category:existing.category,status:existing.status,updatedAt:existing.updatedAt}]:[],createdAt:existing?.createdAt||now(),updatedAt:now()}}
async function save(input){const existing=input.id?await get(input.id):null;const item=normalize(input,existing);const all=await getAll();const duplicate=all.find(t=>t.id!==item.id&&t.canonicalName.toLowerCase()===item.canonicalName.toLowerCase());if(duplicate)throw new Error('Canonical term already exists');await tx('readwrite',s=>s.put(item));return item}
async function remove(id){await tx('readwrite',s=>s.delete(id));return true}
async function search(query='',options={}){const q=String(query).trim().toLowerCase();let rows=await getAll();if(options.category)rows=rows.filter(t=>t.category===options.category);if(options.status)rows=rows.filter(t=>t.status===options.status);if(q)rows=rows.filter(t=>[t.canonicalName,t.definition,t.category,(t.aliases||[]).join(' ')].some(v=>String(v||'').toLowerCase().includes(q)));return rows}
async function resolve(value){const q=String(value||'').trim().toLowerCase();if(!q)return null;const rows=await getAll();return rows.find(t=>t.canonicalName.toLowerCase()===q||(t.aliases||[]).some(a=>a.toLowerCase()===q))||null}
async function verify(){const rows=await getAll(),issues=[],names=new Map(),aliases=new Map();for(const t of rows){if(!t.canonicalName)issues.push({severity:'warning',type:'term-name-missing',id:t.id});const n=t.canonicalName.toLowerCase();if(names.has(n))issues.push({severity:'attention',type:'duplicate-canonical-term',ids:[names.get(n),t.id]});else names.set(n,t.id);for(const a of t.aliases||[]){const k=a.toLowerCase();if(names.has(k)&&names.get(k)!==t.id)issues.push({severity:'warning',type:'alias-conflicts-canonical',id:t.id,alias:a});if(aliases.has(k)&&aliases.get(k)!==t.id)issues.push({severity:'warning',type:'duplicate-alias',ids:[aliases.get(k),t.id],alias:a});else aliases.set(k,t.id)}}return {checked:rows.length,issues}}
window.genreactrixTerminologyEngine={save,get,getAll,search,resolve,remove,verify};
})();
