(()=>{
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>`${Math.round((Number(n)||0)*100)}%`;
async function render(){const e=window.genreactrixConsensusEngine;if(!e)return;const s=await e.summary();$('consensusStatus').textContent=`${s.records} records · ${s.controversial} controversial · ${pct(s.directorAgreementRate)} Director agreement`;const filters={voteType:$('consensusVoteType').value||'',directorAgreement:$('consensusAgreement').value||'',controversial:$('consensusControversialOnly').checked?.55:0};const rows=await e.query(filters);$('consensusBody').innerHTML=rows.map(r=>`<article class="consensus-row"><header><div><strong>${esc(r.imageId)}</strong><span>${esc(r.voteType)}</span></div><button type="button" data-consensus-image="${esc(r.imageId)}">Open image</button></header><div class="consensus-metrics"><span>Top <strong>${esc(r.topValue||'—')}</strong> ${pct(r.topShare)}</span><span>Confidence <strong>${pct(r.confidence)}</strong></span><span>Controversy <strong>${pct(r.controversy)}</strong></span><span>Participants <strong>${r.participants}</strong></span></div><p>Director: ${r.directorValues.length?esc(r.directorValues.join(', ')):'—'} · ${r.directorTopAgreement?'agrees':'differs'}</p><div class="consensus-options">${r.options.slice(0,6).map(o=>`<span>${esc(o.value)} ${pct(o.share)}</span>`).join('')}</div></article>`).join('')||'<p>No consensus records yet. Calculate consensus after importing community votes.</p>'}
async function calculate(){const b=$('consensusCalculate');b.disabled=true;try{const result=await window.genreactrixConsensusEngine.calculate();$('consensusStatus').textContent=`Calculated ${result.records.length} records from ${result.run.voteCount} votes.`;await render()}catch(err){$('consensusStatus').textContent=err.message}finally{b.disabled=false}}
function bind(){const d=$('consensusDialog');$('consensusClose')?.addEventListener('click',()=>d.close());$('consensusCalculate')?.addEventListener('click',calculate);['consensusVoteType','consensusAgreement','consensusControversialOnly'].forEach(id=>$(id)?.addEventListener('change',render));d?.addEventListener('click',ev=>{const imageId=ev.target.closest('[data-consensus-image]')?.dataset.consensusImage;if(imageId){d.close();window.genreactrixDirectorClassificationEngine?.open?.(imageId)||window.genreactrixImageRecordEngine?.get?.(imageId)}});$('openConsensus')?.addEventListener('click',async()=>{d.showModal();await render()})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();window.openGenreactrixConsensus=async()=>{$('consensusDialog')?.showModal();await render()};
})();
